### ISSUE TITLE
Prices differ from TraingView

### ISSUE THREAD

**Issue by alexmartin9** [fxcm/RestAPI#10]
I am comparing the prices give by the RestAPI vs the prices in TradingView (the FXCM prices, which should be the same), and apparently there are some differences:
- In the H4 timeframe, the hours are grouped differently in the API and in TradingView (e.g. in TradingView we have 10, 14, 18, 22,... and in the RestAPI 11, 15, 19, 23,...
- In the other timeframes, the prices are also slightly different

Any insight on why could be these differences?

**Comment by fxcm-dhalpert** [comment]
We are working on this issue, for now you can use Historical Data Downloader program or with Forex Connect API.
https://www.fxcmapps.com/apps/basic-historical-data-downloader/

For Forex Connect API please see:
https://github.com/fxcm/ForexConnectAPI

Regards,
Daniel Halpert

**Comment by marejp** [comment]
Perhaps the same issue. Left side of table was downloaded with fxcmpy. Right side with HDD. Seems as if there is a problem when OpenBid price stays the same.

date | bidopen | bidclose | bidhigh | bidlow | askopen | askclose | askhigh | asklow | tickqty |   | Date | OpenBid | HighBid | LowBid | CloseBid | OpenAsk | HighAsk | LowAsk | CloseAsk | Total Ticks
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
2018/12/03 01:13 | 524.25 | 524.75 | 525.0 | 524.38 | 525.0 | 525.5 | 525.75 | 525.0 | 30 |   | 12/03/2018,01:13:00 | 524,25 | 525 | 524,25 | 524,75 | 525 | 525,75 | 525 | 525,5 | 30
  |   |   |   |   |   |   |   |   |   |   | 12/03/2018,01:14:00 | 524,75 | 524,88 | 524,75 | 524,75 | 525,5 | 525,63 | 525,5 | 525,5 | 4
2018/12/03 01:15 | 524.75 | 524.5 | 524.75 | 524.5 | 525.5 | 525.25 | 525.5 | 525.25 | 18 |   | 12/03/2018,01:15:00 | 524,75 | 524,75 | 524,5 | 524,5 | 525,5 | 525,5 | 525,25 | 525,25 | 18
\|\|\|\|\| | \|\|\|\|\| | \|\|\|\|\| | \|\|\|\|\| | \|\|\|\|\| | \|\|\|\|\| | \|\|\|\|\| | \|\|\|\|\| | \|\|\|\|\| | \|\|\|\|\| |   | \|\|\|\|\| | \|\|\|\|\| | \|\|\|\|\| | \|\|\|\|\| | \|\|\|\|\| | \|\|\|\|\| | \|\|\|\|\| | \|\|\|\|\| | \|\|\|\|\| | \|\|\|\|\|
2018/12/03 01:24 | 523.0 | 523.0 | 523.25 | 523.0 | 523.75 | 523.75 | 524.0 | 523.75 | 8 |   | 12/03/2018,01:24:00 | 523 | 523,25 | 523 | 523 | 523,75 | 524 | 523,75 | 523,75 | 8
  |   |   |   |   |   |   |   |   |   |   | 12/03/2018,01:25:00 | 523 | 523 | 522,75 | 522,75 | 523,75 | 523,75 | 523,5 | 523,5 | 2
2018/12/03 01:26 | 522.75 | 523.0 | 523.0 | 522.5 | 523.5 | 523.75 | 523.75 | 523.25 | 12 |   | 12/03/2018,01:26:00 | 522,75 | 523 | 522,5 | 523 | 523,5 | 523,75 | 523,25 | 523,75 | 12
\|\|\|\|\| | \|\|\|\|\| | \|\|\|\|\| | \|\|\|\|\| | \|\|\|\|\| | \|\|\|\|\| | \|\|\|\|\| | \|\|\|\|\| | \|\|\|\|\| | \|\|\|\|\| |   | \|\|\|\|\| | \|\|\|\|\| | \|\|\|\|\| | \|\|\|\|\| | \|\|\|\|\| | \|\|\|\|\| | \|\|\|\|\| | \|\|\|\|\| | \|\|\|\|\| | \|\|\|\|\|
2018/12/03 01:29 | 522.25 | 522.0 | 522.5 | 522.0 | 523.0 | 522.75 | 523.25 | 522.75 | 44 |   | 12/03/2018,01:29:00 | 522,25 | 522,5 | 522 | 522 | 523 | 523,25 | 522,75 | 522,75 | 44
  |   |   |   |   |   |   |   |   |   |   | 12/03/2018,01:31:00 | 522 | 522 | 522 | 522 | 522,75 | 522,75 | 522,75 | 522,75 | 1
2018/12/03 01:33 | 522.0 | 521.5 | 521.75 | 521.5 | 522.75 | 522.25 | 522.5 | 522.25 | 6 |   | 12/03/2018,01:33:00 | 522 | 522 | 521,5 | 521,5 | 522,75 | 522,75 | 522,25 | 522,25 | 6
\|\|\|\|\| | \|\|\|\|\| | \|\|\|\|\| | \|\|\|\|\| | \|\|\|\|\| | \|\|\|\|\| | \|\|\|\|\| | \|\|\|\|\| | \|\|\|\|\| | \|\|\|\|\| |   | \|\|\|\|\| | \|\|\|\|\| | \|\|\|\|\| | \|\|\|\|\| | \|\|\|\|\| | \|\|\|\|\| | \|\|\|\|\| | \|\|\|\|\| | \|\|\|\|\| | \|\|\|\|\|

Regards
Johan

**Comment by fxcm-dhalpert** [comment]
The prices from HDD program are correct,

**Comment by FXCMAPI** [comment]
this is a known issue, it is on the queue. will update when it is released.
closed this thread for now.
