### ISSUE TITLE
Demo Server Down?

### ISSUE THREAD

**Issue by JonathanRayner** [fxcm/RestAPI#103]
Did the demo server go down in the last two days? Trying to debug an issue.

Are logs of downtime available anywhere?

**Comment by fxcm-dhalpert** [comment]
We had some issues with demo REST API, should be fixed now.

**Comment by pkbrown608** [comment]
i'm also troubled by the same issue, can u plz kindly update when the demo server is up? I wanna backtest my strategy with paper money before cash in live account

**Comment by FXCMAPI** [comment]
demo is up and running, what is your error?
do yo mind share your demo token?

**Comment by pkbrown608** [comment]
![image](https://user-images.githubusercontent.com/17403372/104168821-9b482e00-5439-11eb-9437-d12a4dfd8510.png)

demo token: ce2e3e89b0710ee46de03d8972bf627e31f7a745

**Comment by RebelRae** [comment]
Glad I'm not the only one. Hopefully it's an easy fix

**Comment by FelixSauer** [comment]
![Bildschirmfoto 2021-01-11 um 14 47 57](https://user-images.githubusercontent.com/46744199/104190330-3b8f5a00-541c-11eb-96ca-a1a3a8888344.jpg)

Same issue!

**Comment by FXCMAPI** [comment]
can you try again? 
ce2e3e89b0710ee46de03d8972bf627e31f7a745
woks for me .

**Comment by nicola-decao** [comment]
I have opened an account today and I am getting the same error.

**Comment by FelixSauer** [comment]
I just tried it from colab with this code and get the same error.

pip install fxcmpy python-socketio
pip install fxcmpy --upgrade
import fxcmpy
import socketio
TOKEN = 'fa432f37e03fac932e9fbbc1cfee72ac0298439b'
con = fxcmpy.fxcmpy(access_token=TOKEN, log_level='debug', server='demo', log_file='log.txt')
print(con.get_instruments())

**Comment by FXCMAPI** [comment]
fa432f37e03fac932e9fbbc1cfee72ac0298439b was not valid, please generate a new token

**Comment by FelixSauer** [comment]
> fa432f37e03fac932e9fbbc1cfee72ac0298439b was not valid, please generate a new token

Done, with no effect

**Comment by FXCMAPI** [comment]
demo environment is working. i have python 3.7.4, fxcmpy 1.2.6 and socketio 4.4.0

**Comment by FelixSauer** [comment]
With python -m pip install python-engineio==3.9 it works.
I guess it makes sense to note this in the docs!

**Comment by FXCMAPI** [comment]
thank you

**Comment by MaartenBrits** [comment]
Is the demo server down at this point in time? I was able to connect earlier, but can't now for the past 3 hours

**Comment by FXCMAPI** [comment]
Hi,

REST server seems to work a bit slower, we are looking at it. This is causing issues with fxcmpy.
Meanwhile I would suggest using REST without fxcmpy or switching to ForexConnect which is not using socketio and is faster and a lot more stable API. (https://github.com/fxcm/ForexConnectAPI)
