### ISSUE TITLE
fxcmpy ServerError: Can not connect to FXCM Server.

### ISSUE THREAD

**Issue by satinder-2000** [fxcm/RestAPI#106]
I have just installed fxcmpy (v 1.2.6) and socketio (v 5.0.4)

And started to follow the official documentation here: https://www.fxcm.com/fxcmpy/00_quick_start.html

When I try to connect to Demo server via Jupyter Notebook, I use the following code:

con = fxcmpy.fxcmpy(access_token='<MY CORRECT TOKEN>', log_level='error', server='demo', log_file='log.txt')

However, i keep getting the following error:

~/opt/anaconda3/lib/python3.8/site-packages/fxcmpy/fxcmpy.py in __init__(self, access_token, config_file, log_file, log_level, server, proxy_url, proxy_port, proxy_type)
    216             raise ServerError('**Can not find FXCM Server.**')
    217         elif self.connection_status == 'aborted':
--> 218             raise ServerError('Can not connect to FXCM Server.')
    219 
    220         self.__collect_account_ids__()

ServerError: Can not connect to FXCM Server.

Would be grateful if someone can help in understanding what could be happening here.

**Comment by nicola-decao** [comment]
I have opened an account today and I am getting the same error.

**Comment by FelixSauer** [comment]
Looks the same as #103

**Comment by FXCMAPI** [comment]
please share your dome token for further investigation.

**Comment by nicola-decao** [comment]
> please share your dome token for further investigation.

this is mine `618dbe4b606d2ded1b1af0acbbbb8c9d3f90d782`

**Comment by nicola-decao** [comment]
> > please share your dome token for further investigation.
> 
> this is mine `618dbe4b606d2ded1b1af0acbbbb8c9d3f90d782`

and I am getting 
```
>>> import fxcmpy
>>> TOKEN = "618dbe4b606d2ded1b1af0acbbbb8c9d3f90d782"
>>> con = fxcmpy.fxcmpy(access_token=TOKEN, log_level='error',
...                     server='demo', log_file='log.txt')
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/Users/nicoladecao/.anaconda3/envs/trade36/lib/python3.6/site-packages/fxcmpy/fxcmpy.py", line 218, in __init__
    raise ServerError('Can not connect to FXCM Server.')
fxcmpy.fxcmpy.ServerError: Can not connect to FXCM Server.
```

**Comment by FXCMAPI** [comment]
can you share your login/password? 
i want generate a new token and test again on my side. 
thanks

**Comment by nicola-decao** [comment]
> can you share your login/password?
> i want generate a new token and test again on my side.
> thanks

D25834216
Password1234

**Comment by FXCMAPI** [comment]
can you try this one 
9c0c815f3b5638e6cb82e2a28461e7cc753e7bd4

**Comment by nicola-decao** [comment]
> can you try this one
> 9c0c815f3b5638e6cb82e2a28461e7cc753e7bd4

It gives me the same error as before.

**Comment by FXCMAPI** [comment]
works on my side
![image](https://user-images.githubusercontent.com/13039151/104216021-8783d400-5407-11eb-8f94-f3713cc35131.png)

**Comment by nicola-decao** [comment]
> works on my side

what version of python are you using?

**Comment by FXCMAPI** [comment]
3.7.4

**Comment by nicola-decao** [comment]
with a fresh python installation (3.7.4) and only installing these 2 libraries `pip install python-socketio==4.4.0 fxcmpy`:

```
Python 3.7.4 (default, Aug 13 2019, 15:17:50) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import fxcmpy
>>> import socketio
>>> 
>>> print(fxcmpy.__version__)
1.2.6
>>> print(socketio.__version__)
4.4.0
>>> 
>>> TOKEN = "9c0c815f3b5638e6cb82e2a28461e7cc753e7bd4"
>>> con = fxcmpy.fxcmpy(access_token=TOKEN, log_level='error', server='demo', log_file='log.txt')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/nicoladecao/.anaconda3/envs/trade37/lib/python3.7/site-packages/fxcmpy/fxcmpy.py", line 218, in __init__
    raise ServerError('Can not connect to FXCM Server.')
fxcmpy.fxcmpy.ServerError: Can not connect to FXCM Server.
>>> 

```

**Comment by nicola-decao** [comment]
Is there some hidden dependence?

**Comment by FXCMAPI** [comment]
can you try 
python -m pip install python-engineio==3.9

**Comment by nicola-decao** [comment]
> can you try
> python -m pip install python-engineio==3.9

works now! :) maybe is useful to put these packages with versions in the `requirements.txt`

**Comment by nicola-decao** [comment]
Should this work if I generate a new token?

**Comment by FXCMAPI** [comment]
thank you.  will do

**Comment by Karagul** [comment]
Hi,

I have just installed fxcmpy (v 1.2.8) and python_socketio (v 4.6.1) and python_engineio (3.9)

I tried to connect to Demo server via Python.

con = fxcmpy.fxcmpy(access_token=TOKEN, log_level='error', server='demo', log_file='log.txt')
    
However, i keep getting the following error:

  File "C:\WPy64-3920\python-3.9.2.amd64\lib\site-packages\fxcmpy\fxcmpy.py", line 218, in __init__
    raise ServerError('Can not connect to FXCM Server.')

ServerError: Can not connect to FXCM Server.

How can I fix it?

**Comment by FXCM-ValentinMandev** [comment]
Hi,

You can try downgrading python-socketio to v. 4.4.
If you still have problems after that please send your username and token to api@fxcm.com, so we could check.

**Comment by fantasticDev2** [comment]
Hi, I am using 
fxcmpy - 1.2.6
python-socketio - 4.4.0
python-engineio - 3.9.0
API_TOKEN - ebc1512caeeebaa67bb20fd00bf02a77f297b74f

But I am getting this error
Can not connect to FXCM Server.
How can I fix it?

**Comment by FXCMAPI** [comment]
Hi,

Please try with:
fxcmpy - 1.3.3
python-socketio - 5.1.4
python-engineio - 4.3.1

Please note that we are in the process of depreciating REST API and the support is not expected to extend beyond March 2023.
 
We would suggest testing our ForexConnect API, which doesn’t use websocket connection and is a lot more stable than REST API.
FC API main page: https://github.com/fxcm/ForexConnectAPI 
To download FC API: http://fxcodebase.com/wiki/index.php/Download 
Python – currently it supports Python versions 3.5, 3.6 and 3.7 - https://pypi.org/project/forexconnect/  
 
The connection URL [www.fxcorporate.com/Hosts.jsp](http://www.fxcorporate.com/Hosts.jsp) is for all accounts demo and real.
To connect you need four parameters – username, password, server - “Real” or “Demo”, and url.
