### ISSUE TITLE
Issue #106 cont. fxcmpy ServerError: Can not connect to FXCM Server.

### ISSUE THREAD

**Issue by satinder-2000** [fxcm/RestAPI#107]
I opened the issue at 
https://github.com/fxcm/RestAPI/issues/106, but did not get chance to comment on it before it got closed.Anyway,
I am doing everything correct as per the discussion on the issue, but still getting the same error. I have reproduced the issue again here:
`
from platform import python_version

print(python_version())
3.9.1
import fxcmpy
import socketio
print(fxcmpy.__version__)
1.2.6
print(socketio.__version__)
5.0.4
`
As far I can see, everything looks OK so far. However, when I try to connect to the Demo Server, I get the following error:

ServerError                               Traceback (most recent call last)
<ipython-input-3-53be1043babd> in <module>
----> 1 con = fxcmpy.fxcmpy(access_token='my-valid-token', log_level='error', server='demo', log_file='log.txt')

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/fxcmpy/fxcmpy.py in __init__(self, access_token, config_file, log_file, log_level, server, proxy_url, proxy_port, proxy_type)
    216             raise ServerError('Can not find FXCM Server.')
    217         elif self.connection_status == 'aborted':
--> 218             raise ServerError('Can not connect to FXCM Server.')
    219 
    220         self.__collect_account_ids__()

ServerError: Can not connect to FXCM Server.

Please advice.

Thanks

**Comment by FXCMAPI** [comment]
Dear client

We experienced issue on demo environment .
Do you mind try generate a new token and try again?
If you still have issue, please share demo token for further investigation

Thanks
Lei

**Comment by FelixSauer** [comment]
@satinder-2000 Try this package python-engineio==3.9

**Comment by Jorgee1** [comment]
Hello @satinder-2000,

I have been doing some test regarding this. It seems that the API doesn't work with the latest version of socket-io and engine-io for python.

If you want to change any of these dependencies you have to follow the compatibility table in the link:
https://python-socketio.readthedocs.io/en/latest/intro.html#version-compatibility

I usually use the following version to interact with the service:
python-engineio==3.13.2
python-socketio==4.6.0

A couple of things to note are that python-engineio==3.9 works up to version python-socketio==4.5 (according to pip), but this throws an exception inside the library and as such I am not sure which version goes with that specific version of python-engineio.

And some times the connection with the demo server gets kind of laggy, specially during the day. Could be related to server load, not really sure. Maybe is related to what @FXCMAPI is referring to.

I de wonder if Fxcm has plans to support for the latest version on the server side.

**Comment by satinder-2000** [comment]
> Dear client
> 
> We experienced issue on demo environment .
> Do you mind try generate a new token and try again?
> If you still have issue, please share demo token for further investigation
> 
> Thanks
> Lei

Here is the new API Token, but unfortunately, I see no change: 'af6b59005e674423c28381af8df05b6562fb8d4e'

**Comment by FXCMAPI** [comment]
af6b59005e674423c28381af8df05b6562fb8d4e
is not valid anymore, please generate a new one and try again,

**Comment by FXCMAPI** [comment]
dear client 
We experienced issue on demo environment .
this has been fixed. 
please try again let let me know if issue still persist

thanks 
Lei

**Comment by HenriqueAJNB** [comment]
Hi there, I'm facing the same issue.

Here I'm using `fxcmpy==1.2.6` and get the same error as mentionet above

```
ServerError: Can not connect to FXCM Server.
```

**Comment by FXCMAPI** [comment]
Dear client

i dont see any issue on our side
can you provide demo token or sample code?

**Comment by Marcus2810** [comment]
Write I spent yesterday for ages trying to get the wrapped/ normal RestApi with SocketIO_client working to do DL stuff, so the request above works exactly as needed.

(Makesure your env is disabled)
Do this not in virtual env: 
  pip install -U fxmpy
  pip uninstall  engineio
  pip uninstall socketio
  python-engineio==3.13.2
  python-socketio==4.6.0

fxcmpy.fxcmpy(access_token=TOKEN,log_level='error',log_file=None)

**Comment by Bruhpy** [comment]
Hey @Marcus2810 , you are an absolute legend mate, your solution worked. After a whole day of trying to figure it all out this FINALLY WORKED. Its crazy that I had to uninstall engineio and socketio and reinstall older versions for it to work. Thanks once again.

**Comment by techcrewe** [comment]
Thanks, @Marcus2810, I used similar steps but made the changes inside the virtual env:
1. stayed inside the  virtual env
2. pip uninstall engineio
3. pip uninstall socketio
4. python-engineio==3.13.2
5. python-socketio==4.6.0
I basically downgraded the two packages and it resolved all issues.

**Comment by RiekertCodes** [comment]
> 
> 
> Write I spent yesterday for ages trying to get the wrapped/ normal RestApi with SocketIO_client working to do DL stuff, so the request above works exactly as needed.
> 
> (Makesure your env is disabled)
> Do this not in virtual env:
> pip install -U fxmpy
> pip uninstall engineio
> pip uninstall socketio
> python-engineio==3.13.2
> python-socketio==4.6.0
> 
> fxcmpy.fxcmpy(access_token=TOKEN,log_level='error',log_file=None)

Can you maybe tell how to disable env
And where you did those steps

**Comment by wysifu** [comment]
I did the downgrade in the Jupiter notebook terminal but socketio 5.3.0 is till running as the version in the actual notebook. how do I change this

**Comment by FXCMAPI** [comment]
Hi,
 
For installing versions in Jupyter notebook please try the following:
 
import sys
!{sys.executable} -m pip install python-socketio==4.4
!{sys.executable} -m pip install python-engineio==3.9

**Comment by rkresnadi** [comment]
Hi I am having the same issue. here's my code:
con = fxcmpy.fxcmpy(access_token='64967d42c7bae903705d6405e0faa4891a126c99', log_level='error', server='demo', log_file='log.txt')

**Comment by FXCMAPI** [comment]
Our server was down for maintenance in weekend. 
trading opens on Sundays between 5:00 PM ET and 5:15 PM ET and closes on Fridays around 4:55 PM ET

please try again after market open

**Comment by rkresnadi** [comment]
Just tried again. I think it’s Sunday 9PM EST time right now and still can’t find the server. 

below is the error: 

/usr/local/lib/python3.7/dist-packages/fxcmpy/fxcmpy.py in __init__(self, access_token, config_file, log_file, log_level, server, proxy_url, proxy_port, proxy_type)
    216             raise ServerError('Can not find FXCM Server.')
    217         elif self.connection_status == 'aborted':
--> 218             raise ServerError('Can not connect to FXCM Server.')
    219 
    220         self.__collect_account_ids__()

ServerError: Can not connect to FXCM Server.

**Comment by FXCMAPI** [comment]
Hi,

Please set log_level='debug' and send the log to api@fxcm.com

**Comment by FXCMAPI** [comment]
We did release on 1/24 that don’t support socketio-client package, 
please make sure uninstall socketio-client package
you can check this by running pip freeze
pip freeze | findstr socketio-client

Please make sure you have 
pip install python-socketio==4.4.0
pip install –U fxcmpy
python -m pip install python-engineio==3.9

import fxcmpy
import socketio
print(fxcmpy.__version__)
print(socketio.__version__)
 
TOKEN = 'your token'
con = fxcmpy.fxcmpy(access_token=TOKEN, log_level='error', server='demo', log_file='log.txt')

**Comment by FXCMAPI** [comment]
Hi,

To fix this, please install websocket-client:
python -m pip install websocket-client

**Comment by AL89** [comment]
@FXCMAPI  Which version should it be? I installed v0.5. And I tried to run my cell in Jupyter Notebook, and it takes forever (10 minutes now) to connect.

**Comment by FXCMAPI** [comment]
We did release on 1/24 that don’t support socketio-client package, 
please make sure uninstall socketio-client package if you have it
you can check this by running pip freeze
pip freeze | findstr socketio-client
