### ISSUE TITLE
{“response”:{“executed”: true,..............      {“response”:{“executed”: false,..............

### ISSUE THREAD

**Issue by chop-pixel** [fxcm/RestAPI#108]
When attempting to execute a position using fxcmpy I am either presented with one of the two following messages in my output:

{“response”:{“executed”: true,..............

{“response”:{“executed”: false,..............

How can this text be saved for later use?

**Comment by FXCMAPI** [comment]
you can 
Subscribing for Orders table:
  POST /trading/subscribe
  models=Order

**Comment by chop-pixel** [comment]
> you can
> Subscribing for Orders table:
>   POST /trading/subscribe
>   models=Order

It is till not clear to me how to save the response from the server
