### ISSUE TITLE
NodeJS - TransportError

### ISSUE THREAD

**Issue by Mko19** [fxcm/RestAPI#113]
Hello,

I tried this example code for NodeJS, but I had allways same error (pic lower).
I set a Token to new but I have still same errors.
When I change connection from HTTPS to HTTP, this second error is

https://user-images.githubusercontent.com/77933765/105638658-16670680-5e74-11eb-9790-6a1024222ef5.png

Can you help me please ?

**Comment by fxcm-dhalpert** [comment]
please check if you have installed:
socket.io-client
please try test with telent from CMD:
telnet api.fxcm.com 443

please email your username to api@fxcm.com

**Comment by Mko19** [comment]
I tested it via Telnet and I can connect to this link and port.
Package "socket.io-client" I have at version 1.7.3

**Comment by FXCMAPI** [comment]
We did release on 1/24 that don’t support socketio-client package
Please make sure you have latest fxcmpy 1.2.6 and python-socketio 4.4.0
pip install python-socketio
pip install –U fxcmpy

**Comment by Mko19** [comment]
How I wrote, with Python it worked.
But I have problem with NodeJS. I used Python only like reference.

S for now, is still NodeJS still supported?
