### ISSUE TITLE
FXCM Server reports an unknown error: {'executed': False, 'error': ''}

### ISSUE THREAD

**Issue by vnch31** [fxcm/RestAPI#115]
Hello,

I get an error when I try to retrieve data with the get_candles() function, it returns nothing and looking at the logs I get this error message : 

|ERROR|2021-02-06 15:52:43,903|FXCM Server reports an unknown error: {'executed': False, 'error': ''}.
|ERROR|2021-02-06 15:52:43,903|Can not parse server answer to json object: {"response":{"executed":false,"error":""},"instrument_id":"2","period_id":"D1","candles":[]}.

I've already tried several things like changing the API token or downgrading my socketio version but nothing works anyone have any idea why it doesn't work?
Thanks

Here is my code :

```python
import fxcmpy
import pandas as pd
import numpy as np
import socketio
```

```python
print(fxcmpy.__version__)
socketio.__version__
```

    1.2.6

    '4.6.1'

```python
# connection 
con = fxcmpy.fxcmpy(config_file='fxcm.cfg', server='demo')
```

```python
con.is_connected()
```

    True

```python
data = con.get_candles('USD/JPY', period='D1')
data
```

<div>

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>bidopen</th>
      <th>bidclose</th>
      <th>bidhigh</th>
      <th>bidlow</th>
      <th>askopen</th>
      <th>askclose</th>
      <th>askhigh</th>
      <th>asklow</th>
      <th>tickqty</th>
    </tr>
    <tr>
      <th>date</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>
</div>

```python
con.close()
```

**Comment by fxcm-dhalpert** [comment]
Please check if current version of python-engineio is 4 then install 3.9
To check the current version of python-engineio, from CMD:
python -c "import engineio; print(engineio.__version__)"
to install it:
python -m pip install python-engineio==3.9

**Comment by vnch31** [comment]
Thanks for you answer, I've installed the following version and it works : 
- fxcmpy 1.2.6
- socketio 4.6.0
- engineio 3.9.0

Do you have any others recommendation for packages version ?

**Comment by IonGuide** [comment]
Same issue; 


Import fxcmpy
con = fxcmpy.fxcmpy(access_token =token, log_level = 'error')
data = con.get_candles('EUR/USD', period='m1', number = 10)
print(data.head())
con.close()


yields: 
|ERROR|2021-02-14 11:37:05,990|FXCM Server reports an unknown error: {'executed': False, 'error': ''}.
|ERROR|2021-02-14 11:37:05,990|Can not parse server answer to json object: {"response":{"executed":false,"error":""},"instrument_id":"1","period_id":"m1","candles":[]}.
Empty DataFrame
Columns: [bidopen, bidclose, bidhigh, bidlow, askopen, askclose, askhigh, asklow, tickqty]
Index: []


engineio = 3.9.0
socket = 4.6.0
fxcmpy = 1.2.6

**Comment by FXCMAPI** [comment]
Please make sure you remove socketio-client package

**Comment by IonGuide** [comment]
It isn't installed

**Comment by FXCMAPI** [comment]
can you share your demo token?

**Comment by oscardavidrm** [comment]
I'm getting the same issue. 
Demo token `788e9fe445b468bc80386d6dcb2ea837a7de0baa`

Using:
- fxcmpy==1.2.6
- python-engineio==3.9.0
- python-socketio==4.6.0

*log.txt*
```
|ERROR|2021-07-24 12:39:08,199|FXCM Server reports an unknown error: {'executed': False, 'error': ''}.
|ERROR|2021-07-24 12:39:08,199|Can not parse server answer to json object: {"response":{"executed":false,"error":""},"instrument_id":"1","period_id":"m15","candles":[]}.
```

**Comment by spramuditha** [comment]
was this solved? I am getting the same too

**Comment by oscardavidrm** [comment]
> was this solved? I am getting the same too

I understand is a sporadic behaviour. Try building a failover retry strategy in your code and you should be ok.

**Comment by yairgd** [comment]
I get the same issue , I did exactly as describe below, and it still does not work.  What else can I do to handle it ?

**Comment by jorgeDynamite** [comment]
Getting the same issue. Has anyone fixed it?

**Comment by FXCMAPI** [comment]
please upgrade fxcmpy to latest 1.3.2

**Comment by pipchris** [comment]
@FXCMAPI it doesn't work

**Comment by FXCMAPI** [comment]
Hi @pipchris , please send your FXCM username at api@fxcm.com
