### ISSUE TITLE
socker.io connect gives parser error on latest version of the module

### ISSUE THREAD

**Issue by aaron-syed** [fxcm/RestAPI#116]
Hi folks,
I'm trying to integrate the APIs into my NodeJS framework that already uses socket.io-client for other reasons.
But when I try to connect to the socket I get a connection_error with this stack:

```
code:'parser error'
message:'server error'
stack:'Error: server error\n    at Socket.onPacket (/Users/aaron/Works/lab/trading/node-backtester/node_modules/engine.io-client/lib/socket.js:381:23)\n    at XHR.<anonymous> (/Users/aaron/Works/lab/trading/node-backtester/node_modules/engine.io-client/lib/socket.js:196:14)\n    at XHR.Emitter.emit (/Users/aaron/Works/lab/trading/node-backtester/node_modules/component-emitter/index.js:145:20)\n    at XHR.onPacket (/Users/aaron/Works/lab/trading/node-backtester/node_modules/engine.io-client/lib/transport.j…ks/lab/trading/node-backtester/node_modules/engine.io-client/lib/transports/polling.js:105:56)\n    at Request.<anonymous> (/Users/aaron/Works/lab/trading/node-backtester/node_modules/engine.io-client/lib/transports/polling-xhr.js:94:12)\n    at Request.Emitter.emit (/Users/aaron/Works/lab/trading/node-backtester/node_modules/component-emitter/index.js:145:20)\n    at Request.onData (/Users/aaron/Works/lab/trading/node-backtester/node_modules/engine.io-client/lib/transports/polling-xhr.js:235:10)'
__proto__:Object
```

I tried to pull the repo in a standalone folder, with fresh npm i etc.. and everything works fine.
What I noticed is that the version of socket.io-client module in the package.json is 1.7.1 ( which is pretty old, current is 3.1.1 ), so I think that this could be the issue. 
Anybody had any luck running it with the latest version?

Thanks in advance

**Comment by fxcm-dhalpert** [comment]
work ok with socket.io-client 2.0.3

**Comment by aaron-syed** [comment]
Yey, I think that there might have been some breaking changes lately ( from 3.0 ), and that could be the reason.
