### ISSUE TITLE
ServerError: Can not connect to FXCM Server.

### ISSUE THREAD

**Issue by hengee** [fxcm/RestAPI#117]
I have used both MacOS and Kaggle to try out the fxcmpy but both failed with the same error: ServerError: Can not connect to FXCM Server.

Tried the solutions in the closed issues by installing some specific versions of python-socketio and engineio, as well as revoking tokens.

    import fxcmpy
    import socketio
    import engineio
    
    print(fxcmpy.__version__) #1.2.6
    print(socketio.__version__) #4.6.1
    print(engineio.__version__) #3.14.2

    ---------------------------------------------------------------------------
    ServerError                               Traceback (most recent call last)
    <ipython-input-24-2528f4677f88> in <module>
          1 TOKEN = 'cd8428ef012ce7df090f7a743d279259872ebf84'
    ----> 2 con = fxcmpy.fxcmpy(access_token = TOKEN, log_level = 'error', server='demo')
          3 instruments = con.get_instruments()
          4 print(instruments[:5]) ['EUR/USD', 'USD/JPY', 'GBP/USD', 'USD/CHF', 'EUR/CHF']

    /opt/conda/lib/python3.7/site-packages/fxcmpy/fxcmpy.py in __init__(self, access_token, config_file, log_file, log_level, server, proxy_url, proxy_port, proxy_type)
        216         elif self.connection_status == 'aborted':
        217             raise ServerError('Can not connect to FXCM Server.')
    --> 218 
        219         self.__collect_account_ids__()
        220         self.default_account = self.account_ids[0]

    ServerError: Can not connect to FXCM Server.

**Comment by FXCMAPI** [comment]
Dear client

First make sure your token is valid, 
you can verify on our test program 
restapi101.herokuapp.com/
If you still have issue, please provide sample code for further investigation.

thanks
Lei

**Comment by superlyb** [comment]
works on 
print(sys.version) == 3.7.2 
print(fxcmpy.__version__) == 1.2.6
print(socketio.__version__) == 4.4.0
