### ISSUE TITLE
python thread clean exit

### ISSUE THREAD

**Issue by prodipta** [fxcm/RestAPI#12]
Hi, the connection thread sometimes causes a problem if the main thread raises exceptions. Can we please set this thread as daemon to make sure the program exits gracefully if the main thread exits: at below 
[here](https://github.com/fxcm/RestAPI/blob/master/fxcmpy/fxcmpy/fxcmpy.py#L279) add: 

`self.socket_thread.daemon = True` 

Or let me know if you suggest some other workaround if this is not feasible. Thx vm.

**Comment by FXCMAPI** [comment]
Hello Prodipta

thank you for your suggestion, 
we are looking into it, will update you the progress. 

Best regards
Lei

**Comment by fxcm-dhalpert** [comment]
can you please email us (to api@fxcm.com) how to replicate this issue, if you have any test code it may help.

thanks,
Daniel

**Comment by prodipta** [comment]
Done - from a different ID than this. Thx vm.
