### ISSUE TITLE
Api giving incorrect data

### ISSUE THREAD

**Issue by miguelhroca** [fxcm/RestAPI#122]
Hi, the API is giving data randomly, if I check the prices on the App, and the data given by the API they don´t match

![image](https://user-images.githubusercontent.com/47392116/110166214-52d33e00-7df4-11eb-9d2a-537da9a36184.png)
![image](https://user-images.githubusercontent.com/47392116/110166228-5797f200-7df4-11eb-80af-c34c777a533a.png)

There is a huge difference on the prices shown, is that known issue?

I can't get my algorithm to work if the prices are not the same as the app's

a response would be appreciated,

Thanks

**Comment by RojoCT** [comment]
I am having the same issue, an answer would be apreciated.

Thanks.

**Comment by FXCMAPI** [comment]
Hi

is the above screen shot from TSII desktop or tsweb? 
do they have the same time zone on same account account?

thanks
Lei

**Comment by miguelhroca** [comment]
yes it´s from the TSII desktop UTC time (london) in both (TSII and API) they have the same time zone, and some of the data matches, but the majority doesnt

**Comment by fxcm-dhalpert** [comment]
The REST API historical data gets updated over the weekend with same data as you see in Trading Station desktop.

**Comment by RojoCT** [comment]
What is the cause of this?

I understand that the historical data does not match with the data you actually use during the week.

**Comment by FXCMAPI** [comment]
we are still looking into it.
