### ISSUE TITLE
please help me

### ISSUE THREAD

**Issue by jfpaniago** [fxcm/RestAPI#123]
ServerError: Can not connect to FXCM Server.
![image](https://user-images.githubusercontent.com/80187324/110229007-c3f21e80-7ee4-11eb-8cc2-0e3673bd2ca3.png)

**Comment by jfpaniago** [comment]
Exception in thread Thread-13:
Traceback (most recent call last):
  File "c:\users\joao francisco note\appdata\local\programs\python\python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "c:\users\joao francisco note\appdata\local\programs\python\python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\joao francisco note\appdata\local\programs\python\python38\lib\site-packages\engineio\client.py", line 635, in _write_loop
    self.ws.send(encoded_packet)
  File "C:\Users\Joao Francisco Note\AppData\Roaming\Python\Python38\site-packages\websocket\_core.py", line 282, in send
    return self.send_frame(frame)
  File "C:\Users\Joao Francisco Note\AppData\Roaming\Python\Python38\site-packages\websocket\_core.py", line 310, in send_frame
    l = self._send(data)
  File "C:\Users\Joao Francisco Note\AppData\Roaming\Python\Python38\site-packages\websocket\_core.py", line 510, in _send
    return send(self.sock, data)
  File "C:\Users\Joao Francisco Note\AppData\Roaming\Python\Python38\site-packages\websocket\_socket.py", line 168, in send
    return _send()
  File "C:\Users\Joao Francisco Note\AppData\Roaming\Python\Python38\site-packages\websocket\_socket.py", line 150, in _send
    return sock.send(data)
  File "c:\users\joao francisco note\appdata\local\programs\python\python38\lib\ssl.py", line 1173, in send
    return self._sslobj.write(data)
ssl.SSLError: [SSL: BAD_LENGTH] bad length (_ssl.c:2474)
|ERROR|2021-03-07 01:42:03,681|Connection aborted, failed to reconnect
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-9-23d9b046cca0> in <module>
----> 1 con = fxcmpy.fxcmpy(access_token=token,log_level='error',log_file=None,)

~\AppData\Roaming\Python\Python38\site-packages\fxcmpy\fxcmpy.py in __init__(self, access_token, config_file, log_file, log_level, server, proxy_url, proxy_port, proxy_type)
    218             raise ServerError('Can not connect to FXCM Server.')
    219 
--> 220         self.__collect_account_ids__()
    221         self.default_account = self.account_ids[0]
    222         msg = 'Default account set to %s, to change use set_default_account().'

~\AppData\Roaming\Python\Python38\site-packages\fxcmpy\fxcmpy.py in __collect_account_ids__(self)
   2225 
   2226         self.account_ids = set()
-> 2227         data = self.get_accounts('list')
   2228         for acc in data:
   2229             if 'accountId' in acc and acc['accountId'] != '':

~\AppData\Roaming\Python\Python38\site-packages\fxcmpy\fxcmpy.py in get_accounts(self, kind)
    510 
    511         """
--> 512         data = self.get_model(('Account',))
    513         accounts = data['accounts']
    514         if kind == 'list':

~\AppData\Roaming\Python\Python38\site-packages\fxcmpy\fxcmpy.py in get_model(self, models, summary)
    342                 raise ValueError('Models have to be of %s' % self.models)
    343 
--> 344         data = self.__handle_request__(method='trading/get_model',
    345                                        params={'models': list(models)})
    346 

~\AppData\Roaming\Python\Python38\site-packages\fxcmpy\fxcmpy.py in __handle_request__(self, method, params, protocol)
   2434         if not self.is_connected():
   2435             self.logger.error('Connection aborted, failed to reconnect')
-> 2436             raise IOError('Connection aborted, failed to reconnect')
   2437 
   2438         self.socket_id = self.socket.sid

OSError: Connection aborted, failed to reconnect

**Comment by jfpaniago** [comment]
please need help with this..
i've tryied everything.. dl all the packages but I still get this message
![image](https://user-images.githubusercontent.com/80187324/110245502-2af1f080-7f42-11eb-831b-16cc28e4c5e6.png)

**Comment by jfpaniago** [comment]
|ERROR|2021-03-07 12:45:29,369|Connection error: Your token is not authorized, please contact admin@fxcm.com

**Comment by FXCMAPI** [comment]
Dear client

our server was down in weekend for maintenance. 
please try again now, 
if you still have issue, please share your demo token or further investigation.

**Comment by jfpaniago** [comment]
sir, 
7bb98a981628726a9534889b662befb20479e64b
this is my token..

**Comment by FXCMAPI** [comment]
your token is working on my side

![image](https://user-images.githubusercontent.com/13039151/110335785-3ac90d80-7ff2-11eb-974e-42f14797b035.png)

**Comment by jfpaniago** [comment]
thank you soo much.. i've been trying to connect for a long time, now it works !!!!! tytytyty
________________________________
De: FXCM <notifications@github.com>
Enviado: segunda-feira, 8 de março de 2021 12:40
Para: fxcm/RestAPI <RestAPI@noreply.github.com>
Cc: jfpaniago <jf.paniago@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [fxcm/RestAPI] please help me (#123)


your token is working on my side

[image]<https://user-images.githubusercontent.com/13039151/110335785-3ac90d80-7ff2-11eb-974e-42f14797b035.png>
