### ISSUE TITLE
Can not parse server answer to json object:

### ISSUE THREAD

**Issue by Pilipets** [fxcm/RestAPI#124]
Guys, why can't you specify the required versions of _python-socketio, python-engineio_ in the fxcmpy package to avoid all the version-related errors?

Firstly, fxcmpy doesn't work with the latest _python-engineio_ as describe here https://github.com/fxcm/RestAPI/issues/58, https://github.com/fxcm/RestAPI/issues/121, that's why I downgraded it to
`python-engineio==3.9.0`
`python-socketio==4.6.1`
`fxcmpy==1.2.6`.

Now I can connect to my demo account using
`con = fxcmpy.fxcmpy(access_token = '8a3512096ee8533b9100f9d42aa9bd58106d93cf', log_level = 'error', server='demo')`

But the problem comes when I try to fetch the candles_data.
`data = con.get_candles('EUR/USD', period='M1', number=5)`

The error is :
|ERROR|2021-03-13 18:47:40,762|FXCM Server reports an unknown error: {'executed': False, 'error': ''}.
|ERROR|2021-03-13 18:47:40,763|Can not parse server answer to json object: {"response":{"executed":false,"error":""},"instrument_id":"1","period_id":"M1","candles":[]}.

What does that mean? Could someone help?

**Comment by longwall78** [comment]
@Pilipets I'm also having an issue with getting candles - see #125
I'm not getting an error message; instead it's returning an empty dataframe.

**Comment by FXCMAPI** [comment]
Dear client

Our system stopped in weekend. 
opens on Sundays between 5:00 PM ET and 5:15 PM ET. The trading desk closes on Fridays at 4:55 PM ET

please try again let me know if you have any questions

best regards
Lei

**Comment by longwall78** [comment]
Understood. Thanks heaps Lei.
