### ISSUE TITLE
Missing candles

### ISSUE THREAD

**Issue by longwall78** [fxcm/RestAPI#125]
Hi, 

Is there a known issue with retrieving candles via the RestAPI using fxcmpy at the moment?

I have confirmed that I have a connection to the demo server, however using 
`con.get_candles('AUD/USD',period='m1',number=2);`

produces an empty dataframe.

**Comment by FXCMAPI** [comment]
we are looking into it.

**Comment by FXCMAPI** [comment]
Dear client

This is resolved. 
Please try again

Best regards
Lei

**Comment by longwall78** [comment]
Thanks @FXCMAPI !

Working now. Appreciate it Lei.
