### ISSUE TITLE
Using api with Django

### ISSUE THREAD

**Issue by jtblog** [fxcm/RestAPI#126]
Has anyone ever tried using FXCM rest api with Django.
I was able to login, get historical data and do all sorts of stuff except streaming. 

I am stuck at streaming. My listener function/callback handler is not being triggered after page/template has finished loading in the browser. 

Oh. It triggers the callback function onces. Then it stops as page stops. I also need it to run asynchronously/background. It makes my page load for too long. Any help would be highly appreciated.

**Comment by Jorgee1** [comment]
I have, but using a separate process for fxcm related stuff. I just send the streamed data to the django server using django rest framework.

I am currently running on to a different problem. After x amount of hours the fxcm api rejects my requests for placing orders, giving me an "Unauthorized" error.

**Comment by FXCMAPI** [comment]
Our rest API use socket and it is stateful connection
Our authentication is Bearer + SessionID + Token.  It use socket to push the update to client. 
"unauthorized" error probably means your Bearer string was different with our server, may due to session was disconnected. 
if you can provide the Json message logs we can do further investigation,

**Comment by Jorgee1** [comment]
Ok, do you have some sort of timeout for the SessionID on the server side?

Here are the most recent log (GMT). I successfully connect to the server and receive the id gdKqcAYpB0oSCM9qAP3s, but around 7 hours later the program is unable to operate.

Disconnections and re connections are strangely common, but they do appear on the logs. Not the case this time.
The "{'error': 'Unauthorized'}" comes from the server.

Mar 31 23:19:08: Enviroment: demo
Mar 31 23:19:08: Fxcm URL: https://api-demo.fuhuisupport.com
Mar 31 23:19:08: Connected gdKqcAYpB0oSCM9qAP3s
Mar 31 23:19:08: Total active orders: 0
Mar 31 23:19:08: Message channels cleaned
Mar 31 23:19:08: Account: *********
Mar 31 23:19:08: Active bot list:
Mar 31 23:19:08: <US Median 4 US30 m15>
Mar 31 23:19:08: <US Median 3 US30 m15>
Mar 31 23:19:08: Synced 2021-03-31 23:19:08.862194+00:00
Apr 01 07:47:29: Unable to place order US Median 4 {'error': 'Unauthorized'} gdKqcAYpB0oSCM9qAP3s
Apr 01 07:47:29: Unable to place order US Median 3 {'error': 'Unauthorized'} gdKqcAYpB0oSCM9qAP3s
Apr 01 08:00:08: Unable to place order US Median 4 {'error': 'Unauthorized'} gdKqcAYpB0oSCM9qAP3s
Apr 01 08:00:08: Unable to place order US Median 3 {'error': 'Unauthorized'} gdKqcAYpB0oSCM9qAP3s
Apr 01 08:15:06: Unable to place order US Median 4 {'error': 'Unauthorized'} gdKqcAYpB0oSCM9qAP3s

**Comment by FXCMAPI** [comment]
do you mind share your username/pass and token for your demo account?

**Comment by Jorgee1** [comment]
Not through the github issue.
It is quite difficult to catch this in the wild. I have been monitoring it today but it hasn´t happened again, but when it happens it could potentially cause big looses.

Btw, @jtblog could you explain how are you setting up the django server/client code?

You mention templates, but if you want to do things from the browser side you need some sort of javascript code running.

**Comment by FXCMAPI** [comment]
we are not sure how Django handle stateful session. can't provide help.
