### ISSUE TITLE
Cannot connect but not server error. 

### ISSUE THREAD

**Issue by Yamsat** [fxcm/RestAPI#129]
Hi,

I am trying to connect to the server. But it wouldn't connect.  It doesn't return error, either. it just keeps loading...
My environment is python 3.7.4. Soketio 4.4.0 and Engineio 3.9 are installed.

![image](https://user-images.githubusercontent.com/50951444/112391920-bf36c280-8d4c-11eb-8375-ac364db82cc7.png)

Please help.

Thanks.

**Comment by fxcm-dhalpert** [comment]
please try to put the login parameters in fxcmpy() function without using CFG file.
If still not working please email the username to api@fxcm.com

**Comment by Yamsat** [comment]
I worked. Thanks!

It actually worked with the configuration file before.  It stopped working after I had not used API for quite a while.  Can you think of any solution to make it usable again?

**Comment by fxcm-dhalpert** [comment]
might be because it can't find the CFG file
