### ISSUE TITLE
Can not connect to FXCM Server.

### ISSUE THREAD

**Issue by lmate17** [fxcm/RestAPI#130]
Hi,
I'm new to rest_api (and also not a veteran of coding either:).
I have a similar problem which was introduced in @harshdeep3 's thread #128 (quoted below).
I have been trying to connect, but I haven't even once succeeded.
At first I got the standard 'Can not connect to FXCM Server.' message, then when I degraded socketIO (4.6.1), engineIO (3.9) it changed to this 'pending' message, then error.
I also tried with new token, and I also reinstalled/downgraded fxcmpy to 1.2.6.
Now it loads forever, my Kernel stuck.
Could someone help what else should I do? What versions should I have?
Could @FXCMAPI check my token?
I'm kind of lost at this point.
Thanks in advance!

I uninstalled python-socketio version 5.1.0, and installed version 4.6.1, this then changes the error to
"---------------------------------------------------------------------------
ServerError                               Traceback (most recent call last)
<ipython-input-6-fdf1eb031be7> in <module>
----> 1 con = fxcmpy.fxcmpy(access_token=token, log_level='error', log_file='none')

~\anaconda3\lib\site-packages\fxcmpy\fxcmpy.py in __init__(self, access_token, config_file, log_file, log_level, server, proxy_url, proxy_port, proxy_type)
    214 
    215         if self.connection_status == 'pending' and count == 50:
--> 216             raise ServerError('Can not find FXCM Server.')
    217         elif self.connection_status == 'aborted':
    218             raise ServerError('Can not connect to FXCM Server.')

ServerError: Can not find FXCM Server.
"

_Originally posted by @harshdeep3 in https://github.com/fxcm/RestAPI/issues/128#issuecomment-803681477_

**Comment by FXCM-ValentinMandev** [comment]
Hi,
Please send your username and token at api@fxcm.com for further investigation.

**Comment by lmate17** [comment]
Thank you for your fast response! I sent it to you.

**Comment by lmate17** [comment]
Thank you Valentin for solving my problem!
For others, who might have the same issue it worked for me, when:

- downgraded fxcmpy to 1.2.6 (pip install fxcmpy==1.2.6)
- downgraded socketio to 4.4 (pip install python-socketio==4.4)
- downgraded engineio to 3.9 (pip install python-engineio==3.9)
- checked the validity of my token 
- restarted my computer
- (also set log_level='debug' >> con = fxcmpy.fxcmpy(access_token=TOKEN, log_level='debug', server='demo', log_file='log.txt'))
