### ISSUE TITLE
AttributeError: module 'socketio' has no attribute 'Client'

### ISSUE THREAD

**Issue by gertsch123** [fxcm/RestAPI#133]
Hi
I'm getting the following error
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-55-36e262b113bd> in <module>
----> 1 import fxcmpy
      2 import socketio

~\Anaconda3\lib\site-packages\fxcmpy\__init__.py in <module>
----> 1 from fxcmpy.fxcmpy import fxcmpy as fxcmpy
      2 from fxcmpy.fxcmpy_open_position import fxcmpy_open_position
      3 from fxcmpy.fxcmpy_closed_position import fxcmpy_closed_position
      4 from fxcmpy.fxcmpy_order import fxcmpy_order
      5 from fxcmpy.fxcmpy_oco_order import fxcmpy_oco_order

~\Anaconda3\lib\site-packages\fxcmpy\fxcmpy.py in <module>
     30 from urllib.parse import unquote
     31 
---> 32 socketIO = socketio.Client()
     33 socket = socketIO;
     34

**Comment by FXCMAPI** [comment]
![image](https://user-images.githubusercontent.com/13039151/116742731-cd1fd900-a9c5-11eb-81d9-ed87295175a5.png)
