### ISSUE TITLE
FXCMPY returns Empty DataFrame

### ISSUE THREAD

**Issue by etutuit** [fxcm/RestAPI#134]
Hi, 

I found few similar topics but no luck in finding solution.

Error log shows such errors:
```
|ERROR|2021-04-24 18:09:55,810|FXCM Server reports an unknown error: {'executed': False, 'error': ''}.
|ERROR|2021-04-24 18:09:55,810|Can not parse server answer to json object: {"response":{"executed":false,"error":""},"instrument_id":"1","period_id":"M1","candles":[]}.
```
Versions of related packages:
```
fxcmpy==1.2.8 
python-engineio==3.13.2
python-socketio==4.6.0
```

Command returning empty dataframe:
```
>>> con.get_candles('EUR/USD', period='M1', number=100)
Empty DataFrame
Columns: [bidopen, bidclose, bidhigh, bidlow, askopen, askclose, askhigh, asklow, tickqty]
Index: []
```

Connection works fine, get_instruments_for_candles too, just no luck in retrieving data.

Regards

**Comment by ImronD** [comment]
I'm having the same issue.

**Comment by FXCMAPI** [comment]
Our server was down in weekend for maintenance. 
The trading desk opens on Sundays between 5:00 PM ET and 5:15 PM ET
Please try now and let me know if you still have issue
