### ISSUE TITLE
ServerError: Can not connect to FXCM Server

### ISSUE THREAD

**Issue by Frankeke** [fxcm/RestAPI#136]
Traceback (most recent call last):
  File "C:\Users\Franck\Documents\Proyectos Python\Main.py", line 3, in <module>
    con = fxcmpy.fxcmpy(access_token='874faa21949310288715e84a4a0528ef62ed38d6', log_level='error', server='demo', log_file='log.txt')
  File "C:\Users\Franck\Documents\Proyectos Python\venv\lib\site-packages\fxcmpy\fxcmpy.py", line 206, in __init__
    raise ServerError('Can not connect to FXCM Server.')
fxcmpy.fxcmpy.ServerError: Can not connect to FXCM Server.

I have this problem with FXCM and I don't know how to fix it. anyone have any idea how to fix?

I'd appreciate your help.

**Comment by FXCMAPI** [comment]
Dear client 
your token is working fine on my side. 
![image](https://user-images.githubusercontent.com/13039151/116333653-d2044300-a7a1-11eb-8b49-7fe2c79fee85.png)

![image](https://user-images.githubusercontent.com/13039151/116333623-c44ebd80-a7a1-11eb-923f-e0afa01feffb.png)

**Comment by Frankeke** [comment]
![image](https://user-images.githubusercontent.com/56119683/116435505-6cec3400-a819-11eb-8f36-09959849e70e.png)


I see everything correct and still it does not connect me to the server, I even tried with a version of socketio 5.2.1 and the problem continues

I'd appreciate your help.

**Comment by FXCM-ValentinMandev** [comment]
Hi,

Your token is not valid anymore, please generate a new one from your account at https://tradingstation.fxcm.com
