### ISSUE TITLE
QUESTION: Why I can't create an entry order without take profit limit from the fxcmpy?

### ISSUE THREAD

**Issue by Pilipets** [fxcm/RestAPI#139]
I don't understand why I can't create the entry order without defining the take profit limit from the fxcmpy, but it's available on the FXCM trading station desktop.

```
order = api.create_entry_order('EUR/USD', True, 10, 'GTC', rate=1.20487)
```

```
|ERROR|2021-05-03 16:35:20,353|Server reports an error: {'executed': False, 'error': '{"code":19,"message":"The Limit distance must be > 0","parameters":[">",0]}'}.
|ERROR|2021-05-03 16:35:20,354|URL: https://api-demo.fxcm.com:443/trading/create_entry_order
|ERROR|2021-05-03 16:35:20,355|Headers: {'User-Agent': 'request', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'Bearer OhaUE01YyWuURDNjADjQf3d78c178d0239de359a9cc3df8a448bb8355b8e', 'Content-Type': 'application/x-www-form-urlencoded', 'Content-Length': '131'}
|ERROR|2021-05-03 16:35:20,356|Params: {'account_id': 1611450, 'symbol': 'EUR/USD', 'is_buy': 'true', 'rate': 1.20487, 'amount': 10, 'limit': 0.0, 'order_type': 'Entry', 'is_in_pips': 'true', 'time_in_force': 'GTC'}
|ERROR|2021-05-03 16:35:20,357|Bearer token: Bearer OhaUE01YyWuURDNjADjQf3d78c178d0239de359a9cc3df8a448bb8355b8e
|ERROR|2021-05-03 16:35:20,358|Connection status: established
|ERROR|2021-05-03 16:35:20,359|Socket session id: OhaUE01YyWuURDNjADjQ
|ERROR|2021-05-03 16:35:20,360|Can not parse server answer to json object: {"response":{"executed":false,"error":"{\"code\":19,\"message\":\"The Limit distance must be > 0\",\"parameters\":[\">\",0]}"},"data":{}}.
```

When I specify the take_profit `order = api.create_entry_order('EUR/USD', True, 10, 'GTC', rate=1.20487, limit=1.20488)`, it works.
But I don't want to - `limit=None` should be available for entry orders as it's for the market ones and desktop trading station.

**Comment by FXCMAPI** [comment]
please remove 'limit': 0.0, and  'is_in_pips': 'true',

**Comment by Pilipets** [comment]
Thanks, will try.

**Comment by Pilipets** [comment]
> please remove 'limit': 0.0, and 'is_in_pips': 'true',

How can I remove 'limit':0.0? My question was, why can't I create the order without setting the profit limit??

I can create entry orders without limit from the trading desktop station or for a market order, but it's not allowed for entry ones...

**Comment by FXCMAPI** [comment]
you can remove the whole field, means you don't pass the tag limit and its value.

**Comment by Pilipets** [comment]
> you can remove the whole field, means you don't pass the tag limit and its value.

it equals to zero in create_entry_order method by default

**Comment by FXCMAPI** [comment]
can you try below 
con.create_entry_order(symbol='EUR/USD', is_buy=True,
                               amount=1, order_type='Entry', is_in_pips = False,
                               time_in_force='GTC', rate=1.1650)

**Comment by Pilipets** [comment]
I'm unable to establish a connection, it says `|ERROR|2021-05-04 00:11:06,661|Connection error: Your token is not authorized, please contact admin@fxcm.com`, but I recreated the token several times - last one was 28b8453fcddff9e01d4cad347b6a350d64348552

**Comment by Pilipets** [comment]
> can you try below
> con.create_entry_order(symbol='EUR/USD', is_buy=True,
> amount=1, order_type='Entry', is_in_pips = False,
> time_in_force='GTC', rate=1.1650)

No, it doesn't work. I don't understand the reason you closed the issue.

```
order = api.create_entry_order(symbol='EUR/USD', is_buy=True,
amount=1, order_type='Entry', is_in_pips = False,
time_in_force='GTC', rate=1.20656)
|ERROR|2021-05-04 00:31:10,523|Server reports an error: {'executed': False, 'error': '{"code":8,"message":"The Limit rate must be > 1.20656","parameters":[">",1.20656]}'}.
|ERROR|2021-05-04 00:31:10,524|URL: https://api-demo.fxcm.com:443/trading/create_entry_order
|ERROR|2021-05-04 00:31:10,525|Headers: {'User-Agent': 'request', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'Bearer iGPg9mrfsLSJpVC0AErp28b8453fcddff9e01d4cad347b6a350d64348552', 'Content-Type': 'application/x-www-form-urlencoded', 'Content-Length': '131'}
|ERROR|2021-05-04 00:31:10,526|Params: {'account_id': 1611450, 'symbol': 'EUR/USD', 'is_buy': 'true', 'rate': 1.20656, 'amount': 1, 'limit': 0.0, 'order_type': 'Entry', 'is_in_pips': 'false', 'time_in_force': 'GTC'}
|ERROR|2021-05-04 00:31:10,526|Bearer token: Bearer iGPg9mrfsLSJpVC0AErp28b8453fcddff9e01d4cad347b6a350d64348552
|ERROR|2021-05-04 00:31:10,527|Connection status: established
|ERROR|2021-05-04 00:31:10,528|Socket session id: iGPg9mrfsLSJpVC0AErp
|ERROR|2021-05-04 00:31:10,528|Can not parse server answer to json object: {"response":{"executed":false,"error":"{\"code\":8,\"message\":\"The Limit rate must be > 1.20656\",\"parameters\":[\">\",1.20656]}"},"data":{}}.
```

**Comment by Pilipets** [comment]
The code of the package needs to be modified:

```
    def create_entry_order(..., limit=0, ...): -> def create_entry_order(..., limit=None, ...): ->
```

Then add here checking for None
```
        if limit is not None:
            try:
                limit = float(limit)
                ....
                
                params = {
                  # Remove limit from here
                 }

        if limit is not None:
            params['limit'] = limit
```

**Comment by fxcm-dhalpert** [comment]
to create entry order only with stop price please use REST API directly without fxcmpy wrapper

**Comment by Pilipets** [comment]
> to create entry order only with stop price please use REST API directly without fxcmpy wrapper

Thanks, but is it planning to be changed in the upcoming releases? The fix is simple

**Comment by ordimans** [comment]
Not still fixed ?
Have this error sometime  : 
Buy at market price :
`symbol: "NAS100"
    is_buy: true
    amount: 10
    at_market: 0
    order_type: "AtMarket"
    time_in_force: "GTC"
    limit: 11339.31

    response: {
      "executed": false,
      "error": "{\"code\":8,\"message\":\"The Limit rate must be > 11342.77\",\"parameters\":[\">\",11342.77]}"
    }
    data: {}`

**Comment by fxcm-dhalpert** [comment]
The exit Limit price for a long position should be above the current market price.
