### ISSUE TITLE
Price stream disconnects 

### ISSUE THREAD

**Issue by zbanga** [fxcm/RestAPI#14]
No way of knowing if streaming is disconnected. If left for a long period of time no way of knowing if 
the stream has disconnected and it does not actively re-establish streaming?

**Comment by fxcm-pguz** [comment]
Hi,

You can tell if stream has been disconnected by attaching a callback to 'disconnect' signal in socketIO:
socket.on('disconnect',disconnect_function)

Best Regards,
Pawel

**Comment by zbanga** [comment]
Hi Pawel,

Thanks for the prompt reply! I was wondering if you could try giving an example using fxcmpy? 

I tried creating a function that attaches the callback but I am still unable to get it working?

Kind Regards,

Ben
