### ISSUE TITLE
ISSUE: fxcmpy connection unexpectedly drops after several minutes.

### ISSUE THREAD

**Issue by Pilipets** [fxcm/RestAPI#140]
I created the fxcmpy instance and waited several minutes, then the connection drops?!
It's not a one-time issue - the problem persists...

The issue appeared at the weekends but remains till now - the flow is simple:
1. Connection establishment.
2. Working perfectly for several minutes - waiting or performing queries, doesn't matter.
3. Received in the output `|INFO|2021-05-03 17:40:54,558|Disconnected.`.
4. Now, the connection isn't established, of course...
`data = bot.get_open_positions()`

```
|INFO|2021-05-03 17:52:56,890|In handle_request with method trading/get_model
|INFO|2021-05-03 17:52:56,891|Connection status: False
|INFO|2021-05-03 17:52:56,893|2. connection status: unset
|INFO|2021-05-03 17:52:56,894|Socket state: False
|INFO|2021-05-03 17:52:56,895|Thread state: True
|INFO|2021-05-03 17:52:56,895|Thread name: Thread-5
|INFO|2021-05-03 17:52:56,896|Socket id: dglgt0C1ZE1m0ZxrAQJy
|DEBUG|2021-05-03 17:52:56,897|Access token: cf33c0e6fe82c715532709f09aa8207986e290f7.
|ERROR|2021-05-03 17:52:56,898|Socket returns unknown error.
|ERROR|2021-05-03 17:52:56,899|Connection aborted, failed to reconnect
Traceback (most recent call last):

  File "<ipython-input-5-31700e553e07>", line 1, in <module>
    data = bot.get_open_positions()

  File "E:\Programming\trading-env\lib\site-packages\fxcmpy\fxcmpy.py", line 372, in get_open_positions
    data = self.get_model(('OpenPosition',))

  File "E:\Programming\trading-env\lib\site-packages\fxcmpy\fxcmpy.py", line 344, in get_model
    data = self.__handle_request__(method='trading/get_model',

  File "E:\Programming\trading-env\lib\site-packages\fxcmpy\fxcmpy.py", line 2436, in __handle_request__
    raise IOError('Connection aborted, failed to reconnect')

OSError: Connection aborted, failed to reconnect
```
```
fxcmpy==1.2.6 or fxcmpy==1.2.8
python-dateutil==2.8.1
python-engineio==3.9.0 or python-engineio==3.13.0
python-socketio==4.6.0
websocket-client==0.58.0
websockets==8.1
```
Any suggestions here?

**Comment by FXCMAPI** [comment]
please set the log level to debug and provide the logs for further investigation

**Comment by Pilipets** [comment]
> please set the log level to debug and provide the logs for further investigation

It's debugging already, as you can see by `|DEBUG|2021-05-03 17:52:56,897|Access token: cf33c0e6fe82c715532709f09aa8207986e290f7.`

Nothing wrong happens, it's just the handler - `self.socket.on('disconnect',self.__on_disconnect__)` - executed.

```
    def __on_disconnect__(self, msg=''):
        self.bearer_token = None
        self.socket_id = None
        self.connection_status = 'unset'
        self.logger.info('Disconnected.')
```

**Comment by FXCMAPI** [comment]
your token working on my side 
![image](https://user-images.githubusercontent.com/13039151/116906598-7a852d80-ac0e-11eb-93a3-4e3ece87010c.png)

**Comment by Pilipets** [comment]
> your token working on my side
> ![image](https://user-images.githubusercontent.com/13039151/116906598-7a852d80-ac0e-11eb-93a3-4e3ece87010c.png)

Could you wait up to 5 minutes after the connection? As I specified, it drops after several minutes

**Comment by Pilipets** [comment]
Alright, there was a problem with the `python-socketio` and `python-engineio` versions.

`python-engineio==3.13.0` and `python-socketio==4.6.1` worked.
Isn't it better to provide a `requirements.txt` file with the fxcmpy releases as It would close a lot of package version-related questions?

**Comment by FXCMAPI** [comment]
that is a good advice, thank you
