### ISSUE TITLE
Installing fxcmpy demo on clean system throws socketio connectionerror

### ISSUE THREAD

**Issue by lz-public** [fxcm/RestAPI#141]
Tried this on MacOs, Windows and Ubuntu on clean OS. 
1) Fresh installation of Python 3.8
2) pip install fxcmpy
2) pip install python-socketio
3) Run command:
/RestAPI/fxcm-api-rest-python3-example# python3 fxcm_rest_client_sample.py

Response:
Traceback (most recent call last):
  File "fxcm_rest_client_sample.py", line 7, in <module>
    trader.login()
  File "/RestAPI/fxcm-api-rest-python3-example/fxcm_rest_api_token.py", line 123, in login
    self.socketIO.connect(self.environment.get("trading") +':'+ str(self.environment.get("port")) + '/?access_token='+  self.access_token)
  File "/usr/local/lib/python3.8/dist-packages/socketio/client.py", line 304, in connect
    raise exceptions.ConnectionError(exc.args[0]) from None
socketio.exceptions.ConnectionError: OPEN packet not returned by server

Tried with different tokens. However, I get always the same result. Any hints? Thanks.

**Comment by FXCM-ValentinMandev** [comment]
Hi,

Please try with python-socketio version 4.4 and python-engineio version 3.9
python -m pip install python-socketio==4.4
python -m pip install python-engineio==3.9

**Comment by lz-public** [comment]
This worked. Thank you!
