### ISSUE TITLE
 Can not connect to FXCM Server

### ISSUE THREAD

**Issue by bisaga-felix** [fxcm/RestAPI#142]
I'm trying to connect to FXCM API with the following code:

```
import fxcmpy as fx

print(fx.__version__) #1.2.9
TOKEN = 'TOKEN'
con = fx.fxcmpy(access_token=TOKEN, log_level='debug', log_file='error.txt')
```

But I'm getting this error:

```
|INFO|2021-05-17 20:46:40,678|Connecting FXCM Server
|DEBUG|2021-05-17 20:46:40,678|Access token: <TOKEN>.
|DEBUG|2021-05-17 20:46:40,688|Starting new HTTPS connection (1): api-demo.fxcm.com:443
|DEBUG|2021-05-17 20:46:40,978|https://api-demo.fxcm.com:443 "GET /socket.io/?access_token=<PARAMETER> HTTP/1.1" 403 None
|ERROR|2021-05-17 20:46:40,980|Socket returns unknown error.
```

I'm using python 3.8.6. This is the package list:

```
bidict          0.21.2
certifi         2020.12.5
chardet         4.0.0
configparser    5.0.2
fxcmpy          1.2.9
idna            2.10
numpy           1.20.3
pandas          1.2.4
pip             21.1.1
PySocks         1.7.1
python-dateutil 2.8.1
python-engineio 4.2.0
python-socketio 5.3.0
pytz            2021.1
requests        2.25.1
setuptools      56.2.0
six             1.16.0
urllib3         1.26.4
```

Before I could connect without the wrapper, but a few hours ago I got this error: 

`socketio.exceptions.ConnectionError: Unexpected status code 403 in server response`

**Comment by FXCM-ValentinMandev** [comment]
Hi,

Please downgrade your python-engineio and python-socketio versions:
pip install python-engineio==3.9
pip install python-socketio==4.4

**Comment by bisaga-felix** [comment]
The problem persists.
It didn't happen before. The 403 error started to appear several hours ago, but it worked before

**Comment by FXCM-ValentinMandev** [comment]
Please share your username and token at api@fxcm.com

**Comment by fernandocanizo** [comment]
I'm having the exact same problem. This is a minimal setup to reproduce the bug:

```Dockerfile
FROM python:3

WORKDIR /trading

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

#COPY . .

CMD bash
```

Where `requirements.txt` file contains:
```txt
python-socketio==4.4.0
python-engineio==3.9.0
fxcmpy==1.2.6
bpython
```

And the connection attempted is the same done by @bisaga-felix .

I've been talking to support via `api@fxcm.com` and I've tried several configurations and libraries combinations to no avail. Tried default updated versions (python-socketio 5.1.0, python-engineio 4.1.0,  and fxcmpy 1.2.9), also, as suggested by support, with python-socketio 4.6.1, but that is not installable as it conflicts with python-engineio 3.9.0. So finally I tried socketio 4.4.0, engineio 3.9.0 with fxcmpy 1.2.6 and 1.2.9, but it's impossible to connect.

Also tried to use the examples for Python and Nodejs on this repo, but both are broken.

Is there a chance you can post a minimal setup, ideally with a `Dockerfile` so there's no possibility to mess up, that works?

**Comment by FXCMAPI** [comment]
please check the mail from api@fxcm.com

**Comment by MalcolmJSimpson** [comment]
I had similar difficulties with fxcmpy==1.2.9 however downgrading to python-socketio==4.4.0 and python-engineio==3.9.0 eliminated the error message. However 10 minutes in and there is still no connection: hangs at,

`api = fxcmpy.fxcmpy(access_token = 'TOKEN', log_level = 'error')`

I have regenerated the token a number of times. Could this be an issue?

**Comment by FXCMAPI** [comment]
first you can make sure your token is valid by testing on our sample program 
restapi101.herokuapp.com/
then you can test our program in attached. 

import pandas as pd
import json
import requests
import socketio
import time
import sys
import engineio
print("Python version: " + sys.version)

socketIO = socketio.Client()
print("socket.io version: " + socketio.__version__)
print("python-engineio version: " + engineio.__version__)


TRADING_API_URL = 'https://api-demo.fxcm.com'
WEBSOCKET_PORT = 443
ACCESS_TOKEN = 'YOUR TOKEN'

def on_connect():
    print ('Websocket connected: ' + socketIO.eio.sid)
        
def on_close():
    print ('Websocket closed.')

def on_error(str):
    print ('Websocket error.' + str)


if __name__ == '__main__':
    socketIO.connect(TRADING_API_URL +":" +str(WEBSOCKET_PORT) +"/?access_token=" +ACCESS_TOKEN)
                            
    print (socketIO.eio.sid)
    bearer_access_token="Bearer "+ socketIO.eio.sid + ACCESS_TOKEN

    print (bearer_access_token)
    socketIO.on('disconnect', on_close)
    socketIO.on('connect', on_connect)
    socketIO.on('connect_error', on_error) 
    socketIO.disconnect()
