### ISSUE TITLE
Can not find FXCM Server.

### ISSUE THREAD

**Issue by RiekertCodes** [fxcm/RestAPI#144]
So i tried running this code
```import fxcmpy
import socketio
print(fxcmpy.__version__)
print(socketio.__version__)
TOKEN = ''
con = fxcmpy.fxcmpy(access_token='1be1bf78bcccb2e228b96a2023eeb680002f9aed', log_level='debug', server='real', log_file='mylog1.txt')```
 
```
But this is the error i get
```
ServerError                               Traceback (most recent call last)
<ipython-input-1-ab97da7724f5> in <module>
      4 print(socketio.__version__)
      5 TOKEN = ''
----> 6 con = fxcmpy.fxcmpy(access_token='1be1bf78bcccb2e228b96a2023eeb680002f9aed', log_level='debug', server='real', log_file='mylog1.txt')

~\anaconda3\lib\site-packages\fxcmpy\fxcmpy.py in __init__(self, access_token, config_file, log_file, log_level, server, proxy_url, proxy_port, proxy_type)
    214 
    215         if self.connection_status == 'pending' and count == 50:
--> 216             raise ServerError('Can not find FXCM Server.')
    217         elif self.connection_status == 'aborted':
    218             raise ServerError('Can not connect to FXCM Server.')

ServerError: Can not find FXCM Server.
```
My versions are fxcmpy == 1.2.9
python-engineio           3.13.2
python-socketio           4.6.0

**Comment by Sanji-moku** [comment]
Hello,

First, you should not share your access token.

I'm able to connect to FXCM server with the following versions :

fxcmpy version: 1.2.9
socketio version: 4.6.1
engineio version: 3.9.0

pip uninstall namepackage
pip install namepackage==x.x.x

**Comment by jaywalker68** [comment]
@Sanji-moku's solution above worked for me on Linux. Anyone know which versions of socketio and engineio fxcmpy works with on Windows? I'm running fxcmpy version 1.2.9. Thanks

**Comment by FXCMAPI** [comment]
We did release on 1/24 that don’t support socketio-client package, 
please make sure uninstall socketio-client package
you can check this by running pip freeze

Please make sure you have latest fxcmpy 1.2.6 and python-socketio 4.4.0
pip install python-socketio
pip install –U fxcmpy
python -m pip install python-engineio==3.9

**Comment by jaywalker68** [comment]
@FXCMAPI, I have done as you suggested, but still it fails to connect. Below is the traceback (most recent call last):
  File "C:\Users\jwbla\Desktop\main.py", line 25, in <module>
    fxcm_connection()
  File "C:\Users\jwbla\Desktop\main.py", line 19, in fxcm_connection
    con = fxcmpy.fxcmpy(access_token='REMOVED', log_level='error', server='demo', log_file='log.txt')
  File "C:\Users\jwbla\Desktop\venv\lib\site-packages\fxcmpy\fxcmpy.py", line 226, in __init__
    self.__collect_offers__()
  File "C:\Users\jwbla\Desktop\venv\lib\site-packages\fxcmpy\fxcmpy.py", line 2284, in __collect_offers__
    offers = self.get_offers('list')
  File "C:\Users\jwbla\Desktop\venv\lib\site-packages\fxcmpy\fxcmpy.py", line 412, in get_offers
    data = self.get_model(('Offer',))
  File "C:\Users\jwbla\Desktop\venv\lib\site-packages\fxcmpy\fxcmpy.py", line 344, in get_model
    data = self.__handle_request__(method='trading/get_model',
  File "C:\Users\jwbla\Desktop\venv\lib\site-packages\fxcmpy\fxcmpy.py", line 2436, in __handle_request__
    raise IOError('Connection aborted, failed to reconnect')
OSError: Connection aborted, failed to reconnect
