### ISSUE TITLE
Multiple Tokens Slow Connection. 

### ISSUE THREAD

**Issue by Marcus2810** [fxcm/RestAPI#145]
Hi I have a problem with multiple tokens being looped and the Rest API is so slow at connecting even tho I have 100 mega bytes internet speeds and my computer is fast enough to train neural networks in minutes, so how do I fix this.

**Comment by fxcm-dhalpert** [comment]
please email your username to api@fxcm.com

**Comment by FXCMAPI** [comment]
are you using fxcmpy? please send mail to api@fxcm.com if you still have issue.
