### ISSUE TITLE
cannot connect to api server. how can I fix this ?

### ISSUE THREAD

**Issue by wysifu** [fxcm/RestAPI#148]
ServerError                               Traceback (most recent call last)
<ipython-input-70-ab9fd9f94c52> in <module>
----> 1 con = fxcmpy.fxcmpy(access_token = token, log_level='error',log_file=None)

~/opt/anaconda3/lib/python3.8/site-packages/fxcmpy/fxcmpy.py in __init__(self, access_token, config_file, log_file, log_level, server, proxy_url, proxy_port, proxy_type)
    216             raise ServerError('Can not find FXCM Server.')
    217         elif self.connection_status == 'aborted':
--> 218             raise ServerError('Can not connect to FXCM Server.')
    219 
    220         self.__collect_account_ids__()

ServerError: Can not connect to FXCM Server.

I have already imported fxcmpy and socketio. socketio version is 5.3.0. I tried to uninstall version 5.3.0 and install 4.6.0 but 5.3.0 is still being used in the jupyter notebook

**Comment by FifthHour** [comment]
what is the uri you are trying to connect to, and is your account demo or live? I have been playing with their api for a few days and have got over some issues similar to this, so i may be able to help.
please post your `pip freeze` output i will compare to mine and try to see any differences...

**Comment by fxcm-dhalpert** [comment]
Host: 
For Demo accounts: https://api-demo.fxcm.com
For Real accounts: https://api.fxcm.com
Port for demo or real: 443

For python:
Please check current versions of python-engineio and python-socketio:
python -c "import engineio; print(engineio.__version__)"
python -c "import socketio; print(socketio.__version__)"

We currently recommend the following:
python -m pip install python-socketio==4.4
python -m pip install python-engineio==3.9
