### ISSUE TITLE
Real-time close price for last candle

### ISSUE THREAD

**Issue by zxhaxdr** [fxcm/RestAPI#15]
I'm using python wrapper. Is there any way to get candles that the last candle has Open, Close, High, Low but the Close is in real-time? the get_candles method only gives the already closed candles which doesn't meet my requirement.
Example for m5 data:
first request:
Time          O     C      H      L
10:25         1.9   1.3   2.0    1.0
10:30         1.3   1.2   1.6    1.2
10:35         1.2   **_1.8_**   1.9    1.1

second request:
requested before 10:40 so the 10:35 candle isn't yet closed. All candles before 10:35 remain the same but the Close for 10:35 candle changes.
Time          O     C      H      L
10:25         1.9   1.3   2.0    1.0
10:30         1.3   1.2   1.6    1.2
10:35         1.2   **_1.4_**   1.9    1.1

Also, I can use High/Low from get_prices() or get_last_price() to make up the desired data but I don't think the High/Low from get_prices() is correct(maybe it's the High/low for D1 candle, but I need m5 candle).

**Comment by fxcm-dhalpert** [comment]
in REST API the historical bars don't include the current open bar, we have it in Forex Connect API, 
the Low and High refers to trading session Low and High, which starts daily at 17:00 EST

**Comment by zxhaxdr** [comment]
That's great. Thank you very much.
