### ISSUE TITLE
Can not connect to FXCM Server using proxy.

### ISSUE THREAD

**Issue by bitnick10** [fxcm/RestAPI#150]
```
import fxcmpy

con = fxcmpy.fxcmpy(access_token='cddb22db2*****bac6fdef963c91005649a42614', log_level='error', server='real', log_file='log.txt',proxy_url='192.168.1.111',proxy_port=11111,proxy_type='http')

print(con.get_instruments())
```

File "C:\Users\w2\AppData\Roaming\Python\Python39\site-packages\fxcmpy\fxcmpy.py", line 218, in __init__
    raise ServerError('Can not connect to FXCM Server.')
fxcmpy.fxcmpy.ServerError: Can not connect to FXCM Server

**Comment by FXCMAPI** [comment]
Hi,

Please try the following:
python -m pip install python-socketio==4.4
python -m pip install python-engineio==3.9
python -m pip uninstall socketio-client
python -m pip install websocket-client

**Comment by bitnick10** [comment]
@FXCMAPI not work

**Comment by FXCMAPI** [comment]
Hi,

Please send your username to api@fxcm.com

**Comment by bitnick10** [comment]
@FXCMAPI still not work.

**Comment by FXCMAPI** [comment]
Hi,

As I wrote to you in the email communication, please run **pip freeze** and send the output to api@fxcm.com

Thanks,
Valentin

**Comment by FXCMAPI** [comment]
We did release on 1/24 that don’t support socketio-client package, 
please make sure uninstall socketio-client package
you can check this by running pip freeze
pip freeze | findstr socketio-client
if you still have issue, please send mail to api@fxcm.com
