### ISSUE TITLE
cannot steaming the data with callback functions

### ISSUE THREAD

**Issue by kinzia** [fxcm/RestAPI#151]
I followed the example in 4.2. Callback functions
https://www.fxcm.com/fxcmpy/03_streaming_market_data.html

`def print_data(data, dataframe):
    print('%3d | %s | %s, %s, %s, %s, %s'
          % (len(dataframe), data['Symbol'],
             pd.to_datetime(int(data['Updated']), unit='ms'),
             data['Rates'][0], data['Rates'][1], data['Rates'][2],
             data['Rates'][3]))

con.subscribe_market_data('XAU/USD', (print_data,))`

nothing printed in my jupyter notebook. However, when I run 
`con.subscribe_market_data('XAU/USD', (print_data,))` again. few row is printed like the example but it is not keep printing.

**Comment by FXCMAPI** [comment]
Hi,

Looks like 'con.subscribe_market_data('XAU/USD', (print_data,))' needs to be run run in separate cell after defining print_data() function.

It keeps printing updates for me. Please set log_level to 'debug' and share log file to api@fxcm.com

Best Regards,
Valentin

**Comment by kinzia** [comment]
Hi Valentin

already run in separate cell after defining print_data() function

Just sent a email to you

Thanks for your fast response
Kevin

**Comment by kinzia** [comment]
already run in separate cell, you can check my code in github and showed in
[6]
only one row printed after call con.subscribe_market_data('XAU/USD', (
print_data,))again

https://github.com/kinzia/FXCM/blob/main/FXCM.ipynb

Thanks

FXCM ***@***.***> 於 2021年7月7日 週三 下午4:42寫道：

**Comment by FXCMAPI** [comment]
Hi,

That's really strange, I used your notebook for a test and all is updating okay for me:
https://github.com/FXCM-ValentinMandev/subscribe_market_data/blob/main/FXCM.ipynb

Also the log that you sent seems completely fine.
Could it be a network issue on your side?

Best Regards,
Valentin

**Comment by kinzia** [comment]
Hi Valentin

I tried it on mac and pc with wifi and my mobile shared wifi. They have the
same result.
I think colab notebook is running in google server and should not have
network issues.

Do you have any ideas what makes it wrong?

Thanks,
Kevin

FXCM ***@***.***> 於 2021年7月7日 週三 下午6:47寫道：

**Comment by FXCMAPI** [comment]
Hi Kevin,

We received other reports in the past that our REST API currently doesn't work well with Google Colab.
All tests that I did were run locally.

Best Regards,
Valentin

**Comment by kinzia** [comment]
my local machine python version is  3.8.5
which version of python is your testing machine?

**Comment by FXCMAPI** [comment]
I'm using 3.6.8, but I've also tested with python 3.8.5 and 3.9.5 - they should also work okay.

**Comment by kinzia** [comment]
print _data callback function is work now after switched from jupyter notebook to jupyterLab.
