### ISSUE TITLE
Server seems to connect but drop connection

### ISSUE THREAD

**Issue by clearoak** [fxcm/RestAPI#152]
[fxcm.log](https://github.com/fxcm/RestAPI/files/6778738/fxcm.log)
Trying to connect for first time.  I took note of an issue here and in my venv, I replaced socketio and engineio with the versions in the requirements file.  I generated a new token for this attempt. 
On the command line, I got nothing for about 100 seconds, and then:

con=fxcmpy.fxcmpy(config_file='fxcm.cfg')
(waited for about 100 seconds and then we get . . . )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/daddy/sync/computer/python/testfxcm/testshit/lib/python3.6/site-packages/fxcmpy/fxcmpy.py", line 226, in __init__
    self.__collect_offers__()
  File "/home/daddy/sync/computer/python/testfxcm/testshit/lib/python3.6/site-packages/fxcmpy/fxcmpy.py", line 2284, in __collect_offers__
    offers = self.get_offers('list')
  File "/home/daddy/sync/computer/python/testfxcm/testshit/lib/python3.6/site-packages/fxcmpy/fxcmpy.py", line 412, in get_offers
    data = self.get_model(('Offer',))
  File "/home/daddy/sync/computer/python/testfxcm/testshit/lib/python3.6/site-packages/fxcmpy/fxcmpy.py", line 345, in get_model
    params={'models': list(models)})
  File "/home/daddy/sync/computer/python/testfxcm/testshit/lib/python3.6/site-packages/fxcmpy/fxcmpy.py", line 2436, in __handle_request__
    raise IOError('Connection aborted, failed to reconnect')
OSError: Connection aborted, failed to reconnect

And the log file seems to show connection established and dropped, then a brick wall. 

Any help?  I'm out of ideas. 

With thanks. 
This was python 3.6.9 on linux MATE, 32-bit.

**Comment by FXCMAPI** [comment]
Hi,

Please check if you have the following packages:
- socketio-client (remove it if you have it – python –m pip uninstall socketio-client)
- websocket-client (install it if you don't have it – python –m pip install websocket-client)


Best Regards,
Valentin

**Comment by clearoak** [comment]
Hi Valentin.  Thanks for the fast reply, which I missed for quite a long time! 

[fxcm.log](https://github.com/fxcm/RestAPI/files/6779066/fxcm.log)
Now it doesn't return!
I didn't have either package you mentioned, so I installed the second one. 
Now I have this:

backcall         0.2.0
bidict           0.21.2
certifi          2021.5.30
chardet          4.0.0
configparser     5.0.2
decorator        5.0.9
fxcmpy           1.2.9
idna             2.10
ipython          7.16.1
ipython-genutils 0.2.0
jedi             0.18.0
numpy            1.19.5
pandas           1.1.5
parso            0.8.2
pexpect          4.8.0
pickleshare      0.7.5
pip              21.1.3
pkg-resources    0.0.0
prompt-toolkit   3.0.19
ptyprocess       0.7.0
Pygments         2.9.0
PySocks          1.7.1
python-dateutil  2.8.1
python-engineio  3.9.0
python-socketio  4.4.0
pytz             2021.1
requests         2.25.1
setuptools       39.0.1
six              1.16.0
traitlets        4.3.3
urllib3          1.26.6
wcwidth          0.2.5
websocket-client 1.1.0

The log file seems to show stuff going on for about 28 seconds.  After that, I see from the size on the disk that nothing more was being added to it.  I waited about five minutes, then decided it would never return from the con=fxcmpy.fxcmpy statement, so I had to "kill -9" the python3 process.  You can see when I did that in the log file. 

With thanks.

**Comment by FXCM-ValentinMandev** [comment]
Hi,

Please try connecting now.

Best Regards,
Valentin

**Comment by clearoak** [comment]
Hi Valentin, 

Success, connection made.   Seems to open and close OK. 
Whatever you did your end, thank you very much.
