### ISSUE TITLE
Multiple symbols?

### ISSUE THREAD

**Issue by matt22176** [fxcm/RestAPI#153]
Hello. Code works great, I was wondering if this could be adapted to work on various symbols / timeframes simultaneously?

**Comment by FXCMAPI** [comment]
Hi
I don't understand your questions. 
please provide sample or screenshot with explanation.

**Comment by matt22176** [comment]
Hello. The code in question truns a strategy on a specified symbol/ticker in a specified timeframe. Specifically in the code this is for EURUSD symbol on the timeframe of m1 (1 minute). My question is simply if the code could be adapted to simultaneously run the strategy on more than one symbol or timeframe. Since the api only allows one connection per token it would be useful to manage a multi symbol strategy from the code.

**Comment by FXCMAPI** [comment]
our rest API use socket and it is stateful API. you can subscribe multiple currencies but the price update will pushed to your end in one session.
