### ISSUE TITLE
Question: Historical tick data on indexes?

### ISSUE THREAD

**Issue by clearoak** [fxcm/RestAPI#154]
I note that one can obtain some historical tick data on twenty-four currency pairs.   But get_available_symbols lists no index symbol.  I wonder if this is an oversight.   I cannot see any reason why index tick data could not be provided, especially for the more important markets such as London, New York, Nasdaq, EU50, France, India, Hang Seng, Germany etc.   So, would you mind providing ticks for those symbols too?  

Edit: I see I might have looked at old info.  I can't find get_available_symbols in the API documentation, although it works.  And the tick_data_reader method doesn't work.  So is this (historical ticks) a capability which has been removed?

**Comment by fxcm-dhalpert** [comment]
You can download historical tick data for all symbols with Forex Connect API or with Tick Data Downloader program.
FC API main page: https://github.com/fxcm/ForexConnectAPI
https://www.fxcmapps.com/apps/tick-data-downloader/
