### ISSUE TITLE
ServerError: Can not connect to FXCM Server.

### ISSUE THREAD

**Issue by bigsay** [fxcm/RestAPI#157]
import fxcmpy

TOKEN = 'c62ee-------b3dc58abf0'

con = fxcmpy.fxcmpy(access_token=TOKEN, log_level='error', server='demo', log_file='log.txt')

---------------------------------------------------------------------------
ServerError                               Traceback (most recent call last)
<ipython-input-20-eb90ca958db7> in <module>
----> 1 con = fxcmpy.fxcmpy(access_token=TOKEN, log_level='error', server='demo', log_file='log.txt')

~\anaconda3\lib\site-packages\fxcmpy\fxcmpy.py in __init__(self, access_token, config_file, log_file, log_level, server, proxy_url, proxy_port, proxy_type)
    216             raise ServerError('Can not find FXCM Server.')
    217         elif self.connection_status == 'aborted':
--> 218             raise ServerError('Can not connect to FXCM Server.')
    219 
    220         self.__collect_account_ids__()

ServerError: Can not connect to FXCM Server.

fxcmpy.__version__
'1.2.9'
print(socketio.__version__)
4.4.0
print(engineio.__version__)
3.9.0

Someone, please tell me

**Comment by FXCMAPI** [comment]
We did release on 1/24 that don’t support socketio-client package, 
please make sure uninstall socketio-client package
you can check this by running pip freeze
pip freeze | findstr socketio-client

**Comment by bigsay** [comment]
Sorry to trouble you
Please tell me the uninstall code

**Comment by bigsay** [comment]
pip freeze | findstr socketio-client


Doesn't seem to be installed

**Comment by FXCMAPI** [comment]
pip uninstall  socketio-client

**Comment by bigsay** [comment]
Skipping socketio-client as it is not installed.

 Traceback (most recent call last)
<ipython-input-30-eb90ca958db7> in <module>
----> 1 con = fxcmpy.fxcmpy(access_token=TOKEN, log_level='error', server='demo', log_file='log.txt')

~\anaconda3\lib\site-packages\fxcmpy\fxcmpy.py in __init__(self, access_token, config_file, log_file, log_level, server, proxy_url, proxy_port, proxy_type)
    216             raise ServerError('Can not find FXCM Server.')
    217         elif self.connection_status == 'aborted':
--> 218             raise ServerError('Can not connect to FXCM Server.')
    219 
    220         self.__collect_account_ids__()

ServerError: Can not connect to FXCM Server.

not work.

**Comment by FXCM-ValentinMandev** [comment]
Hi,

Please send you API token to api@fxcm.com so we could investigate further.

**Comment by bigsay** [comment]
I sent an email

Thank you,
