### ISSUE TITLE
Fetching candle data not working

### ISSUE THREAD

**Issue by oscardavidrm** [fxcm/RestAPI#158]
Demo token `788e9fe445b468bc80386d6dcb2ea837a7de0baa`

Using:
- fxcmpy==1.2.9
- python-socketio==4.6.0
- python-engineio==3.13.2

**log.txt**
```
|ERROR|2021-07-24 12:39:08,199|FXCM Server reports an unknown error: {'executed': False, 'error': ''}.
|ERROR|2021-07-24 12:39:08,199|Can not parse server answer to json object: {"response":{"executed":false,"error":""},"instrument_id":"1","period_id":"m15","candles":[]}.
```

**code**
```
import fxcmpy
import socketio
import engineio

print(fxcmpy.__version__) # 1.2.9
print(socketio.__version__) # 4.6.0
print(engineio.__version__) # 3.13.2

con = fxcmpy.fxcmpy(
  access_token='788e9fe445b468bc80386d6dcb2ea837a7de0baa', 
  log_level='error', 
  server='demo', 
  log_file='log.txt'
)

print(con.get_candles(instrument='EUR/USD', period='m5', number=10))
# Empty DataFrame
# Columns: [bidopen, bidclose, bidhigh, bidlow, askopen, askclose, askhigh, asklow, tickqty]
# Index: []
```

**Comment by 69ways** [comment]
Having the same problem with

fxcmpy.__version: 1.2.9
socketio.__version: 4.6.1
engineio.__version: 3.14.2

Many thanks

**Comment by oscardavidrm** [comment]
It's working now!

Apparently `.get_candles(...)` was down. For future reference, this could be seen by login into the [demo account](https://tradingstation.fxcm.com/). If data is not loading, or something is off, this is a starting cue to debug.

Although @FXCMAPI, it would be nice to have a public [Grafana dashboard](https://grafana.com/grafana/dashboards) or a health check endpoint to verify the server's state.
