### ISSUE TITLE
H2 candle incorrect.

### ISSUE THREAD

**Issue by zxhaxdr** [fxcm/RestAPI#16]
The H2 candles completely don't make sense (not just inaccurate). Also if I specify get_candles(number=10), it will just return 5 candles, if get_candles(number=5), it returns 3 candles.

PythonWrapper used
Thanks

**Comment by FXCMAPI** [comment]
this was an issue H2 candles and above. we are working on it
for now please listening the real time price and build your own candles. 
also H1 is correct.
