### ISSUE TITLE
Return Type for Candles

### ISSUE THREAD

**Issue by ViewableGravy** [fxcm/RestAPI#164]
When hitting the /candles/1/{period_id} endpoint, the returned format is a 2 dimensional array.

I Feel that it would make more sense to return an array of objects for obvious reasons.

Is this something that just hasn't been changed due to historical reasons?

```
[
  {
    timestamp, //(epoch), 
    BidOpen, 
    BidClose,
    BidHigh, 
    BidLow, 
    AskOpen, 
    AskClose, 
    AskHigh, 
    AskLow,
    TickQty
  }
] 
```

**Comment by FXCMAPI** [comment]
we are reviewing this. please contact us via email at api@fxcm.com thanks you.
