### ISSUE TITLE
Executed=false when requesting historical bars on the most current weekend.

### ISSUE THREAD

**Issue by ViewableGravy** [fxcm/RestAPI#166]
When making a request for historical candles on the weekend, (Demo account) I don't receive an error, nor is there any candles. The query is simply not executed with no information on what I am doing wrong. 

This is likely because there are no bars to retrieve but an error message or similar would likely make sense as at the moment I just have to write code to assume that if there is no error this is the issue.

Regardless, can this either be resolved or some standard be set within the documentation to indicate what isn't allowed in terms of requests.

If I am wrong and this is documented somewhere I would love to be informed (The response from FXCM should still at least say why"

**Comment by FXCMAPI** [comment]
Dear client

our server was closed in weekend for maintenance. 
For forex, trading opens on Sundays between 5:00 PM ET and 5:15 PM ET and closes on Fridays around 4:55 PM ET. 
Hope this help

**Comment by ViewableGravy** [comment]
I certainly understand the times that trading is open but this doesn't explain why the response back from the API is simply "executed=false" with no error message. This indicates nothing to the consumer about why the query failed. Please consider updating the response on this endpoint to provide a more clear error message regarding the circumstances of why the query was not executed.

**Comment by FXCMAPI** [comment]
request data outside of trading hours should not be treated as an "Error", but you are right, meaning message will help client in this case. We will raise this to our developers thanks
Lei

**Comment by ViewableGravy** [comment]
Thank you and glad to help contribute, The service offered by FXCM is fantastic for people delving into programmatic trading and it's great to have communication on things like this. Thanks

**Comment by FXCMAPI** [comment]
thank you for your advice, this has been added to our enhancement list.
