### ISSUE TITLE
520 Error

### ISSUE THREAD

**Issue by ViewableGravy** [fxcm/RestAPI#168]
I have been using the demo API for FXCM now for several months and something that has intermittently come up is a 520 error when making requests through the historical endpoint.

With the current implementation I am hitting this endpoint on average once a minute for 3 bars and since I have recently added further logging to look into why/what error I was receiving I am confident this is an issue with the server.

I have attached below a list of times that I received a 520 error in the last 3 hours below:
```
The following update occurred during the PriceUpdate event at Fri Oct 08 2021 01:21:01 GMT+1100 (Australian Eastern Daylight Time): Error: Error: statusCode=520
The following update occurred during the PriceUpdate event at Fri Oct 08 2021 01:29:00 GMT+1100 (Australian Eastern Daylight Time): Error: Error: statusCode=520
The following update occurred during the PriceUpdate event at Fri Oct 08 2021 01:43:01 GMT+1100 (Australian Eastern Daylight Time): Error: Error: statusCode=520
The following update occurred during the PriceUpdate event at Fri Oct 08 2021 01:45:02 GMT+1100 (Australian Eastern Daylight Time): Error: Error: statusCode=520
The following update occurred during the PriceUpdate event at Fri Oct 08 2021 02:32:01 GMT+1100 (Australian Eastern Daylight Time): Error: Error: statusCode=520
```

Hopefully there are some correlating logs in any server output to help track down this issue. Ultimately it doesn't affect me however writing retry mechanisms is awfully tedious as simply making the request again works correctly

**Comment by FXCMAPI** [comment]
We are looking into it.

**Comment by FXCMAPI** [comment]
Please raise to api@fxcm.com if you still see this issue. thanks you
