### ISSUE TITLE
FXCM API error Python

### ISSUE THREAD

**Issue by vakol24** [fxcm/RestAPI#171]
Hello, 

I am trying to connect to the FXCM server using the following code in Python:

import fxcmpy
import socketio
token = "d05f6a63b7511a6caf9e9507e45e5cc869001e38"
conn=fxcmpy.fxcmpy(access_token = token, log_level='error')

However, I get the following error message:

erverError                               Traceback (most recent call last)
<ipython-input-14-fe01673ed5b1> in <module>
----> 1 conn=fxcmpy.fxcmpy(access_token = token, log_level='error')

~\Anaconda3\lib\site-packages\fxcmpy\fxcmpy.py in __init__(self, access_token, config_file, log_file, log_level, server, proxy_url, proxy_port, proxy_type)
    216         elif self.connection_status == 'aborted':
    217             raise ServerError('Can not connect to FXCM Server.')
--> 218 
    219         self.__collect_account_ids__()
    220         self.default_account = self.account_ids[0]

ServerError: Can not connect to FXCM Server.

Any ideas on how to get around the problem would be greatly appreciated.

**Comment by FXCMAPI** [comment]
Hi,

Please check current versions of python-engineio and python-socketio:
import engineio
import socketio
print(engineio.__version__)
print(socketio.__version__)


We currently recommend the following:
python -m pip install python-engineio==3.9
python -m pip install python-socketio==4.4

Plus install websocket-client if you don’t have it:
python -m pip install websocket-client
