### ISSUE TITLE
packet queue is empty, aborting

### ISSUE THREAD

**Issue by kfuangsung** [fxcm/RestAPI#172]
my python script always running fine for many hours (3 to 5hours - sometimes longer) until I get this error
`packet queue is empty, aborting`
(that's all the message, nothing else)
I don't know what it means.
Unlike other error, the script just stopped running but not being terminated.
Sometimes it stopped for few minutes or hours then it came back to normal (running fine again until next error).
Sometimes it seems to be stopped forever and I had to manually kill the script.
If I immediately execute the script after that, same thing would happen. (running fine for hours until getting this error)
Finally, I don't have any problem with connection or other errors, just this one. 
Thanks in advance.

**Comment by FXCMAPI** [comment]
this sounds like your session was lost, can you provide sample code for us to replicate? 
I will close this thread but please mail code to api@fxcm.com
