### ISSUE TITLE
Cannot connect to FC

### ISSUE THREAD

**Issue by jinyan1999** [fxcm/RestAPI#173]
When I first run this commands:
con = fxcmpy.fxcmpy(access_token = "1fe37f6f53e05c35e1e82724775fb0fa65e52a3d", log_level = 'error', server='demo')

It says I cannot connect to FXCM as the following shows:
<img width="757" alt="cannot connect" src="https://user-images.githubusercontent.com/89759486/147131124-ae53891e-5f7b-4276-9c8d-0f925485e1e5.png">

Then, I tried to install python-engineio==3.9, python-socketio==4.4, and websocket-client
however when I run my code, the console freezes there and I cannot proceed with my other codes as the following shows. Do you know how I can solve the problem?
<img width="726" alt="freezes" src="https://user-images.githubusercontent.com/89759486/147131255-65763b9e-764d-48c8-8a92-95e96df2d695.png">

**Comment by FXCMAPI** [comment]
Hi,

If you are connecting from China, please try with server='demo2'

**Comment by jinyan1999** [comment]
Hi, sorry to interrupt again!

I was able to connect to FXCM server this morning but was unable to do so this afternoon at around 4:30pm. This is how it shows:

<img width="427" alt="Screen Shot 2021-12-27 at 4 51 19 PM" src="https://user-images.githubusercontent.com/89759486/147509453-4c617f0f-02e7-4725-82d4-b3376d82057f.png">
 
I am wondering what the problem is and how i can solve it, Thank you!!!

**Comment by FXCMAPI** [comment]
if you successfully connected before, suggest you don't have issue on code. 
it may due to network or token was not valid. 
please try again and let us know if you still have this issue.

**Comment by jinyan1999** [comment]
Thank you for your reply! I tried to close and open Sypder multiple times and it finally worked! It might be the network that s not not very stable. Thank you again
