### ISSUE TITLE
Connection aborted

### ISSUE THREAD

**Issue by jinyan1999** [fxcm/RestAPI#174]
Hi,

What is the problem below?

<img width="390" alt="Screen Shot 2021-12-27 at 11 44 04 PM" src="https://user-images.githubusercontent.com/89759486/147529023-3dea9f56-ee8a-4e29-8eec-2e8653bf5ded.png">

**Comment by FXCMAPI** [comment]
Do you see this issue again? 
if so please provide sample code on how to replicate
