### ISSUE TITLE
What server to use to connect to real account in China?

### ISSUE THREAD

**Issue by jinyan1999** [fxcm/RestAPI#175]
<img width="802" alt="Screen Shot 2022-01-02 at 10 09 29 PM" src="https://user-images.githubusercontent.com/89759486/147897277-6a2180e1-1b30-4e57-8e2b-78e373579797.png">

I run the above code for multiple times and it does not proceed for some reasons. If I am connecting from China, what server do I need use? Thank you!

**Comment by fxcm-dhalpert** [comment]
Please create a new token, don't post it on Github nor email it.
please change the server to 'real2', if still not working email us the error message to api@fxcm.com
