### ISSUE TITLE
fxcmpy.fxcmpy.ServerError: Can not find FXCM Server

### ISSUE THREAD

**Issue by nf78** [fxcm/RestAPI#176]
Hi,

I'm  trying to connect with the latest fxcmpy==1.2.9 it does not connect me to the server. 

I even tried with suggestions on similar previous issues:
Name: python-engineio
Version: 3.9.0

Name: python-socketio
Version: 4.4.0

Name: fxcmpy
Version: 1.2.6

Traceback (most recent call last):
  File "LSTM-833ticks-48lb-28nr.py", line 48, in <module>
    con = fxcmpy.fxcmpy(config_file = 'fxcm_ubuntu64.cfg')
  File "/anaconda/envs/fxcm/lib/python3.8/site-packages/fxcmpy/fxcmpy.py", line 216, in __init__
    raise ServerError('Can not find FXCM Server.')
fxcmpy.fxcmpy.ServerError: Can not find FXCM Server.

I'd appreciate your help.

**Comment by FXCMAPI** [comment]
Hi,

Please try connecting without using .cfg file.

**Comment by FXCMAPI** [comment]
Hi,

The older versions that you previously had should work better, so please downgrade back to them.
Please set log_level='debug' and share the log to api@fxcm.com

**Comment by nf78** [comment]
Ok,

So thanks a lot for your help, I've realised on my previous error log file that there was an "unauthorised token" error, even though it was recently created (less than a month ago). So I went ahead and created a new one and it now works with the previous modules versions I had:

fxcmpy==1.2.6
python-engineio==3.9.0
python-socketio==4.4.0

Just before downgrading fxcmpy to 1.2.6, I attempted to use 1.2.9, 1.2.8 and 1.2.7 but all of those were hanging for a long time. I tried connection types using the config file and without, both yielded same results.

Now just a question, why the recommended versions are related to a fxcmpy version (1.2.6) from 2 years ago? What happened to the improvements made on the following versions?

I think this should be addressed asap please.

Thanks for your help!

**Comment by FXCMAPI** [comment]
Hi,

Changes to fxcmpy since 1.2.6 were related to documentation/description. There is no difference in functionality between fxcmpy 1.2.6 and 1.2.9.
We are aware that after some time of inactivity fxcmpy hangs the first few times when you try to connect, but then starts working normally. So if you try 1.2.9 now, it should work okay too, just like 1.2.9

**Comment by nf78** [comment]
Hi,

In fact after upgrading from 1.2.6 to 1.2.9 it actually worked well.

But I wanted to do a deeper analysis of the situation because I understand that if the only difference from the oldest to the newest is just documentation, then the underlying dependencies should not be affected, hence why from my fresh install with 1.2.9 had problems from the beginning when I first tried a month ago with a new token. 

The result of the analysis is as below:

BEFORE UPGRADING (fxcmpy==1.2.6)
`Requirement already satisfied: socketIO-client in /anaconda/envs/fxcm/lib/python3.8/site-packages (from fxcmpy==1.2.6) (0.7.2)`
`Requirement already satisfied: websocket-client in /anaconda/envs/fxcm/lib/python3.8/site-packages (from socketIO-client->fxcmpy==1.2.6) (1.2.1)`

AFTER UPGRADING (fxcmpy==1.2.9)
`Requirement already satisfied: python-socketio in /anaconda/envs/fxcm/lib/python3.8/site-packages (from fxcmpy==1.2.9) (4.4.0)`
`Requirement already satisfied: python-engineio in /anaconda/envs/fxcm/lib/python3.8/site-packages (from fxcmpy==1.2.9) (3.9.0)`

FRESH INSTALL OF fxcmpy==1.2.6
`Successfully installed PySocks-1.7.1 charset-normalizer-2.0.10 configparser-5.2.0 fxcmpy-1.2.6 idna-3.3 numpy-1.22.0 pandas-1.3.5 
python-dateutil-2.8.2 pytz-2021.3 requests-2.27.1 six-1.16.0 socketIO-client-0.7.2 urllib3-1.26.7 websocket-client-1.2.3`

FRESH INSTALL OF fxcmpy==1.2.9
`Successfully installed PySocks-1.7.1 bidict-0.21.4 charset-normalizer-2.0.10 configparser-5.2.0 fxcmpy-1.2.9 idna-3.3 numpy-1.22.0 
pandas-1.3.5 python-dateutil-2.8.2 python-engineio-4.3.0 python-socketio-5.5.0 pytz-2021.3 requests-2.27.1 six-1.16.0 urllib3-1.26.7`


CONCLUSION:
A fresh install of fxcmpy==1.2.9 requires different versions of those recommended for python-engineio and python-socketio
A fresh install of fxcmpy==1.2.6 doesn't even installs those dependencies.

So there must be differences on the setup used when "pip installing" both versions that are affecting functionality.

Thanks for your time.

**Comment by FXCMAPI** [comment]
Hi,

Both fxcmpy 1.2.6 and 1.2.9 work best with python-engineio 3.9 and python-socketio 4.4. 

Those exact versions were not specified in 1.2.6 requirements and on fresh install of fxcmpy 1.2.6 you would always get latest versions of python-engineio and python-socketio installed (currently 4.3.0 and 5.5.0).

This was changed in fxcmpy 1.2.9 and the versions were specified in the requirements. So on fresh install you would get versions 3.9 and 4.4 installed. However if you have more recent versions, you would need to downgrade them manually.

**Comment by nf78** [comment]
That's exactly what I did, a fresh install on a brand new conda environment (no previous versions of any other package before), and when I pip installed the 1.2.9 it still installed python-engineio (4.3.0) and python-socketio (5.5.0). 

But if it works "better" with python-engineio (3.9.0) and python-socketio (4.4.0), then I'm sure this should be a hard requirement instead of just accepting whatever the latest versions are, to avoid people having to manually downgrade after a good degree of investigation and research.

**Comment by pelluchon** [comment]
Hi, 

I am running into the same issue "Can not connect to FXCM Server." I am doing a loop on different ticks. Randomly after some ticks, I have the error: "Can not connect to FXCM Server."

I am using those:
fxcmpy==1.2.10
python-engineio==3.9.0
python-socketio==4.4.0

I have re-generated also my token but it did not solve the issue.

My code is: 
for l in range(0,len(FX)):
    try:
        con = fxcmpy.fxcmpy(access_token = TOKEN, log_level = 'error', server= server_name, log_file='log.txt')
        open_pos = con.get_open_positions()
         ---- > my function
        con.close()
    except Exception as e:
        con.close()
        time.sleep(120)
        pass

Has anyone got a solution for this issue or a workaround ?

Cheers

**Comment by suhanovs** [comment]
> Hi,
> 
> I'm trying to connect with the latest fxcmpy==1.2.9 it does not connect me to the server.
> 
> I even tried with suggestions on similar previous issues: Name: python-engineio Version: 3.9.0
> 
> Name: python-socketio Version: 4.4.0
> 
> Name: fxcmpy Version: 1.2.6
> 
> Traceback (most recent call last): File "LSTM-833ticks-48lb-28nr.py", line 48, in con = fxcmpy.fxcmpy(config_file = 'fxcm_ubuntu64.cfg') File "/anaconda/envs/fxcm/lib/python3.8/site-packages/fxcmpy/fxcmpy.py", line 216, in **init** raise ServerError('Can not find FXCM Server.') fxcmpy.fxcmpy.ServerError: Can not find FXCM Server.
> 
> I'd appreciate your help.

Found this in one of the other threads that could help.  You need to unload all fxcmpy modules from memory and reinitialize as follows: 

`            a_del=[]
            for module in sys.modules.keys():
                if 'fxcm' in module:
                    a_del.append(module)
            for module in a_del:
                del sys.modules[module]
`

Running this in your except whenever you get Cannot connect to server seems to be fixing the issue for me.

**Comment by fxcm-dhalpert** [comment]
please update the fxcmpy with latest version 1.3.2
pip install fxcmpy -U

**Comment by FXCMAPI** [comment]
please use python 3.7

**Comment by pelluchon** [comment]
I have moved to Python 3.7.10. It improved for 2 days but got that issue now :
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/app/.heroku/python/lib/python3.7/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/app/.heroku/python/lib/python3.7/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/app/.heroku/python/lib/python3.7/http/client.py", line 1373, in getresponse
    response.begin()
  File "/app/.heroku/python/lib/python3.7/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/app/.heroku/python/lib/python3.7/http/client.py", line 280, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/app/.heroku/python/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/app/.heroku/python/lib/python3.7/ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "/app/.heroku/python/lib/python3.7/ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

**Comment by pelluchon** [comment]
By the way since, I have moved away from Python 3.6 and I have installed the latest release of fxcmpy, I am not able to set the stop/loss and take/profit using this code:
con.change_trade_stop_limit(trade_id = int(trade), is_stop = True,rate = sl, is_in_pips = False)

Before it is working, any clue on what could be the issue ? I have no error raised, it is just not doing it.

**Comment by FXCMAPI** [comment]
Hi,

The problem with change_trade_stop_limit is from fxcmpy wrapper. This will be fixed in an updated version that will be released in next few days.

**Comment by pelluchon** [comment]
Cool, many thanks for fix

For the first issue mentionned above, I still got that issue once a day:

Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/app/.heroku/python/lib/python3.7/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/app/.heroku/python/lib/python3.7/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/app/.heroku/python/lib/python3.7/http/client.py", line 1373, in getresponse
    response.begin()
  File "/app/.heroku/python/lib/python3.7/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/app/.heroku/python/lib/python3.7/http/client.py", line 280, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/app/.heroku/python/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/app/.heroku/python/lib/python3.7/ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "/app/.heroku/python/lib/python3.7/ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

**Comment by pelluchon** [comment]
> Hi,
> 
> The problem with change_trade_stop_limit is from fxcmpy wrapper. This will be fixed in an updated version that will be released in next few days.

Thank you very much for this answer. When the new version will be released ?

**Comment by pelluchon** [comment]
> Cool, many thanks for fix
> 
> For the first issue mentionned above, I still got that issue once a day:
> 
> Traceback (most recent call last): File "/app/.heroku/python/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen chunked=chunked, File "/app/.heroku/python/lib/python3.7/site-packages/urllib3/connectionpool.py", line 449, in _make_request six.raise_from(e, None) File "", line 3, in raise_from File "/app/.heroku/python/lib/python3.7/site-packages/urllib3/connectionpool.py", line 444, in _make_request httplib_response = conn.getresponse() File "/app/.heroku/python/lib/python3.7/http/client.py", line 1373, in getresponse response.begin() File "/app/.heroku/python/lib/python3.7/http/client.py", line 319, in begin version, status, reason = self._read_status() File "/app/.heroku/python/lib/python3.7/http/client.py", line 280, in _read_status line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1") File "/app/.heroku/python/lib/python3.7/socket.py", line 589, in readinto return self._sock.recv_into(b) File "/app/.heroku/python/lib/python3.7/ssl.py", line 1071, in recv_into return self.read(nbytes, buffer) File "/app/.heroku/python/lib/python3.7/ssl.py", line 929, in read return self._sslobj.read(len, buffer) ConnectionResetError: [Errno 104] Connection reset by peer

Any thoughts on this issue, I am still getting it once a day ?

**Comment by pelluchon** [comment]
I have moved to the new version of fxcmpy but I still have the issue of "Connection reset by peer". I am using the following config:
fxcmpy~=1.3.3
python-socketio==5.0.4
python-engineio==4.3.1

The message I am receiving is the following:
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/app/.heroku/python/lib/python3.7/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/app/.heroku/python/lib/python3.7/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/app/.heroku/python/lib/python3.7/http/client.py", line 1373, in getresponse
    response.begin()
  File "/app/.heroku/python/lib/python3.7/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/app/.heroku/python/lib/python3.7/http/client.py", line 280, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/app/.heroku/python/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/app/.heroku/python/lib/python3.7/ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "/app/.heroku/python/lib/python3.7/ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

Does someone has an idea of how to fix it ?
