### ISSUE TITLE
Error message when python tries to initiate a rate

### ISSUE THREAD

**Issue by jinyan1999** [fxcm/RestAPI#177]
Hi,

isn't the foreign exchange market open 24 hours? Why when my python codes tried to initiate a trade, it showed the following error message.  Thank you

<img width="570" alt="Screen Shot 2022-01-07 at 6 50 42 PM" src="https://user-images.githubusercontent.com/89759486/148621339-9830f3de-5a27-44d5-9c83-900fb0ea067c.png">

**Comment by fxcm-dhalpert** [comment]
please see FXCM trading hours:
https://www.fxcm.com/uk/help/fx-trading-what-are-your-trading-hours/
