### ISSUE TITLE
Account is not in pool.

### ISSUE THREAD

**Issue by nguyenthang338** [fxcm/RestAPI#178]
send { "method":"POST", "resource":"/trading/open_trade", "params": {"account_id":"701647191", "symbol":"AUD/USD", "is_buy":true, "amount":100, "time_in_force":"FOK" } }
request # 7  sending
> request # 7  has been executed: {
  "response": {
    "executed": false,
    "error": "{\"type\":5,\"sessionId\":\"CFDDEMO01_D12E1B6222420C03E053E12B3C0A9846_01182022070802401933_\",\"requestId\":\"Request-557024\",\"text\":\" Account is not in pool. Skip request for acct 701647191\\n\",\"code\":20001,\"stack\":\"\"}"
  }
}
I install and setup token done. 
When i try use demo account , What mean api@fxcm.com

**Comment by fxcm-dhalpert** [comment]
the 701647191 is not account_id, please check the Account table for account ID

**Comment by nguyenthang338** [comment]
@fxcm-dhalpert  hi, i am try with account_id=1001722090 . This is number of Account table 
But result the same ...
send { "method":"POST", "resource":"/trading/open_trade", "params": {"account_id":"1001722090", "symbol":"EUR/USD", "is_buy":true, "amount":100, "time_in_force":"FOK" } }
request # 1  sending
> request # 1  has been executed: {
  "response": {
    "executed": false,
    "error": "{\"type\":5,\"sessionId\":\"CFDDEMO01_D12E1B6756D60C03E053E12B3C0A9846_01192022085724132299_\",\"requestId\":\"Request-951679\",\"text\":\" Account is not in pool. Skip request for acct 1001722090\\n\",\"code\":20001,\"stack\":\"\"}"
  }
}

**Comment by fxcm-dhalpert** [comment]
the 1001722090 is account number not account ID, try 1722090

**Comment by nguyenthang338** [comment]
@fxcm-dhalpert 
thanks for supports .i found  my account ID 
i suggest , make app cli from rest  api  fxcm like api binance https://www.npmjs.com/package/binance-api-node
try for fun :)))
