### ISSUE TITLE
connection error

### ISSUE THREAD

**Issue by jinyan1999** [fxcm/RestAPI#179]
why is this problem happening?

![15961643383203_ pic](https://user-images.githubusercontent.com/89759486/151573038-e4055fed-8cac-4f1e-b841-be61b648aaad.jpg)

**Comment by jinyan1999** [comment]
Thank you for your response! Usually make a request every 5 minute for 8
hours between 7am-3pm. Is that too frequent?

**Comment by jinyan1999** [comment]
What is the maximum frequency I can make requests?

**Comment by FXCMAPI** [comment]
the maximum frequency is 3 request per min. do you get this error often or just once? do  you have sample code for us to replicate. 
you can send to api@fxcm.com

**Comment by jinyan1999** [comment]
Not very often but occasionally. I am pretty sure that I did not make more
than 3 requests in a minute but still it sometimes can have this error. In
addition to this, it quite often failed to connect to FXCM in the middle of
the running process. It went smoothly in the first two to three hours but
always resulted in an error afterwards. I will send a screenshot to you
next time when I encounter it again.

Just emailed my sample code to the above email address and please let me
know if there are any issues. Thank you very much!

**Comment by FXCMAPI** [comment]
thank you for your input. 
Let me check our inbox
