### ISSUE TITLE
Demo account get_candles not working

### ISSUE THREAD

**Issue by jaikumaruk2017** [fxcm/RestAPI#180]
Demo account able to connect to FXCM but getting empty data frame back.

fxcmpy.__version__  = 1.2.10
print(socketio.__version__) = 4.4.0
|ERROR|2022-01-29 16:03:52,573|FXCM Server reports an unknown error: {'executed': False, 'error': ''}.
|ERROR|2022-01-29 16:03:52,574|Can not parse server answer to json object: {"response":{"executed":false,"error":""},"instrument_id":"3","period_id":"m15","candles":[]}.
Empty DataFrame
Columns: [bidopen, bidclose, bidhigh, bidlow, askopen, askclose, askhigh, asklow, tickqty]
Index: []

**Comment by FXCMAPI** [comment]
the error shows your session was not connect correctly.
Host: 
For Demo accounts: https://api-demo.fxcm.com
For Real accounts: https://api.fxcm.com
Port for demo or real: 443
 
For python:
Please check current versions of python-engineio and python-socketio:
python -c "import engineio; print(engineio.__version__)"
python -c "import socketio; print(socketio.__version__)"
 
We currently recommend the following:
python -m pip install python-socketio==4.4
python -m pip install python-engineio==3.9
python –m pip install websocket-client==1.1.0
