### ISSUE TITLE
The websocket is constantly disconnected

### ISSUE THREAD

**Issue by fatemeh26si** [fxcm/RestAPI#182]
Hi,
I added this file [(fxcm_rest_client_sample.py)](https://github.com/fxcm/RestAPI/blob/master/fxcm-api-rest-python3-example/fxcm_rest_client_sample.py) to my project. Everything works, but the problem is that a few seconds after the connection, the web socket is disconnected 
it slows down the process and it does not work for me
The same problem exists on the server
Please help to solve this problem

**Comment by FXCMAPI** [comment]
Hi,

Please try [fxcm_rest_api_token.py](https://github.com/fxcm/RestAPI/blob/master/fxcm-api-rest-python3-example/fxcm_rest_api_token.py) instead.
