### ISSUE TITLE
Cannot connect

### ISSUE THREAD

**Issue by jinyan1999** [fxcm/RestAPI#183]
When I try to connect, I encountered the following error message:
|ERROR|2022-02-22 09:41:47,894|Server reports an error: {'executed': False, 'error': ' \nORA-06512: at "CFD_U10D1.API", line 1177\nORA-06512: at line 1\n'}.
|ERROR|2022-02-22 09:41:47,895|URL: https://api-demo.fuhuisupport.com:443/trading/update_subscriptions
|ERROR|2022-02-22 09:41:47,896|Headers: {'User-Agent': 'request', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'Bearer kHBe5D4g4AGHgUB9AQH4abd8b450b7063a70a0d8c038270dc629d459b776', 'Content-Type': 'application/x-www-form-urlencoded', 'Content-Length': '26'}
|ERROR|2022-02-22 09:41:47,897|Params: {'symbol': 'ACA.fr', 'visible': 'true'}
|ERROR|2022-02-22 09:41:47,898|Bearer token: Bearer kHBe5D4g4AGHgUB9AQH4abd8b450b7063a70a0d8c038270dc629d459b776
|ERROR|2022-02-22 09:41:47,899|Connection status: established
|ERROR|2022-02-22 09:41:47,899|Socket session id: kHBe5D4g4AGHgUB9AQH4
|ERROR|2022-02-22 09:41:47,901|Can not parse server answer to json object: {"response":{"executed":false,"error":" \nORA-06512: at \"CFD_U10D1.API\", line 1177\nORA-06512: at line 1\n"}}.
|ERROR|2022-02-22 09:41:47,996|Server reports an error: {'executed': False, 'error': ' \nORA-06512: at "CFD_U10D1.API", line 1177\nORA-06512: at line 1\n'}.
|ERROR|2022-02-22 09:41:47,998|URL: https://api-demo.fuhuisupport.com:443/trading/update_subscriptions
|ERROR|2022-02-22 09:41:48,000|Headers: {'User-Agent': 'request', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'Bearer kHBe5D4g4AGHgUB9AQH4abd8b450b7063a70a0d8c038270dc629d459b776', 'Content-Type': 'application/x-www-form-urlencoded', 'Content-Length': '27'}
|ERROR|2022-02-22 09:41:48,000|Params: {'symbol': 'MVRS.us', 'visible': 'true'}
|ERROR|2022-02-22 09:41:48,002|Bearer token: Bearer kHBe5D4g4AGHgUB9AQH4abd8b450b7063a70a0d8c038270dc629d459b776
|ERROR|2022-02-22 09:41:48,003|Connection status: established
|ERROR|2022-02-22 09:41:48,004|Socket session id: kHBe5D4g4AGHgUB9AQH4
|ERROR|2022-02-22 09:41:48,005|Can not parse server answer to json object: {"response":{"executed":false,"error":" \nORA-06512: at \"CFD_U10D1.API\", line 1177\nORA-06512: at line 1\n"}}.

Do you know how I can resolve this?

**Comment by FXCMAPI** [comment]
Hi,

Please check current versions of python-engineio and python-socketio:
import engineio
import socketio
print(engineio.__version__)
print(socketio.__version__)


We currently recommend the following:
python -m pip install python-engineio==3.9
python -m pip install python-socketio==4.4

Plus install websocket-client if you don’t have it:
python -m pip install websocket-client

**Comment by jinyan1999** [comment]
Yes I installed it but it still returned the same error message

**Comment by FXCMAPI** [comment]
Hi,

Did you ever have this problem before?
Please send your username and the code that you are trying to run at api@fxcm.com

**Comment by jinyan1999** [comment]
Yes, I did.

**Comment by lnmn249** [comment]
Getting the same errors.   Although it does retrieve the candles. I shouldn't be receiving any errors

python-engineio 3.9
python-socketio 4.4
websocket-client is installed
fxcmpy.__version__ 1.2.10

```
from fxcmpy import fxcmpy
import fxcm_token
def fxcmData(tf): 
    con = fxcmpy(access_token=fxcm_token.token_dev,log_level='')
    records = con.get_candles('USDOLLAR',period=tf,number=262)
    records = records[["bidopen","bidhigh","bidlow","bidclose"]]
    
    records['pair'] = "USDOLLAR"
    records.reset_index(inplace=True)
    records = records.rename(columns={"bidopen":"open","bidhigh":"high","bidlow":"low","bidclose":"close","date":"time"})
    con.close()
    return records
rs = fxcmData("m5")
rs
```

```
WARNING|2022-02-25 09:52:15,185|Default account set to 1140454, to change use set_default_account().
|ERROR|2022-02-25 09:52:16,920|Server reports an error: {'executed': False, 'error': ' \nORA-06512: at "U100D2.API", line 1177\nORA-06512: at line 1\n'}.
|ERROR|2022-02-25 09:52:16,921|URL: [https://api-demo.fxcm.com:443/trading/update_subscriptions](https://api-demo.fxcm.com/trading/update_subscriptions)
|ERROR|2022-02-25 09:52:16,922|Headers: {'User-Agent': 'request', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'Bearer 1hmwp_fPsOgk8MzmBN455d5d5cf41c798620f0aa7195317d0723cc90b54a', 'Content-Type': 'application/x-www-form-urlencoded', 'Content-Length': '26'}
|ERROR|2022-02-25 09:52:16,923|Params: {'symbol': 'ACA.fr', 'visible': 'true'}
|ERROR|2022-02-25 09:52:16,924|Bearer token: Bearer 1hmwp_fPsOgk8MzmBN455d5d5cf41c798620f0aa7195317d0723cc90b54a
|ERROR|2022-02-25 09:52:16,925|Connection status: established
|ERROR|2022-02-25 09:52:16,926|Socket session id: 1hmwp_fPsOgk8MzmBN45
|ERROR|2022-02-25 09:52:16,927|Can not parse server answer to json object: {"response":{"executed":false,"error":" \nORA-06512: at \"U100D2.API\", line 1177\nORA-06512: at line 1\n"}}.
|ERROR|2022-02-25 09:52:17,088|Server reports an error: {'executed': False, 'error': ' \nORA-06512: at "U100D2.API", line 1177\nORA-06512: at line 1\n'}.
|ERROR|2022-02-25 09:52:17,089|URL: [https://api-demo.fxcm.com:443/trading/update_subscriptions](https://api-demo.fxcm.com/trading/update_subscriptions)
|ERROR|2022-02-25 09:52:17,090|Headers: {'User-Agent': 'request', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'Bearer 1hmwp_fPsOgk8MzmBN455d5d5cf41c798620f0aa7195317d0723cc90b54a', 'Content-Type': 'application/x-www-form-urlencoded', 'Content-Length': '27'}
|ERROR|2022-02-25 09:52:17,092|Params: {'symbol': 'MVRS.us', 'visible': 'true'}
|ERROR|2022-02-25 09:52:17,093|Bearer token: Bearer 1hmwp_fPsOgk8MzmBN455d5d5cf41c798620f0aa7195317d0723cc90b54a
|ERROR|2022-02-25 09:52:17,094|Connection status: established
|ERROR|2022-02-25 09:52:17,095|Socket session id: 1hmwp_fPsOgk8MzmBN45
|ERROR|2022-02-25 09:52:17,096|Can not parse server answer to json object: {"response":{"executed":false,"error":" \nORA-06512: at \"U100D2.API\", line 1177\nORA-06512: at line 1\n"}}.
```


```
  | time | open | high | low | close | pair
-- | -- | -- | -- | -- | -- | --
2022-02-24 18:00:00 | 12262 | 12265 | 12261 | 12265 | USDOLLAR
2022-02-24 18:05:00 | 12265 | 12265 | 12259 | 12263 | USDOLLAR
2022-02-24 18:10:00 | 12263 | 12264 | 12259 | 12261 | USDOLLAR
2022-02-24 18:15:00 | 12261 | 12265 | 12259 | 12260 | USDOLLAR
2022-02-24 18:20:00 | 12260 | 12265 | 12260 | 12264 | USDOLLAR
... | ... | ... | ... | ... | ...
2022-02-25 15:30:00 | 12222 | 12226 | 12221 | 12226 | USDOLLAR
2022-02-25 15:35:00 | 12226 | 12228 | 12225 | 12226 | USDOLLAR
2022-02-25 15:40:00 | 12226 | 12226 | 12221 | 12222 | USDOLLAR
2022-02-25 15:45:00 | 12222 | 12222 | 12219 | 12222 | USDOLLAR
2022-02-25 15:50:00 | 12222 | 12223 | 12222 | 12222 | USDOLLAR
```

**Comment by FXCMAPI** [comment]
Hi,

Please unsubscribe and re-subscribe from Trading Station to the following two instruments - ACA.fr (this is Credit Agricole from French Shares) and MVRS.us (Meta Platform from US Shares) - this should solve the problem.
