### ISSUE TITLE
How to get more error info?

### ISSUE THREAD

**Issue by bitnick10** [fxcm/RestAPI#185]
When connect to server failed error info printed:
ServerError: Can not connect to FXCM Server.
But I don't know which part is wrong like 
1.server close
2.proxy failed
3.account id error
4.account id expired
5.connection timeout
etc.

**Comment by FXCMAPI** [comment]
Hi,

You can get more details in the log by setting log level to 'debug'.
We would be happy to assist - you can send the log and your FXCM account number to api@fxcm.com
