### ISSUE TITLE
Unable to get historical data based on date ranges

### ISSUE THREAD

**Issue by sjahajeeah** [fxcm/RestAPI#189]
E.g data = pd.DataFrame(con.get_candles( 'EUR/USD', period= 'm15',num=10000, From= 1648126800, To= 1650808800, dt_fmt="%Y-%m-%d %H:%M:%S")['candles'])

 This code will return 10000 records instead of the data between the "from" and "to" timestamp, if you do not specify a value for "num", the code fails which is counter intuitive - ideally you would expect to be able to extract candle info based on dates or number of records.

**Comment by fxcm-dhalpert** [comment]
please try with num=0

**Comment by sjahajeeah** [comment]
Hi Daniel, 
Thanks for getting back to me, I have tried with num = 0, same error message - screenshot attached with num=0 and num=1.
num=1 works i.e. it returns 1 record, num=0 fails to return dataset within date range, instead returns an error message.
Am I meant to update something on my end post the update you have done i.e. should I be updating my fxcm_rest_api_token file?
Regards,Sunjoo Jahajeeah

Mobile : +614 2151 2393
Skype : sjahajeeah
 

    On Monday, May 2, 2022, 03:01:27 PM GMT+10, Daniel Halpert ***@***.***> wrote:  
 
 


please try with num=0

**Comment by FXCMAPI** [comment]
There was performance issue on our fxcmpy python package.  We are still working on it. 
We apologize for the inconvenience.

Rest API use socket which is hard to maintenance a stable socket connection.
I suggest Forex Connect python (version 3.5, 3.6, 3.7) package. Which doesn't use socket and the connection is very stable.
 
Example programs:
https://github.com/gehtsoft/forex-connect/tree/master/samples/Python
http://fxcodebase.com/code/viewtopic.php?f=51&t=66684&sid=dd4ccb493f1dfe54d5ae1e25baeec405 Download/install:
https://pypi.org/project/forexconnect/
