### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by zxhaxdr** [fxcm/RestAPI#19]
When trading BOT run for a time period (usually over one week). I will get the following error.

`|WARNING|2019-03-20 21:15:21,251|api.fxcm.com:443/socket.io [connection error] HTTPSConnectionPool(host='api.fxcm.com', port=443): Max retries exceeded with url: /socket.io/?access_token=******************************************&agent=pythonquants&EIO=3&transport=polling&t=1553116519099-0 (Caused by SSLError(OSError(24, 'Too many open files'),))`

This error will keep occurring when the BOT keeps running and it's everywhere in the log file. Used the following to reconnect if any error happens:
`def reconnect(self):`
`self.con.close()`
`del self.con`
`self.con = None`
`time.sleep(1)`
`self._connect()`

**I'm not sure if reconnect() made the infinite number of the errors into the log file or fxcmpy made the errors in the log.** Then the BOT will freeze. What does this warning mean? Thanks.

**Comment by FXCMAPI** [comment]
looks like issue not our our side
http://earthdef.caltech.edu/boards/4/topics/1611
thanks
Lei
