### ISSUE TITLE
Get an update on accounts

### ISSUE THREAD

**Issue by jpcetre** [fxcm/RestAPI#190]
Hi,
I am wondering how to generate an update on self.accounts?
I use the Equity as well as usableMargin3Perc values for the Accounts table. These values are retrieved at the connection, but never updated afterwards.
Regards,
JP

**Comment by fxcm-dhalpert** [comment]
you can subscribe for Account table update, 
POST /trading/unsubscribe
models=Account

**Comment by jpcetre** [comment]
I added "subscription_list": ["Account"] to fxcm_rest.json
