### ISSUE TITLE
What are the tick numbers? (Request for help.)

### ISSUE THREAD

**Issue by clearoak** [fxcm/RestAPI#193]
I just looked at live ticks.  One gets Bid, Ask, High and Low.   But high and low of which price?  The bid?  The ask?  And surely this is really a candle, because it's reporting only a tick or so per second.    Basically, the numbers don't make sense to me - help please?

**Comment by FXCMAPI** [comment]
subscribe market data will give you live ticks, it show you the bid/ask in real time.
it was not candle.
the high/low were session high/low.  people usually ignore it. because client only care the live bod/ask
