### ISSUE TITLE
I cannot import Volume 

### ISSUE THREAD

**Issue by yacdrak** [fxcm/RestAPI#194]
Hello everyone,
I'm trying to import historical data from FXCM API to try my strategy. The problem i cannot get the Volume (I need it to calculate the VWAP indicator).
Did you have a solution/alternative for the problem ?
Thank you for your help
![Screenshot 2022-05-21 at 14 28 10](https://user-images.githubusercontent.com/7192896/169651539-f5050dbb-466f-4b32-a322-1f5bf0bf83ab.png)

**Comment by fxcm-dhalpert** [comment]
The real trading volume available as indicator in Trading Station desktop, we don't have real volume in REST API.
