### ISSUE TITLE
Why is tick data reader limited to currency pairs? - Code extract

### ISSUE THREAD

**Issue by clearoak** [fxcm/RestAPI#195]
Here is the code from the fxcmpy package tick data reader:

class fxcmpy_tick_data_reader(object):
    """ fxcm_tick_data_reader, a class to fetch historical tick data provided 
    by FXCM
    """

    symbols = ('AUDCAD', 'AUDCHF', 'AUDJPY', 'AUDNZD', 'CADCHF', 'EURAUD',
               'EURCHF', 'EURGBP', 'EURJPY', 'EURUSD', 'GBPCHF', 'GBPJPY',
               'GBPNZD', 'GBPUSD', 'GBPCHF', 'GBPJPY', 'GBPNZD', 'NZDCAD',
               'NZDCHF', 'NZDJPY', 'NZDUSD', 'USDCAD', 'USDCHF', 'USDJPY')

The symbols are explicitly limited to currency pairs. 
So one can't get historical tick data for anything else, despite being able to stream it. 
No idea why this is so.  Still looks like an oversight.  
Explanation?

**Comment by FXCMAPI** [comment]
Hi,

REST API itself doesn't have historical tick data.

The tick data reader which is part from fxcmpy downloads data from https://github.com/fxcm/MarketData
Those are the only available symbols.

For any other symbol you can use ForexConnect API to download tick data.
https://github.com/fxcm/ForexConnectAPI
