### ISSUE TITLE
 pandas._libs.tslibs.np_datetime.OutOfBoundsDatetime: cannot convert input with unit 'ms' ON US30 Symbol.

### ISSUE THREAD

**Issue by Marcus2810** [fxcm/RestAPI#199]
self.con.subscribe_market_data('US30',[self.last_price])

Only symbol that is returning, 

`*** pandas._libs.tslibs.np_datetime.OutOfBoundsDatetime: cannot convert input with unit 'ms'`

**Comment by FXCMAPI** [comment]
Hi,

This is resolved now - all timestamps are in milliseconds.
