### ISSUE TITLE
some params is missing in rest api

### ISSUE THREAD

**Issue by orvice** [fxcm/RestAPI#2]
Hi, 

we were using ForexConnectAPI, and we can't find some params in rest api:

* Offer:  BaseUnitSize, MaxQuantity, MinQuantity   
* Trade: OpenOrderRequestTXT,Commission
* ClosedTrade: TradeIDOrigin, TradeIDRemain, CloseOrderRequestTXT

could we get those params in rest api?

the second question ,in  `POST /trading/open_trade` and `POST /trading/close_trade` api, could we set `RequestTXT`  in request?

**Comment by FXCMAPI** [comment]
Hi,

The Commission is available in Trade and ClosedTrade table, the field name is “com”, other fields currently not available from REST API.

Regards,
Daniel Halpert

**Comment by orvice** [comment]
Any plan to support those params in rest api?

**Comment by FXCMAPI** [comment]
Hello

Yes, this is in developing phase.
will update you when it is live.

thanks
Lei

**Comment by ebakkest** [comment]
Here we are 2+ years later, is there no progress on the Rest API? Can't find the OpenOrderRequestTXT in the C# implementation.

**Comment by FXCMAPI** [comment]
this is in development, will update you when it deployed.

**Comment by FXCMAPI** [comment]
just confirmed with developer that this has been released a month ago already. 
please try again and let me know if you have any questions.

**Comment by ebakkest** [comment]
Sorry, I forgot to emphasize:

Can't find the OpenOrderRequestTXT **in the C# implementation**

In the debugger I can see that it exists in the JSON reply, but the C# implementation you provide does not have it (actually doesn't look like it has been updated much since 2018).

Do you have any plans to bring the C# implementation up to date?
