### ISSUE TITLE
Please provide a Golang Implementation of the FXCM APIs REST

### ISSUE THREAD

**Issue by gocharting101** [fxcm/RestAPI#205]
Using Golang with Socketio client has been very very challenging.  Please provide a sample repo to connect to the socketio to get the correct connection ID and how to subscribe to live prices

**Comment by fxcm-dhalpert** [comment]
We don't have sample code in Golang, it seems the Golang socket.io is not working with our REST API.

**Comment by gocharting101** [comment]
Any solutions or workarounds using Golang that you can suggest,  Our backend is built on Golang

**Comment by fxcm-dhalpert** [comment]
Unfortunately, we don't have any usable solution for Golang with REST AP.
You may use Golang with our FIX API/connection, if you have Golang FIX library, for example QuickFix/Go
https://github.com/quickfixgo/examples

**Comment by scottjbarr** [comment]
This package works with FXCM. I was able to get a client running.

https://github.com/graarh/golang-socketio

**Comment by fxcm-dhalpert** [comment]
Great, thanks for sharing.

**Comment by gocharting101** [comment]
@scottjbarr Did you actually try to connect and subscribe to the symbol.  When I tried with this package, it established the connection but the connectionID was not able to either subscribe to the symbols nor was I able to fetch the REST calls with that ID.  If you can share your code sample, I will be very grateful

**Comment by fxcm-dhalpert** [comment]
No, I didn't tried to connect, I thought it was working for you.

**Comment by gocharting101** [comment]
So when you connect to the socket, a socketID is returned which is also called the connectionID.  Now this connectionID is used for both REST calls and streaming prices.  The socketID that is returned when using the nodejs package works fine.  But the socketID returned when using the Golang  https://github.com/graarh/golang-socketio seems to have an issue as it does not successfully call the REST API nor the streaming subscriptions

**Comment by gocharting101** [comment]
Attaching my code. The connID is the issue

conn, err := gosocketio.Dial(
		"wss://api-demo.fxcm.com/socket.io/?access_token=XXXXXXXXXXXXXXa&EIO=4&transport=websocket",
		transport.GetDefaultWebsocketTransport(),
	)
	if err != nil {
		glog.Info("Client Error : ", err)
		return nil, err
	}
	err = conn.On("/message", func(h *gosocketio.Channel) {
		glog.Println("--- Got chat message: ")
	})
	if err != nil {
		glog.Error("Message Error ", err)
		return nil, err
	}

	err = conn.On(gosocketio.OnDisconnection, func(h *gosocketio.Channel) {
		glog.Error("Disconnected")
	})
	if err != nil {
		glog.Error("Disconnection Error ", err)
		return nil, err
	}

	err = conn.On(gosocketio.OnConnection, func(h *gosocketio.Channel) {
		glog.Println("Connected")
		glog.Info("Channel ID : ", h.Id())

	})
	if err != nil {
		glog.Error("Connection Error ", err)
		return nil, err
	}
	time.Sleep(5 * time.Second)

	// do something, handlers and functions are same as server ones
	connId := conn.Id()

	authToken := fmt.Sprintf("Bearer %s%s", connId, apiToken)
	glog.Info("Connection ID : ", connId)

demo.fxcm.com:443/trading/get_instruments/"
	loc := "https://api-demo.fxcm.com:443/subscribe?pairs=EUR%2FUSD"
	d := "pairs=EUR%2FUSD"
	by, _ := json.Marshal(d)


	req, err := http.NewRequest(
		"POST",
		loc,
		bytes.NewBuffer(by),
	)
	dump, _ := httputil.DumpRequest(req, true)
	glog.Info("DUMP : ", string(dump))
	if err != nil {
		return nil, err
	}
	req.Header.Add("Authorization", authToken)
	req.Header.Add("Accept", "application/json")
	req.Header.Add("Content-Type", "application/x-www-form-urlencoded")
	req.Header.Add("User-Agent", "request")

	client := &http.Client{}
	glog.Info("Is Connection Alive? ", conn.IsAlive())
	resp, err := client.Do(req)

	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	b, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	glog.Info("DATA : ", string(b))

**Comment by scottjbarr** [comment]
HI @gocharting101

It definitely works. I've got it running now.

You have to subscribe to the endpoint socketio endpoint to get a socket ID.

Once you have that you make REST calls with your socket ID with your API
key. These are working for me.

You make the "subscribe" call to the REST API. Let's say for "EUR/USD".

The socketio client needs to watch for messages of type "EUR/USD".

**Comment by gocharting101** [comment]
@scottjbarr I have pasted my bit of the code. I feel the connId := conn.Id() part is where I am going wrong. The connId is not giving me the data. Please note I am in demo mode

**Comment by scottjbarr** [comment]
@gocharting101 

The connId is correct.  Your code works. 

Just change the socketio url value to `EIO=3` instead of `EIO=4`.

I'll share my fxcm package sometime soon but I need to review it before I make it public.

**Comment by scottjbarr** [comment]
Don't forget to add functions to the price update messages, or whatever messages you want.

For example, price updates for `"EUR/USD"` ...

```
client.On("EUR/USD", func(ch *gosocketio.Channel, msg interface{}) {
    b := []byte(msg.(string))

    // this is just a struct that maps to the message
    p := fxcm.Pair{}

    if err := json.Unmarshal(b, &p); err != nil {
        // ...
    }

    // you have a price update now, enjoy
})
```
