### ISSUE TITLE
Question: What are numbers in rates array pushed by server

### ISSUE THREAD

**Issue by Soumyadeep21** [fxcm/RestAPI#206]
`"{"Updated":1659088495096,"Rates":[1.01888,1.0189599999999999,1.0183499999999999,1.02566],"Symbol":"EUR/USD"}"`
Server gives us this above data as price updates, what are the numbers in rates array signify.

**Comment by fxcm-dhalpert** [comment]
the fields are: bid, ask, session low, session high, the daily session starts at 17:00 EST

**Comment by Soumyadeep21** [comment]
> the fields are: bid, ask, session low, session high, the daily session starts at 17:00 EST

Thanks for the answer
