### ISSUE TITLE
 Failed to create order with type UNKNOWN, type is unknown when opening a trade. 

### ISSUE THREAD

**Issue by Marcus2810** [fxcm/RestAPI#210]
With the FXCM Rest API. 

send { "method":"POST", "resource":"/trading/open_trade", "params": { "account_id":"900613", "symbol":"US30", "is_buy":true, "amount":1, "time_in_force":"GTC","order-type":"AtMarket" } }

What is the parameter for order-type, and where can I find the other paraemeters.

**Comment by FXCMAPI** [comment]
Hi,

The parameter name is order_type.
For more info you can check page 24 of REST API specs - https://apiwiki.fxcorporate.com/api/RestAPI/Socket%20REST%20API%20Specs.pdf

**Comment by Marcus2810** [comment]
Thank you, you're rest API, looks great.
