### ISSUE TITLE
fxcmpy.fxcmpy.ServerError: Can not connect to FXCM Server.

### ISSUE THREAD

**Issue by UladzimirLaziuk** [fxcm/RestAPI#213]
fxcmpy == 1.2.6
socketio == 4.4.0
engineio == 3.14.2

con = fxcmpy.fxcmpy(access_token=TOKEN, log_level='debug', server='demo2', log_file='log.txt')
print(con.get_instruments())

everything was working yesterday...

**Comment by FXCMAPI** [comment]
Hi,

Please use the following versions:
fxcmpy==1.3.3
python-socketio==5.0.4
python-engineio==4.3.1
websocket-client==1.3.3

**Comment by UladzimirLaziuk** [comment]
fxcmpy == 1.3.3
python-socketio== 5.0.4
python-engineio==4.3.1
websocket-client==1.3.3

raise ServerError('Can not connect to FXCM Server.')
fxcmpy.fxcmpy.ServerError: Can not connect to FXCM Server.

**Comment by FXCMAPI** [comment]
Hi,

It seems to be an issue on our side, we are currently checking. I will let you know as soon as this is resolved.

Please use the new library versions from now on.

**Comment by FXCMAPI** [comment]
Hi,

Please let us know if you still have this problem.

**Comment by UladzimirLaziuk** [comment]
Thanks, it works

**Comment by UladzimirLaziuk** [comment]
Good afternoon. Please tell me I often get the error
fxcmpy.fxcmpy.ServerError: Can not connect to FXCM Server.Is this a common
error typical of demo servers or will there be such errors on real servers
after the application is launched?Thanks)

вт, 20 сент. 2022 г. в 18:29, FXCM ***@***.***>:

**Comment by FXCMAPI** [comment]
Hi,

The REST API is using socket.io, and it often causes such problems to clients.
We would recommend Forex Connect API which is not using socket.io, and the connection is a lot more stable.

FC API main page: https://github.com/fxcm/ForexConnectAPI

The connection URL [www.fxcorporate.com/Hosts.jsp](http://www.fxcorporate.com/Hosts.jsp) is for all accounts demo and real.
To connect need four parameters, <username>, <password>, “Real” or “Demo”, [www.fxcorporate.com/Hosts.jsp](http://www.fxcorporate.com/Hosts.jsp).

Example programs in Python for Forex Connect API:
https://github.com/gehtsoft/forex-connect/tree/master/samples/Python
Download/install:
https://pypi.org/project/forexconnect/
Works with Python versions 3.5, 3.6 and 3.7

Online Help:
https://fxcodebase.com/bin/forexconnect/1.6.4/help/Python/web-content.html#index.html
