### ISSUE TITLE
fxcmpy.fxcmpy.ServerError: Can not connect to FXCM Server.

### ISSUE THREAD

**Issue by UladzimirLaziuk** [fxcm/RestAPI#214]
Hello((
fxcmpy == 1.3.3
python-socketio== 5.0.4
python-engineio==4.3.1
websocket-client==1.3.3

raise ServerError('Can not connect to FXCM Server.')
fxcmpy.fxcmpy.ServerError: Can not connect to FXCM Server.

**Comment by imadmoussa1** [comment]
Hello,
I am having the same error, how did fix this?
My code was working but when I updated it to these requirements I had this error:
 fxcmpy.fxcmpy.ServerError: Can not connect to FXCM Server.

**Comment by FXCMAPI** [comment]
Dear Clients

Rest API use socket which is hard to maintenance a stable socket connection.
I suggest Forex Connect python (version 3.5, 3.6, 3.7) package. Which doesn't use socket and the connection is very stable.
 
Example programs:
https://github.com/gehtsoft/forex-connect/tree/master/samples/Python
https://fxcodebase.com/bin/forexconnect/1.6.4/help/Python/order_parameters.html
https://fxcodebase.com/code/viewforum.php?f=51
Download/install:
https://pypi.org/project/forexconnect/
 
 
Hope this help 
-Lei
