### ISSUE TITLE
Bad default parameter type

### ISSUE THREAD

**Issue by asier-paz** [fxcm/RestAPI#23]
https://github.com/fxcm/RestAPI/blob/eaf510ce154aa83df7e79f64d0ae2edbada7dbee/fxcm-api-rest-python3-example/fxcm_rest_api_token.py#L847

Hello.

Turns out that after hours trying to make the "close_all_for_symbol" call and returning a "for_symbol is a required field" error, I fixed it by changing the default value of the forSymbol parameter to 'true' as a string. Seems like the API does not parse boolean values.

Just wanted to let others who might be fighting this error to know how to fix it...

**Comment by FXCMAPI** [comment]
thank you Asier
confirmed the bug, will fix it in next release

best regards
Lei
