### ISSUE TITLE
Fxcm Get_candle get the old data

### ISSUE THREAD

**Issue by jimmylai-hk** [fxcm/RestAPI#24]
First of all, thanks for reading this message and help on the issue.

I'm using python wrapper (fxcmpy package) to get the last one minute candle with the following simple code.  

while True:
    last_seconds=int(time.strftime("%S"))
    if (last_seconds >= 59) :
        time.sleep(2)
        candle=con.get_candles("EUR/USD", period='m1',number=1)
        print(candle)

Sometime, I found that the candle return do not update at all and just return the same candles.  (See the out below.  All the candles are the same)   Is it the server issue or something wrong with my code?

                     bidopen  bidclose  bidhigh   bidlow  askopen  askclose  \
date                                                                          
2019-04-29 00:07:00  1.11495   1.11499  1.11499  1.11495  1.11502   1.11506   

                     askhigh   asklow  tickqty  
date                                            
2019-04-29 00:07:00  1.11506  1.11502       14  
                     bidopen  bidclose  bidhigh   bidlow  askopen  askclose  \
date                                                                          
2019-04-29 00:07:00  1.11495   1.11499  1.11499  1.11495  1.11502   1.11506   

                     askhigh   asklow  tickqty  
date                                            
2019-04-29 00:07:00  1.11506  1.11502       14  
                     bidopen  bidclose  bidhigh   bidlow  askopen  askclose  \
date                                                                          
2019-04-29 00:07:00  1.11495   1.11499  1.11499  1.11495  1.11502   1.11506   

                     askhigh   asklow  tickqty  
date                                            
2019-04-29 00:07:00  1.11506  1.11502       14

**Comment by fxcm-dhalpert** [comment]
The issue with intraday historical data has been resolved.
