### ISSUE TITLE
tuple indices must be integers or slices, not str

### ISSUE THREAD

**Issue by dominhtri1995** [fxcm/RestAPI#28]
Hi,

I have this error when trying to call get_candles method in Python3 for all the symbols which are not "Visible"

`Error: tuple indices must be integers or slices, not str`

Any way I can access these symbols ? It looks like symbols which has 'visible': false couldn't be found with self.symbol_info.get(instrument, {}).get('offerId', -1), which led to the crash

**Comment by FXCMAPI** [comment]
can you try below
TOKEN = "your token"
con = fxcmpy.fxcmpy(access_token=TOKEN, log_level='error', server='demo', log_file='log.txt')
con.is_connected()
data = con.get_candles('EUR/USD', period='H1', number=5)
data

**Comment by dominhtri1995** [comment]
yeah I installed the FXCMpy and it's working now. However using the example folder didn't work. Thanks
