### ISSUE TITLE
H4 candle data error

### ISSUE THREAD

**Issue by dominhtri1995** [fxcm/RestAPI#29]
Hi,
It looks like there is an error with H4 candles. Other timeframe works fine. You can see it's all green.

![image](https://user-images.githubusercontent.com/17529911/57477952-fe2c0e00-72c3-11e9-8718-9a3fed9b4ca4.png)

Is there anyway to fix it ?

**Comment by FXCMAPI** [comment]
we do have issue on H4 candles. we are working on it. will update you the progress
thanks
Lei
