### ISSUE TITLE
Getting error "Amount should be divisible by 10" after min-trade-size has been adjusted to 1k

### ISSUE THREAD

**Issue by redsalmon91** [fxcm/RestAPI#30]
Request:
```
{
  "account_id": "xxxxxxxxx",
  "symbol": "USD/JPY",
  "is_buy": true,
  "rate": 0,
  "amount": 1,
  "at_market": 0,
  "order_type": "AtMarket",
  "time_in_force": "FOK"
}
```

Response:
```
{
  "response": {
    "executed": false,
    "error": "{"code":3,"message":"Amount should be divisible by 10","parameters":["10"]}"
  },
  "data": {}
}
```

**Comment by fxcm-dhalpert** [comment]
this error means your account minimum order size for FX is 10k, and your order amount was only 1k.

**Comment by redsalmon91** [comment]
> this error means your account minimum order size for FX is 10k, and your order amount was only 1k.

Thanks for the reply. I have already asked them to adjust my min order size to be 1k, is there a way to check this settings? (like a portal somewhere?)

Thanks

**Comment by fxcm-dhalpert** [comment]
The simple way is trying to place 1k entry order in Trading Station, if the minimum size is 10k it won't let you place an order below 10k.

**Comment by redsalmon91** [comment]
> The simple way is trying to place 1k entry order in Trading Station, if the minimum size is 10k it won't let you place an order below 10k.

I am able to place 1k orders in Trading Station, but the REST api is behaving differently. I suspect there is a non-account-specific check on the REST api. Could you help me to confirm this?

**Comment by redsalmon91** [comment]
Root cause is using account number as account id.
