### ISSUE TITLE
Can not open config file: fxcm.cfg

### ISSUE THREAD

**Issue by vucoofigaloo** [fxcm/RestAPI#31]
To get historical data I did con = fxcmpy.fxcmpy(config_file='fxcm.cfg') like outlined but is giving the error (Can not open config file: fxcm.cfg).

**Comment by fxcm-dhalpert** [comment]
you can try like this:
token='11111111111111111111111'
api = fxcmpy.fxcmpy(access_token=token, log_level='error',server='demo',log_file='log.txt')
server='demo' or 'real' for demo or real accounts

**Comment by sam30606** [comment]
code-runner.fileDirectoryAsCwd

It's a relative path issue.
