### ISSUE TITLE
Forex connect time out

### ISSUE THREAD

**Issue by dominhtri1995** [fxcm/RestAPI#33]
Hi I tried Forexconnect python but keep getting this error:
forexconnect.errors.LoginFailedError: Wait timeout exceeded

```
fx.login("D25725254", "8608", "fxcorporate.com/Hosts.jsp",
                     "Demo", session_status_callback=common_samples.session_status_changed)
```

Plz help

**Comment by fxcm-dhalpert** [comment]
can you please test with tracert fxcorporate.com, 
please check if you using the latest FC API 1.6.2 version
i tested with the Login.py example program:
python login.py -l D25725254 -p 8608 -c Demo -u fxcorporate.com/Hosts.jsp

**Comment by dominhtri1995** [comment]
I got it. thanks
