### ISSUE TITLE
Subscribe to more than 20 symbols

### ISSUE THREAD

**Issue by dominhtri1995** [fxcm/RestAPI#35]
Hi,

I'm using the ForexConnect version. Is there any way I can subscribe to real-time price of more than 20 symbols ? I think this question apply to the RestApi as well.

**Comment by fxcm-dhalpert** [comment]
You can email your username to api@fxcm.com and we can lift the 20 symbols limit.

**Comment by dominhtri1995** [comment]
can I do that with just a demo account ?

**Comment by fxcm-dhalpert** [comment]
yes

**Comment by dominhtri1995** [comment]
Thank you. I have emailed the request. Plz check and help me with the limit. I'm working on a strategy which requires that access.

**Comment by FXCMAPI** [comment]
issue resolved.
