### ISSUE TITLE
Problem with REST API when using multiprocessing module with "real" account

### ISSUE THREAD

**Issue by adrianpattinasarany** [fxcm/RestAPI#37]
Please run code below using real account vs demo account and advice why demo account can run this code smoothly while the real account can only retrieve USD/JPY with error Can Not Find FXCM server?

    import fxcmpy
    import time
    import multiprocessing
    import datetime as dt
    import pytz

    def symbol_function(symbol,collectio_n):
        #token = 'put real token here' #token real
        #con = fxcmpy.fxcmpy(access_token=token, log_level='error', server='real', log_file="APlog_real.txt")
        token = 'put demo token here' #token demo
        con = fxcmpy.fxcmpy(access_token=token, log_level='error', server='demo', log_file="APlog_demo.txt")
        while True:
            currenttime = dt.datetime.now(pytz.timezone('US/Eastern'))
            if currenttime.second ==0:
                openpositions = con.get_open_positions(kind='list')
                closedpositions = con.get_closed_positions(kind='list') 
                pricedata = con.get_candles(symbol,period='m1', number=1001)
                pricedata_m5 = con.get_candles(symbol, period='m5', number=1000)
                pricedata_D1 = con.get_candles(symbol, period='D1', number=350)
                StrategyHeartBeat(symbol,con,pricedata,pricedata_m5,pricedata_D1,collectio_n,openpositions,closedpositions)
            time.sleep(1)

    def StrategyHeartBeat(symbol,con,pricedata,pricedata_m5,pricedata_D1,collectio_n,openpositions,closedpositions):
        print (symbol+" len  openpositions = " + str(len(openpositions)))
        print (symbol+" len  closedpositions = " + str(len(closedpositions)))
        print (symbol+" len  pricedata = " + str(len(pricedata)))
        print (symbol+" len  pricedata_m5 = " + str(len(pricedata_m5)))
        print (symbol+" len  pricedata_m5 = " + str(len(pricedata_m5)))

    if __name__ == "__main__": 
        collectio_n = ['GBP/USD', 'USD/CAD', 'USD/JPY', 'NZD/USD']
        processes = {}        
        nomor_process = 0
        for symbol in collectio_n: 
            p = multiprocessing.Process(target=symbol_function, args=(symbol,collectio_n,))
            p.start()
            processes[nomor_process] = (p, symbol) # Keep the process and the app to monitor or restart
            nomor_process += 1

        while len(processes) > 0:
            currenttime = dt.datetime.now(pytz.timezone('US/Eastern'))
            hitung = 0
            for nomor_process in processes.keys():  #list(processes):
                hitung = hitung + 1
                (p, a) = processes[nomor_process]
                time.sleep(1)
                currenttime = dt.datetime.now(pytz.timezone('US/Eastern'))
                ap_print=(str(currenttime.second)+' symbol = ' + str(a),'p.exitcode = ' + str(p.exitcode),'p.is_alive() = ' + str(p.is_alive()))
                print(ap_print)

**Comment by FXCMAPI** [comment]
Hello Adrian. 
we are following up with you on api@fxcm.com closing this thread,
