### ISSUE TITLE
No updated prices found, trying again in 10 seconds...

### ISSUE THREAD

**Issue by gkourogiorgas** [fxcm/RestAPI#38]
I am running the small crossover strategy in python using fxcmpy.
I have run into two errors:
1. No updated prices found, trying again in 10 seconds...
What could be the reason for this? The market was open when several of these messages appeared
2. Error Opening Trade.
Why would a trade not open? I have a valid token and the account is on demo server.
Do I have to declare that it is a demo server in the connection or it identifies it automatically?

**Comment by fxcm-dhalpert** [comment]
please see example code how to get streaming prices with fxcmpy wrapper:
https://github.com/fxcm/RestAPI/blob/master/fxcmpy-doc/03_streaming_market_data.ipynb
