### ISSUE TITLE
Unauthorized Error

### ISSUE THREAD

**Issue by eswdevplus** [fxcm/RestAPI#4]
Hey! I'm trying to integrate your API into Cordova (Ionic 3) for mobile use!
I'm running into a tiny error which I'm sure can be resolved easily, but I am going to need some help.

Code used to access Live prices: _(note that code has been slightly modified for this post but all logic is intact)_

Head code:
```
TRADING_API_URL = 'https://api-demo.fxcm.com:443';
ACCESS_TOKEN = "8dXXXXXXXXXXXXXXXXXXXXXXXXXXX71"; // Demo Token

socket = io('https://api-demo.fxcm.com:443', {query: 'access_token=8dXXXXXXXXXXXXXXXXXXXXXXXXXXX71'}); // Connect to socket.io
io.connect();

socket.on('connect',()=> {
      console.log("Websocket connected.");
      bearer_access_token = "Bearer " + this.socket.id + this.ACCESS_TOKEN; // Build Bearer
      this.LiveData(); // Make the POST request
    });
```

Function **LiveData()**:
```
 let method = '/subscribe';
 let headers, data; // Ignore

    this.http.post(this.TRADING_API_URL + method,
                                                  headers = {
                                                       'User-Agent': 'request',
                                                       'Authorization': this.bearer_access_token,
                                                       'Accept': 'application/json',
                                                       'Content-Type': 'application/x-www-form-urlencoded'
                                                   },
                                                   data = {
                                                       'pairs': 'EUR/USD'
                                                   })
  .then(MyData => {

    console.log(MyData);
    console.log("Got the live prices!");

  })
  .catch(error => {

    console.log(error);
    console.log("Could not get live prices!");
  });
```
The JSON returned:

![image](https://user-images.githubusercontent.com/17680512/37645905-dbab65cc-2c30-11e8-852d-b5c1235b3357.png)

Why am I unauthorized?
Perhaps the session ID I'm getting from Socket.IO is invalid? I have no way of confirming that but I honestly do not know where the problem is.
An example of the bearer: `Bearer T9XbY2f3eXmBpI77AAmq8dXXXXXXXXXXXXXXXXXXXXXXXXXXX71`

**Comment by FXCMAPI** [comment]
Please email your username to api@fxcm.com<mailto:api@fxcm.com>, we might need to enable REST API for your username.

Regards,
Daniel Halpert

**Comment by illi4** [comment]
Eswdevplus, did you manage to close the issue? I am facing the same one currently and the API support is not suggesting anything unfortunately

**Comment by Killerbeans** [comment]
Same issue, please help

**Comment by FXCMAPI** [comment]
first make sure your token is valid by logon to our test program
restapi101.herokuapp.com/
then make sure you uninstall socketio-client, 
We did release on 1/24 that don’t support socketio-client package,

**Comment by Killerbeans** [comment]
Sorry I have trust issues, I can't enter my token on restapi101.herokuapp.com/. Is there any other way?

**Comment by FXCMAPI** [comment]
you can re-generate a new token if you want

**Comment by Killerbeans** [comment]
I've tested the token. It is valid, but I still get the same error in my C# code. I'm using the C# version of FXCMREST API, I can't find the repo any more online, however the problem is the same. Do you have an updated version of the C# FXCMREST API  and please where can I download it?
