### ISSUE TITLE
Socket takes very long time while connecting to FXCM server after uploding to Google Play Store

### ISSUE THREAD

**Issue by Krishna-Vyas** [fxcm/RestAPI#41]
Hello, I'm using Rest Api in Java(Android), But it takes now,  too much time while connecting to fxcm server and sometimes it does not connect, after i uploaded application to play store, before it working perfectly. I don't know what is the problem. Please provide some solution for it. Thank You.

**Comment by fxcm-dhalpert** [comment]
I just checked the REST demo and real servers and it works fine, the connection time is about one second.

**Comment by fxcm-dhalpert** [comment]
The servers get down/restarted on the weekend for maintenance, usually they up after Friday midnight EST.

**Comment by Krishna-Vyas** [comment]
Next Friday Means 23rd August?

**Comment by fxcm-dhalpert** [comment]
Yes.

**Comment by Krishna-Vyas** [comment]
Is server is in still maintenance?

**Comment by fxcm-dhalpert** [comment]
No.
