### ISSUE TITLE
Error handling / exc catching

### ISSUE THREAD

**Issue by adrpp** [fxcm/RestAPI#42]
Hello,

just wondering how to catch exceptions from fxcmpy. As you make use of threading, thread caller has no way (status quo) to catch any thrown exception in child thread.
Thought about `concurrent.futures` or a kind of Queue which would store thrown exceptions and make them accessible to caller ?

e.g. connect() or open_trade(), if an error happens, we got nice logger.error() logging, but the exception itself is not propagated.

Rgds,
Adrian

**Comment by fxcm-dhalpert** [comment]
you may try to set log_level='debug' so it will save more information for debugging

**Comment by adrpp** [comment]
hello,

I'm not talking about logging but exception catching.

example:
==> watch malformed symbol
try:
    con.open_trade(
        symbol='GERR30',
        is_buy=True,
        amount=1,
        order_type='AtMarket',
        time_in_force='GTC',
        stop=-10,
        trailing_step=1.0)
except:
    print('ERRR')
    raise

==> output
|ERROR|2019-08-27 21:23:29,320|Server reports an error: {'executed': False, 'error': '{"code":1,"parameters":[],"message":"The symbol is incorrect"}'}.
|ERROR|2019-08-27 21:23:29,321|URL: https://api-demo.fxcm.com:443/trading/open_trade
|ERROR|2019-08-27 21:23:29,321|Headers: {'User-Agent': 'request', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'Bearer XXXXX', 'Content-Type': 'application/x-www-form-urlencoded', 'Content-Length': '157'}
|ERROR|2019-08-27 21:23:29,321|Params: {'account_id': XXXXX, 'symbol': 'GERR30', 'is_buy': 'true', 'rate': 0.0, 'amount': 1, 'at_market': 0.0, 'order_type': 'AtMarket', 'time_in_force': 'GTC', 'limit': None, 'is_in_pips': 'true', 'stop': -10.0, 'trailing_step': 1}
|ERROR|2019-08-27 21:23:29,321|Bearer token: Bearer XXXXX
|ERROR|2019-08-27 21:23:29,321|Connection status: established
|ERROR|2019-08-27 21:23:29,321|Socket session id: XXXXXX
|ERROR|2019-08-27 21:23:29,321|Can not parse server answer to json object: {"response":{"executed":false,"error":"{\"code\":1,\"parameters\":[],\"message\":\"The symbol is incorrect\"}"},"data":{}}.
|DEBUG|2019-08-27 21:23:29,322|Server answer: {'response': {'executed': False, 'error': '{"code":1,"parameters":[],"message":"The symbol is incorrect"}'}, 'data': {}}.
|WARNING|2019-08-27 21:23:29,322|Missing orderId in servers answer.

You can see the error, but can't catch it in your own code.
This is due to `ServerError` is catched and not re-raised in fxcmpy.py on line 2523 in __handle_request__()

With patched fxcmpy file I get the exception raised so I can catch it. Why is it not re-raised in current fxcmpy code ?


The second part of this issue is related to errors that happen while streaming. As fxcmpy.connect() uses threading to 'unblock' SocketIO.wait() called in __connect__(), you don't get any exceptions at all. Here is a enhacement (via concurrent.features) possible too.

Rgds,
Adrian

**Comment by illi4** [comment]
Did you arrive to some solution? I am experiencing the same issue not understanding how to catch an error. The returned value is just None.

**Comment by adrpp** [comment]
@illi4 basically we wrote own socket io based client using `concurrent.features`, snippet:

        with concurrent.futures.ThreadPoolExecutor(max_workers=1) as executor:
            future = executor.submit(self._connect_socket_io)
            while not future.done():
                if future.exception():
                     #here goes your logic how to handle stream errors


where _connect_socket_io() method create the stream connection using `socketIO_client.SocketIO` cls.
We collect raised connections on instance of `StreamClient` and do checking before every rest api call if some stream errors occurred (in the meanwhile) ... 

Not ultra cool, but you have to deal with the fact how do you handle exceptions that were raised in a separate thread. So this is what came up while while my research, there might have be more elegant solutions :)

Rgds,
Adrian

**Comment by ra8870** [comment]
> @illi4 basically we wrote own socket io based client using `concurrent.features`, snippet:
> 
> ```
>     with concurrent.futures.ThreadPoolExecutor(max_workers=1) as executor:
>         future = executor.submit(self._connect_socket_io)
>         while not future.done():
>             if future.exception():
>                  #here goes your logic how to handle stream errors
> ```
> 
> where _connect_socket_io() method create the stream connection using `socketIO_client.SocketIO` cls.
> We collect raised connections on instance of `StreamClient` and do checking before every rest api call if some stream errors occurred (in the meanwhile) ...
> 
> Not ultra cool, but you have to deal with the fact how do you handle exceptions that were raised in a separate thread. So this is what came up while while my research, there might be more elegant solutions :)
> 
> Rgds,
> Adrian

Adrian,

Thank you so much for this - how is it working?  I'm having the same issues.  Would you be willing to share code on how you handle stream errors?

**Comment by FXCMAPI** [comment]
Whenever, our server detects session lost, we fire the disconnect event
So You can try to catch the event and action on it. 

var authenticate = (token) => {
                socket = io(trading_api_proto + '://' + trading_api_host + ':' + trading_api_port, {
                                                query: querystring.stringify({
                                                                access_token: token
                                                })
                                });
                // fired when socket.io connects with no errors
                socket.on('connect', () => {
                                console.log('Socket.IO session has been opened: ', socket.id);
                                request_headers.Authorization = 'Bearer ' + socket.id + token;
                });
                // fired when socket.io cannot connect (network errors)
                socket.on('connect_error', (error) => {
                                console.log('Socket.IO session connect error: ', error);
                });
                // fired when socket.io cannot connect (login errors)
                socket.on('error', (error) => {
                                console.log('Socket.IO session error: ', error);
                });
                // fired when socket.io disconnects from the server
                socket.on('disconnect', () => {
                                console.log('Socket disconnected, terminating client.');
                                process.exit(-1);
                });
}

Hope this help
