### ISSUE TITLE
H2, H4 candles are incorrect

### ISSUE THREAD

**Issue by mevda** [fxcm/RestAPI#45]
Hi,

H2, H4 candles are incorrect, the open price is always lower than the closed price

**Comment by fxcm-dhalpert** [comment]
we are aware of this issue, you can use the Historical Data Downloader program
https://www.fxcmapps.com/apps/basic-historical-data-downloader/

**Comment by mevda** [comment]
Just run a for loop on H1 candle and update H2, H4 is not that hard :)

**Comment by fxcm-dhalpert** [comment]
Yes, we know about this issue, so to get correct historical data you can use HDD program.

**Comment by mevda** [comment]
There are only 7 Instruments and H2 is not available in HDD program

**Comment by fxcm-dhalpert** [comment]
Please try to subscribe for additional symbols from Trading Station, then re-login in HDD.
