### ISSUE TITLE
Info about EMA calculation

### ISSUE THREAD

**Issue by Ulixestoitaca** [fxcm/RestAPI#48]
Hello,

thanks for this job first of all.
I would just like to have more info about this point in EMA:

returns += (row['difference (pips)'] * pip_cost * lot_size)

If I well understand being pip_cost < 1 it substract 12% from returns because this is the cost per transaction. So the pip cost would be ( 1 - pip_cost ). Is it rigth?

second question: how should be interpreted a return of 10 in a given year ?
the capital invested is unclear so I am a little uncertain about this point.

Thank you for any help

**Comment by FXCMAPI** [comment]
Hi
this is not API related questions
please reach to our sales at info@fxcm.co.uk and admin@fxcm.co.uk
