### ISSUE TITLE
the java example cannot connect

### ISSUE THREAD

**Issue by chlch** [fxcm/RestAPI#5]
I download the JavaRestClient, but the socket cannot connect.
![_20180327111121](https://user-images.githubusercontent.com/14156891/37944790-9ba83d2c-31af-11e8-90f5-1c3f276f0334.png)

it prints nothing

**Comment by FXCMAPI** [comment]
Hello Tony,

Can you please email your login id to api@fxcm.com<mailto:api@fxcm.com>?

Thank you,

Mylene Roman
API Support

**Comment by FXCMAPI** [comment]
Hello 

if you still have questions, please send mail to api@fxcm.com with token

thanks
Lei
