### ISSUE TITLE
Get response or error

### ISSUE THREAD

**Issue by illi4** [fxcm/RestAPI#50]
I am trying to understand how to get response or error in a variable so that I can work with them in code. Successfull requests to not return an answer (the returned variable is None). If there is an error, I can see it in logger, but how do I actually get the error text? Any hints would be highly appreciated.

**Comment by FXCMAPI** [comment]
you can try below 
var authenticate = (token) => {
	socket = io(trading_api_proto + '://' + trading_api_host + ':' + trading_api_port, {
			query: querystring.stringify({
				access_token: token
			})
		});
	// fired when socket.io connects with no errors
	socket.on('connect', () => {
		console.log('Socket.IO session has been opened: ', socket.id);
		request_headers.Authorization = 'Bearer ' + socket.id + token;
	});
	// fired when socket.io cannot connect (network errors)
	socket.on('connect_error', (error) => {
		console.log('Socket.IO session connect error: ', error);
	});
	// fired when socket.io cannot connect (login errors)
	socket.on('error', (error) => {
		console.log('Socket.IO session error: ', error);
	});
	// fired when socket.io disconnects from the server
	socket.on('disconnect', () => {
		console.log('Socket disconnected, terminating client.');
		process.exit(-1);
	});
}
