### ISSUE TITLE
'Unauthorized' error popping up after running a script with api for more than 15 minutes

### ISSUE THREAD

**Issue by illi4** [fxcm/RestAPI#51]
After the successful connection in a Python script, if I run run this script for more than around 15-30 minutes, I get the error 'Unauthorized' when performing any API requests. If I try to relogin, this also fails with 'unauthorized' error. This happens on the demo account. The URL I am using is https://api-demo.fxcm.com. 

This issue is only solved when a new IP is assigned to the machine where this is running so it seems that this is related to some lockouts or limits. This behaviour is seem both on Windows and Linux (Ubuntu) machines. Instead of fxcmpy, I tried using Python socketIO library directly to login, and it also fails with the same error. 

Support's response in an email was 'I just checked your token and it works, so it should be something from your settings'.

**Comment by FXCMAPI** [comment]
Hello illi4

FXCM Rest API use socket connection, that it can push the live update via socket however, client need to initiate the connection and monitor it.
"unauthorized"  message usually means you can't make connection or your session got lost but you are not aware. which can be triggered by many reasons, like server is down, network unstable or your request exceed our max limit. 
we have those max request in our github.
you can also try to catch the disconnect event that our sever sent 

var authenticate = (token) => {
	socket = io(trading_api_proto + '://' + trading_api_host + ':' + trading_api_port, {
			query: querystring.stringify({
				access_token: token
			})
		});
	// fired when socket.io connects with no errors
	socket.on('connect', () => {
		console.log('Socket.IO session has been opened: ', socket.id);
		request_headers.Authorization = 'Bearer ' + socket.id + token;
	});
	// fired when socket.io cannot connect (network errors)
	socket.on('connect_error', (error) => {
		console.log('Socket.IO session connect error: ', error);
	});
	// fired when socket.io cannot connect (login errors)
	socket.on('error', (error) => {
		console.log('Socket.IO session error: ', error);
	});
	// fired when socket.io disconnects from the server
	socket.on('disconnect', () => {
		console.log('Socket disconnected, terminating client.');
		process.exit(-1);
	});
}

thanks
Lei

**Comment by illi4** [comment]
This is not a solution. The caught error is 'Unauthorized', but why is it happening? Is there a way to troubleshoot this?

**Comment by FXCMAPI** [comment]
it may triggered by many reasons, server is down, session is lost but client still use the old session.
client passing the wrong parameter. 
please provide account or token if it is demo to api@fxcm.com for further investigation
