### ISSUE TITLE
Demo api is very unstable (failed login to tradingstation, unauthorized issue)

### ISSUE THREAD

**Issue by illi4** [fxcm/RestAPI#52]
The demo api has been proving to be extremely unstable. 

- Firstly, it is often impossible to login to tradingstation as it shows '503' error on the login window after clicking 'login' (at the same time, logging through the app is ok). 
- Secondly, there is an issue when a working token cannot be used anymore because the 'unauthorized' error has been returned. I am only using subscription to market updates at this point, and requesting offers table every 5 minutes, so I'm not hitting any api limits. 

The unauthorized issue in particular seems to be a recurring topic in many other issues which were closed without proper resolution on this repo. It does not happen on real account, but it is practically impossible to test on demo because of the unauth issue and inability to login and issue a new token. 

Does anyone else experience the same? Can support look at the issue properly instead of just testing this when the server works and responding that it works now? It has been a very frustrating month for me trying to get this work and I am almost willing to give up on fxcm at this point.

**Comment by FXCMAPI** [comment]
Hello Illia
I fully understand your concerns and frustration
we are aware of the server unstable and we are working on it 
It may take some time to find the root cause and apply fix on it. 
So before that, please bear with us 

we appreciate your help and patience
you can mail to api@fxcm.com,
