### ISSUE TITLE
Incorrect historical data?

### ISSUE THREAD

**Issue by andreaskoeszegi** [fxcm/RestAPI#54]
As mentioned in issue #49, I’ve struggles understanding my incoming data, when I use:
`con.get_candles('EUR/USD', period='H4', start=dt.datetime(2019,10, 1), end=dt.datetime(2019,11, 15)) `
Data doesn’t seem to fit the data I get from TS mobile (iOS)
![BCBFA86C-2821-4E4B-8367-A1B23040287E](https://user-images.githubusercontent.com/59321505/71550320-f5608780-29cd-11ea-9544-b3cbf9f57e6b.jpeg)
![E26FBDD6-1326-42B8-87AF-FA3E5ADD20B7](https://user-images.githubusercontent.com/59321505/71550321-f5608780-29cd-11ea-9e43-ca138684ce65.png)

Hope you can help me! Looking forward to the answer!

**Comment by FXCMAPI** [comment]
this is a known issue on Rest API that only 1 min chat m1 shows the correct results.
we are working on this, will update you as soon as we fix it.,

**Comment by andreaskoeszegi** [comment]
I think 1min doesn’t work as well, am I right?
![A25D796A-7E87-4E7F-B07F-47ADD7ED5C59](https://user-images.githubusercontent.com/59321505/71577747-9eee6880-2af5-11ea-817f-f33d6f85e97c.jpeg)
![58406C61-1846-48B0-A0B2-A67D95E93278](https://user-images.githubusercontent.com/59321505/71577755-a746a380-2af5-11ea-8e0d-1c9eeeae12e8.jpeg)
![44BE255A-DDEA-43DC-B639-6626CC698C4F](https://user-images.githubusercontent.com/59321505/71577756-a7df3a00-2af5-11ea-9559-7f1bd3f8d21e.jpeg)
