### ISSUE TITLE
BUG: fxcmpy claims it does not know the orderid but returns it in get_order_ids

### ISSUE THREAD

**Issue by Sdoof** [fxcm/RestAPI#55]
Hello 

While ordering in a loop (basically canceling the limit order after a specif time period and opening a new one, the code runs fine but after a while I am getting the following error message. I am using version 1.2.5 

  File "C:\Users\XXX\AppData\Local\Programs\Python\Python37\lib\site-packages\fxcmpy\fxcmpy.py", line 1647, in create_entry_order
    order = self.get_order(order_id)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python37\lib\site-packages\fxcmpy\fxcmpy.py", line 636, in get_order
    raise ValueError('No order with id %s' % order_id)
ValueError: No order with id 292936184

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/XXX/PycharmProjects/backtrader/STOP_LIMIT_FXCMTRADE.py", line 33, in <module>
    trailing_step=TRAIL)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python37\lib\site-packages\fxcmpy\fxcmpy.py", line 1650, in create_entry_order
    order = self.get_order(order_id)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python37\lib\site-packages\fxcmpy\fxcmpy.py", line 636, in get_order
    raise ValueError('No order with id %s' % order_id)
ValueError: No order with id 292936184

**Comment by fxcm-dhalpert** [comment]
this order was filled at 01/09/2020 08:04:49.387 UTC, 
this error means the order cancel request was after the order was filled or canceled.

**Comment by Sdoof** [comment]
Thanks Daniel

That helps, but after a rerun this AM I am still getting the following
message, after the code failed on the following line from the modification
suggested (3rd line from the top underlined)

if LEN > 0:
    while i < LEN:
        *try:*
            con.delete_order(TABLE.T[i])
            i=i+1
        except ValueError as e:
            if str(e).startswith("No order with order id"):
                if TABLE.T[i] in con.get_order_ids():
                    raise
                else:
                    pass
            else:
                raise

*Error message returned:*

Traceback (most recent call last):
  File
"C:\Users\olivi\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py",
line 672, in urlopen
    chunked=chunked,
  File
"C:\Users\olivi\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py",
line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File
"C:\Users\olivi\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py",
line 416, in _make_request
    httplib_response = conn.getresponse()
  File
"C:\Users\olivi\AppData\Local\Programs\Python\Python37\lib\http\client.py",
line 1344, in getresponse
    response.begin()
  File
"C:\Users\olivi\AppData\Local\Programs\Python\Python37\lib\http\client.py",
line 306, in begin
    version, status, reason = self._read_status()
  File
"C:\Users\olivi\AppData\Local\Programs\Python\Python37\lib\http\client.py",
line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File
"C:\Users\olivi\AppData\Local\Programs\Python\Python37\lib\socket.py", line
589, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\olivi\AppData\Local\Programs\Python\Python37\lib\ssl.py",
line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\olivi\AppData\Local\Programs\Python\Python37\lib\ssl.py",
line 929, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [WinError 10054] An existing connection was forcibly
closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File
"C:\Users\olivi\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\adapters.py",
line 449, in send
    timeout=timeout
  File
"C:\Users\olivi\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py",
line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File
"C:\Users\olivi\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\retry.py",
line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File
"C:\Users\olivi\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\packages\six.py",
line 734, in reraise
    raise value.with_traceback(tb)
  File
"C:\Users\olivi\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py",
line 672, in urlopen
    chunked=chunked,
  File
"C:\Users\olivi\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py",
line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File
"C:\Users\olivi\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py",
line 416, in _make_request
    httplib_response = conn.getresponse()
  File
"C:\Users\olivi\AppData\Local\Programs\Python\Python37\lib\http\client.py",
line 1344, in getresponse
    response.begin()
  File
"C:\Users\olivi\AppData\Local\Programs\Python\Python37\lib\http\client.py",
line 306, in begin
    version, status, reason = self._read_status()
  File
"C:\Users\olivi\AppData\Local\Programs\Python\Python37\lib\http\client.py",
line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File
"C:\Users\olivi\AppData\Local\Programs\Python\Python37\lib\socket.py", line
589, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\olivi\AppData\Local\Programs\Python\Python37\lib\ssl.py",
line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\olivi\AppData\Local\Programs\Python\Python37\lib\ssl.py",
line 929, in read
    return self._sslobj.read(len, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.',
ConnectionResetError(10054, 'An existing connection was forcibly closed by
the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/olivi/PycharmProjects/backtrader/STOP_LIMIT_FXCMTRADE.py",
line 55, in <module>
    try:
  File
"C:\Users\olivi\AppData\Local\Programs\Python\Python37\lib\site-packages\fxcmpy\fxcmpy.py",
line 1375, in delete_order
    params=params, protocol='post')
  File
"C:\Users\olivi\AppData\Local\Programs\Python\Python37\lib\site-packages\fxcmpy\fxcmpy.py",
line 2466, in __handle_request__
    proxies=self.proxies)
  File
"C:\Users\olivi\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py",
line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File
"C:\Users\olivi\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py",
line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File
"C:\Users\olivi\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py",
line 533, in request
    resp = self.send(prep, **send_kwargs)
  File
"C:\Users\olivi\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py",
line 646, in send
    r = adapter.send(request, **kwargs)
  File
"C:\Users\olivi\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\adapters.py",
line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.',
ConnectionResetError(10054, 'An existing connection was forcibly closed by
the remote host', None, 10054, None))

**Comment by fxcm-dhalpert** [comment]
to debug this issue can you print the TABLE.T[i] value before calling con.delete_order(TABLE.T[i])

**Comment by Sdoof** [comment]
Here we go
![TABLE_FXCMPY_API](https://user-images.githubusercontent.com/5991149/72157130-2608cf80-3385-11ea-88f5-d5b6ad44fa2f.PNG)

**Comment by Sdoof** [comment]
Here we go:

![TABLE_FXCMPY_API](https://user-images.githubusercontent.com/5991149/72157392-cbbc3e80-3385-11ea-85d1-6f0eac809d74.PNG)

**Comment by Sdoof** [comment]
Hi Daniel

Is what I have sent helpful?

Thanks

Olivier

*Kind regards,*
*Olivier Van Parys*

**Comment by michaelhazza** [comment]
I'm also having this issue - was there a resolution?

**Comment by Sdoof** [comment]
Not that I am aware off @michaelhazza - it seems the issue was closed nonetheless (?)
