### ISSUE TITLE
ServerError: Can not connect to FXCM Server.

### ISSUE THREAD

**Issue by RickyMacharm** [fxcm/RestAPI#56]
I have not been able to connect to my demo via my Jupyter notebook since last Sunday. 

running this:
`api = fxcmpy.fxcmpy(config_file='fxcm.cfg')`

...always gives me:
ServerError: Can not connect to FXCM Server.

**Comment by FXCMAPI** [comment]
please see release section 
We did a release on demo on 1/12/2020 to improve the Rest API. With that said, Our REST API wrapper fxcmpy has been updated, you need to install the latest fxcmpy version at 1.2.6. Here is the link where you can find the library: https://pypi.org/project/fxcmpy/#files Please have in mind that just with pip install fxcmpy it might not work as it won’t update the library, please use below command. pip install –U fxcmpy

**Comment by RickyMacharm** [comment]
All working now.

Thanks
