### ISSUE TITLE
import fxcmpy issues...

### ISSUE THREAD

**Issue by RickyMacharm** [fxcm/RestAPI#57]
Hello,

after installing the new version via:
`pip install –U fxcmpy`

I discovered that `import fxcmpy` gives an error `ModuleNotFoundError: No module named 'socketio'`

id there a different way of importing the new update?

**Comment by FXCMAPI** [comment]
please install 
pip install python-socketio

**Comment by RickyMacharm** [comment]
Thanks

**Comment by RickyMacharm** [comment]
Everything working now.

Thanks
