### ISSUE TITLE
RE: ServerError: Can not connect to FXCM Server after update of fxcmpy

### ISSUE THREAD

**Issue by RickyMacharm** [fxcm/RestAPI#59]
I have updated fxcmpy by uninstalling and installing

I have installed python-socketio

I have generated a new token from my demo account

I have repeated the steps above on my local machine and also on google colab

I am still getting the same server error

**Comment by RickyMacharm** [comment]
There are no error logs as there was no connection with the server initiated.

**Comment by FXCMAPI** [comment]
can you share your token?

**Comment by RickyMacharm** [comment]
fxcm.log

access_token = 83474f887bef910a459ec705fc8690a57999fb63

**Comment by FXCMAPI** [comment]
your token is working on my side
import fxcmpy
TOKEN ="83474f887bef910a459ec705fc8690a57999fb63"
con = fxcmpy.fxcmpy(access_token=TOKEN, log_level='error', server='demo', log_file='log.txt')
data = con.get_candles('EUR/GBP',period='D1',number=10000)
data.loc["2019-08-01 21:00:00":"2019-08-30 21:00:00"]

  | bidopen | bidclose | bidhigh | bidlow | askopen | askclose | askhigh | asklow | tickqty
-- | -- | -- | -- | -- | -- | -- | -- | -- | --

0.91335 | 0.91274 | 0.91692 | 0.91241 | 0.91415 | 0.91370 | 0.91716 | 0.91285 | 272162
0.91274 | 0.91289 | 0.91314 | 0.91280 | 0.91370 | 0.91376 | 0.91393 | 0.91373 | 7
0.91289 | 0.92252 | 0.92288 | 0.91312 | 0.91376 | 0.92298 | 0.92311 | 0.91337 | 289479
0.92252 | 0.92010 | 0.92488 | 0.91543 | 0.92298 | 0.92063 | 0.92511 | 0.91568 | 251649
0.92010 | 0.92193 | 0.92476 | 0.91873 | 0.92063 | 0.92276 | 0.92499 | 0.91897 | 273987

**Comment by RickyMacharm** [comment]
It is still not running...
it ran yesterday...after all the updates.

today it refused to run even on Google colab
![JupyterLab 1-15-2020 4-29-11 PM](https://user-images.githubusercontent.com/33702921/72446775-741e3880-37b4-11ea-89f8-0a30616057e6.png)

**Comment by FXCMAPI** [comment]
can you run below command on anaconda console
python -c "import socketio; print(socketio.__version__)"

**Comment by RickyMacharm** [comment]
![socketio 1-15-2020 4-44-04 PM](https://user-images.githubusercontent.com/33702921/72447826-5225b580-37b6-11ea-84f0-4d80517388a2.png)

**Comment by RickyMacharm** [comment]
![socketio version 1-15-2020 4-47-45 PM](https://user-images.githubusercontent.com/33702921/72448136-d2e4b180-37b6-11ea-9247-093567579ed7.png)

**Comment by FXCMAPI** [comment]
can you run telnet api-demo.fxcm.com 443 on cmd?

**Comment by RickyMacharm** [comment]
If I have the right commands I could do so. I have copied and pasted the above but none of the commands ran on cmd
I am using windows by the way

**Comment by RickyMacharm** [comment]
trying out "tracert api-demo.fxcm.com" now

**Comment by RickyMacharm** [comment]
request timed out

**Comment by RickyMacharm** [comment]
222 ms   209 ms   225 ms  api.fxcm.com [204.8.241.111]

**Comment by FXCMAPI** [comment]
looks like issue on network side.

**Comment by RickyMacharm** [comment]
But before the update...the network has been recieving fine.

I have tried alternative internet providers...still the same error.

**Comment by RickyMacharm** [comment]
This is using a different network provider. I am still getting the same error.
![tracert 1-15-2020 5-16-11 PM](https://user-images.githubusercontent.com/33702921/72450546-d712ce00-37ba-11ea-9218-13a0f7324653.png)

**Comment by RickyMacharm** [comment]
After the trace above...I ran the cell to connect to the server...I am still getting the can't connect to fxcm server error

**Comment by FXCMAPI** [comment]
let's do this.
1. try my token 35b91ea52c03042231d320e88d6ab9dfdc3d0eaa
2. try run on other browser or PC.

**Comment by RickyMacharm** [comment]
I have tried it with my own token and it works...on a different browser chromium.

seems like fxcm and google are at war today.

thanks for your help
