### ISSUE TITLE
ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host'

### ISSUE THREAD

**Issue by Sdoof** [fxcm/RestAPI#60]
Hello - the python code runs fine but i get a connectionResetError after a while.

**Comment by fxcm-dhalpert** [comment]
Can you please provide some more details on how to replicate this issue.

**Comment by Sdoof** [comment]
Thanks Daniel I have just sent the code - I have emailed the full details but it fails after a few hours on the canceling and reordering part which is done every 5 seconds:
 
    if LEN > 0:
        while i < LEN:
            try:
                con.delete_order(TABLE.T[i])
                # i=i+1
            except ValueError as e:
                if str(e).startswith("No order with order id"):
                    if TABLE.T[i] in con.get_order_ids():
                        raise
                    else:
                        pass
                else:
                    raise

**Comment by FXCMAPI** [comment]
Hi Sdoof, 
we did release to improve the performance and stability. 
please try again and let me know if you still have issue.

thanks
Lei
