### ISSUE TITLE
[C#] REST API downloaded data not complete

### ISSUE THREAD

**Issue by bitnick10** [fxcm/RestAPI#61]
datetime,open,high,low,close,volume
2020-01-21 06:00:00,1.10904,1.11019,1.10761,1.10939,83184
2020-01-20 06:00:00,1.10905,1.10915,1.10898,1.10904,21
2020-01-11 11:00:00,1.11049,1.11284,1.10844,1.11168,134524
2020-01-10 06:00:00,1.11048,1.11198,1.1092,1.1105,144009
2020-01-09 06:00:00,1.11518,1.11676,1.11014,1.11048,238488
2020-01-08 06:00:00,1.11964,1.1197,1.11329,1.11518,165132
2020-01-07 06:00:00,1.1165,1.12049,1.11566,1.11964,144010
2020-01-06 06:00:00,1.11554,1.11651,1.11595,1.1165,53
2020-01-04 06:00:00,1.11714,1.11793,1.11244,1.11554,173375
2020-01-03 06:00:00,1.12217,1.12134,1.11629,1.11714,129099
2020-01-01 06:00:00,1.11979,1.12387,1.11959,1.12217,132857
2019-12-31 06:00:00,1.1175,1.12202,1.1171,1.11979,149387
2019-12-30 06:00:00,1.1175,1.11765,1.1174,1.1175,10

**Comment by FXCMAPI** [comment]
can you be more specific what is wrong?

**Comment by bitnick10** [comment]
hi @FXCMAPI, there is lack data between 2020-01-11 and 2020-01-20

**Comment by fxcm-dhalpert** [comment]
It seems ok now, please try.

1578693600,1.11056,1.11175,1.11291,1.10851,1.11064,1.1123,1.11292,1.10851,134524, 2020-01-10 22:00
1578866400,1.11175,1.11147,1.11205,1.11133,1.1123,1.11188,1.11227,1.11187,168, 2020-01-12 22:00
1578952800,1.11147,1.1134,1.1147,1.11119,1.11188,1.11341,1.1147,1.11126,106549, 2020-01-13 22:00
1579039200,1.1134,1.11268,1.11446,1.11043,1.11341,1.11289,1.11446,1.11043,141538, 2020-01-14 22:00
1579125600,1.11268,1.11495,1.11635,1.11185,1.11289,1.11498,1.11635,1.11186,124516, 2020-01-15 22:00
1579212000,1.11495,1.11364,1.11728,1.11279,1.11498,1.11375,1.11729,1.11279,129674, 2020-01-16 22:00
1579298400,1.11364,1.10883,1.11425,1.10863,1.11375,1.10909,1.11427,1.10863,123325, 2020-01-17 22:00
1579471200,1.10883,1.1091,1.10921,1.10904,1.10909,1.10963,1.1097,1.10962,21, 2020-01-19 22:00
1579557600,1.1091,1.10945,1.11025,1.10767,1.10963,1.10952,1.11025,1.10768,83163, 2020-01-20 22:00
1579644000,1.10945,1.1082,1.1118,1.1081,1.10952,1.10825,1.11181,1.10812,128283, 2020-01-21 22:00
1579730400,1.1082,1.10925,1.10985,1.10702,1.10825,1.10932,1.10985,1.10702,131794, 2020-01-22 22:00
1579816800,1.10925,1.10511,1.11087,1.10363,1.10932,1.1056,1.11089,1.10363,180914, 2020-01-23 22:00
1579903200,1.10511,1.10239,1.10619,1.10198,1.1056,1.1027,1.10621,1.10196,144479, 2020-01-24 22:00
1580076000,1.10239,1.10306,1.10359,1.10264,1.1027,1.10359,1.10364,1.10289,527, 2020-01-26 22:00
1580162400,1.10306,1.10189,1.10376,1.10097,1.10359,1.10191,1.10377,1.10097,134421, 2020-01-27 22:00
1580248800,1.10189,1.10221,1.10253,1.09978,1.10191,1.10224,1.10254,1.09978,109053, 2020-01-28 22:00
1580335200,1.10221,1.10098,1.10277,1.09923,1.10224,1.1013,1.10277,1.09924,117319, 2020-01-29 22:00
1580421600,1.10098,1.10311,1.10394,1.10064,1.1013,1.10322,1.10394,1.10068,145927, 2020-01-30 22:00
1580526000,1.10311,1.10948,1.10955,1.10169,1.10322,1.10963,1.10963,1.10169,174667, 2020-02-01 03:00
1580680800,1.10827,1.10939,1.1095,1.108,1.10866,1.10959,1.1096,1.10817,312, 2020-02-02 22:00

**Comment by bitnick10** [comment]
yes @fxcm-dhalpert ,lack data happens sometimes. And why this candle data 2020-02-01 03:00 is different from others? this happens near 2 month to me too, they should be all xxxx-xx-xx 22:00

**Comment by fxcm-dhalpert** [comment]
The historical data gets synced every weekend with the data in Trading Station.
We'll check the 03:00 bar.

**Comment by bitnick10** [comment]
No weird datetime and no data lack since this week.

**Comment by bitnick10** [comment]
No weird datetime and no data lack this week.
