### ISSUE TITLE
TypeError: unsupported operand type(s) for -: 'datetime.date' and 'datetime.datetime'

### ISSUE THREAD

**Issue by trentnicholas** [fxcm/RestAPI#62]
The error 
File "/home/user/.local/lib/python3.7/site-packages/fxcmpy/fxcmpy.py", line 2148, in get_candles
    start = ((start - dt.datetime(1970, 1, 1)) / dt.timedelta(seconds=1))
TypeError: unsupported operand type(s) for -: 'datetime.date' and 'datetime.datetime'

arises from the following code
```
conn = fxcmpy.fxcmpy(config_file='fxcm.cfg')
start_date = datetime.date(2019, 1, 1)
end_date = datetime.date(2019, 12, 31)
data = conn.get_candles("EUR/USD", period="D1", start=start_date, end=end_date)
```

Line 2142 accepts the "start" parameter as an instance of datetime.date however Python is unable to do the subtraction on line 2148 between datetime.date and datetime.datetime.

The same problem exists with the "end" parameter.

Python version 3.7.5
fxcmpy version 1.2.6

**Comment by fxcm-dhalpert** [comment]
please try to include the time parameters, for example:
start_date = datetime.date(2019, 1, 1, 0 ,0, 0)
end_date = datetime.date(2019, 12, 31, 0, 0, 0)

**Comment by trentnicholas** [comment]
datetime.date doesn't accept time parameters. The object needs to be datetime.datetime.
However line 2142 in fxcmpy.py (quoted below) lets a datetime.date object through.
```
elif isinstance(start, dt.datetime) or isinstance(start, dt.date):
    pass
```

Changing the above line to the following wouldn't imply to those reading the code that datetime.date should be accepted and will also raise an error with a clear message with the else statement on line 2144.
```
elif isinstance(start, dt.datetime):
    pass
```

**Comment by fxcm-dhalpert** [comment]
her eis example how to use get_candles() function:

start = dt.datetime(2019, 9, 1, 0, 0, 0)
stop = dt.datetime(2019, 9, 4, 0, 0, 0)
data = con.get_candles('EUR/USD', period='H1', columns=['askclose'], start=start, end=stop)
print(data)

**Comment by fxcm-dhalpert** [comment]
you may need to add these import lines:

import fxcmpy
import datetime as dt
import pandas as pd

**Comment by trentnicholas** [comment]
I know how to use it and already have it working. I am trying to point out inconsistencies in the code so it can be improved.
