### ISSUE TITLE
this is a known issue on Rest API that only 1 min chat m1 shows the correct results.

### ISSUE THREAD

**Issue by RickyMacharm** [fxcm/RestAPI#63]
this is a known issue on Rest API that only 1 min chat m1 shows the correct results.
we are working on this, will update you as soon as we fix it.,

_Originally posted by @FXCMAPI in https://github.com/fxcm/RestAPI/issues/54#issuecomment-569577013_

Hello all

Has this been sorted yet?

**Comment by FXCMAPI** [comment]
yes, this has been fixed in the recent release. 
please reopen it if you see any issues
thanks
Lei
