### ISSUE TITLE
Cannot trade amount less than 1 lot

### ISSUE THREAD

**Issue by puguri** [fxcm/RestAPI#66]
**The issue:**
I want to trade haft of 1 lot = 0.5 lot by a Market Order.

**Document:**
The API documents wrote that: 

> amount: integer, the trades amount in lots. 

**So, API don't accept float number (0.5)**

**Reference:**
https://www.fxcm.com/fxcmpy/appendix.html

**Comment by mub4799** [comment]
That's true and it's as intended. Amount represents number of contracts. And in some cases number of contracts must be greater than even 1. e.g. For silver minimum number of contracts are 50 and for XML number of contracts must be 100.

Currently issue I am facing is to know the minimum contract size using API.

**Comment by puguri** [comment]
> That's true and it's as intended. Amount represents number of contracts which should be in whole number. And in some cases number of contracts must be greater than even 1. e.g. For silver minimum number of contracts are 50 and for XLM/USD number of contracts must be 100.
> 
> Currently issue I am facing is to know the minimum contract size using API.

The API is right but the document is wrong. The amount is in units not in lot. 1k units are the minimum size for nano lot. 

So, revise the document: 

> amount: int. amount *1k of units

**Comment by FXCMAPI** [comment]
quantity is integer, not float. 
for CFD, please refer to our CFD guide 
http://docs.fxcorporate.com/user-guide/ug-cfd-product-guide-ltd-en.pdf
