### ISSUE TITLE
How to find Minimum trade amount of instrument? 

### ISSUE THREAD

**Issue by mub4799** [fxcm/RestAPI#67]
I am developing a small scripts with suggests trade amount based on the risk% and Stop loss. I want this script to output exactly what to type in trade station entry order amount field.
To do that script has to know the minimum trade size (or contract size) however I am not able to find it in API (tried get_offers() function). I can see that in trade station simple rates screen as a tool tip on pipcost or mmr. If it's not available can it be calculated based on mmr or pipcost?

**Comment by mub4799** [comment]
I think I figured out the way to compute it using the pipCost. Since this cost is of a lot size in account currency. Anyway following will help to get the lot size. 

```
# Get lot size
pip_value_in_account_currency = instrument_offer.pip / account_quote_currency_price

# Round to whole number to avoid the fractional noise
lot_size = round(instrument_offer.pipCost / pip_value_in_account_currency)
lot_size
```
I have tested above with XAG/USD, EUR/USD and XLM/USD. Anyway would be nice if developer from fxcm can confirm or provide a better solution.

**Comment by FXCMAPI** [comment]
for CFD, you can check our guide at 
 http://docs.fxcorporate.com/user-guide/ug-cfd-product-guide-ltd-en.pdf
