### ISSUE TITLE
No change in visiblePL() or grossPL()

### ISSUE THREAD

**Issue by JTInfinite** [fxcm/RestAPI#7]
Hello,

Did you close the fxcmpy repository or am I confused? I'm sure you guys used to have a separate fxcmpy repo.

anyway, my issue is as follows:

```
try:
    open_position = self.broker.get_open_position(self.trade_id)
except Exception as e:
    self.master_log.error(e)
else:
    self.master_log.info('{} | DEBUG | GROSSPL (£) {} | VISIBLEPL (pips) {} | TRAILING PIPS {}'.format(self.instrument, open_position.get_grossPL(), open_position.get_visiblePL(), self.trailing_profit_pips))
```

Just recently, the output for the get_grossPL() and get_visiblePL() has been stuck on the initial values it receives and does not update. Here is some log output:

INFO : 23/10/2018 07:45:10 PM : USD/CHF | DEBUG | GROSSPL (�) 0.77374 | VISIBLEPL (pips) 2 | TRAILING PIPS 0

INFO : 23/10/2018 07:47:20 PM : USD/CHF | DEBUG | GROSSPL (�) 0.77374 | VISIBLEPL (pips) 2 | TRAILING PIPS 0

INFO : 23/10/2018 07:48:04 PM : USD/CHF | DEBUG | GROSSPL (�) 0.77374 | VISIBLEPL (pips) 2 | TRAILING PIPS 0

No change over 3 minutes. Happens on all pairs. Any ideas?

**Comment by FXCMAPI** [comment]
Hello Joe,

Thank you for your email. The fxcmpy repository has been moved to another location. Please try:

https://github.com/fxcm/RestAPI/tree/master/fxcmpy

Can you please provide the login where you are not seeing any order table updates?

Best regards,

Mylene Roman
API Support

**Comment by FXCMAPI** [comment]
Hello Joe,

Please send your login to api@fxcm.com<mailto:api@fxcm.com>

Best regards,

Mylene Roman
API Support

**Comment by FXCMAPI** [comment]
Hello Joe,
There was an issue on our side. 
this has been fixed and released
please try again and let me know if you still have issue. 

thanks
Lei

**Comment by JTInfinite** [comment]
Hi Lei,

Thanks for the response. I have updated the fxcmpy package via PIP this morning. The issue now is that the order object returned by either create_market_buy_order() or create_market_sell_order() is a nonetype. I can't call get_tradeId() on this nonetype.

Here is a snippet

` try:
            if isBuy:
                order = self.broker.create_market_buy_order(self.instrument, position_size) #SELF.BROKER IS FXCMPY
            else:
                order = self.broker.create_market_sell_order(self.instrument, position_size)
        except Exception as e:
            self.master_log.error("{} | ERROR PLACING ORDER | {}".format(self.instrument, e))
            self.hasPosition = False
        else:
            self.master_log.info('DEBUG | {}'.format(order)) #THIS IS NONE
            self.trade_id = order.get_tradeId()` #THIS THROWS EXCEPTION

**Comment by FXCMAPI** [comment]
Hello Joe

When you place an order. it first goes to Order table and you will get an order id. if order been executed immediately on market, your order will be removed from order table and create a new entry on open position table. you will get the order ID and trade ID if you monitor the open position table. 
so you can link the order id and trade id. 
hope this help. 

thanks
Lei

**Comment by FXCMAPI** [comment]
Hello Joe
first you need to subscribe open position table. 
def print_data(data):
    print(data)
con.subscribe_data_model('OpenPosition', (print_data,))

after you place the the order, you will get order id immediately. 
{"response":{"executed":true},"data":{"type":0,"orderId":81712802}}
then in your call back print_data you will get order id and trade id. 

hope this help.
Lei

**Comment by JTInfinite** [comment]
That helps, thanks.

How do I get the orderId immediately? Is that part of the OpePosition model?

Sent from Mail for Windows 10

**Comment by FXCMAPI** [comment]
Hello Joe

You will get it when you place the order. It is in the response message of open_trade.

Thanks
Lei

**Comment by JTInfinite** [comment]
order = self.broker.create_market_buy_order(self.instrument, position_size)

Return nonetype

As previously stated


Sent from Mail for Windows 10

**Comment by FXCMAPI** [comment]
Hello Joe

Please try below
[cid:image001.png@01D49191.32F6AF60]
Thanks
Lei

**Comment by JTInfinite** [comment]
There was nothing attached

Sent from Mail for Windows 10

**Comment by FXCMAPI** [comment]
attachment been blocked 
please run below
import fxcmpy

TOKEN = 'baca6377b9e104f6f26e1609bb8eece08638658c'
con = fxcmpy.fxcmpy(access_token=TOKEN, log_level='error', server='demo', log_file='log.txt')
con.is_connected()

def print_data(data): print(data) 
con.subscribe_data_model('OpenPosition', (print_data,))

order = con.create_market_buy_order(symbol='EUR/USD', amount=1)
print(order)
