### ISSUE TITLE
incorrect mmr values when using get_offers()

### ISSUE THREAD

**Issue by AhmedRajaie** [fxcm/RestAPI#70]
I am trying to get mmr values to be able to accurately calculate the largest position size I can open. 
I used con.get_offers(kind='dataframe') method to get that information. 
My problem is that all the returned columns are the same as in FXCM Trading Station **except** for the mmr one. 

Here is a screenshot of what I get using fxcmpy:
![1](https://user-images.githubusercontent.com/43614828/81291117-c1bafb80-9058-11ea-8aef-d6ab04f340b9.PNG)

and this is the one from FXCM Trading Station 
![2](https://user-images.githubusercontent.com/43614828/81291147-ce3f5400-9058-11ea-8af6-372dd7ea4922.PNG)

As you can see, some mmr values are not even close to the correct ones (e.g. mmr=0.01 for USD/CAD)!

It is worth mentioning that this problem happens when subscribing to a new instrument using con.subscribe_instrument('USD/CAD'). Now that the instrument is already subscribed to, restarting fxcmpy connection solves this issue. 
This is unreliable since there is a limit to the number of instruments I can subscribe to.

Also, is there another method to get mmr values?

**Comment by fxcm-dhalpert** [comment]
please email your username to api@fxcm.com

**Comment by AhmedRajaie** [comment]
> please email your username to [api@fxcm.com](mailto:api@fxcm.com)

Done

**Comment by fxcm-dhalpert** [comment]
please use the function get_model(models="Offer")

**Comment by AhmedRajaie** [comment]
> please use the function get_model(models="Offer")

No, it does not work too. Also, "Offer" has to be included between brackets when using it (I am using fxcmpy version '1.2.6')

Here is how to replicate the problem. 
1- make sure you are not already subscribed to that instrument using get_subscribed_symbols()
2- subscribe to a new instrument using connection.subscribe_instrument('CAD/CHF')
3- connection.get_model(models=["Offer"])

Here is a screenshoot
![image](https://user-images.githubusercontent.com/43614828/81406129-8ab41b00-9128-11ea-9eba-746a10d8465c.png)

MMR has the same incorrect value. Also, both emr and lmr are zeros! which is also incorrect.
Now, restarting fxcmpy connection will solve the problem. But Again, it is only because 'CAD/CHF' has already been subscribed too! 
Adding a new instrument will result in the same problem.

**Comment by fxcm-dhalpert** [comment]
We are checking this issue, for now if you subscribe from Trading Station then MMR in REST API is correct.

**Comment by AhmedRajaie** [comment]
> We are checking this issue, for now if you subscribe from Trading Station then MMR in REST API is correct.

Thanks for checking this issue. However, suggesting to subscribe from Trading Station defeats the idea of automation in the first place!

**Comment by fxcm-dhalpert** [comment]
please try it, I just tested and seems ok now.

**Comment by AhmedRajaie** [comment]
> please try it, I just tested and seems ok now.

I just tried it and it is not working. I get the same incorrect behaviour.
![image](https://user-images.githubusercontent.com/43614828/81551038-af9acf00-9370-11ea-8e92-9fdb84c8ece1.png)
As you can see, both USD/JPY and AUD/JPY are correct because the had been subscribed too before starting fxcmpy connection. However, AUD/CAD is incorrect as I subscribed to it after I started the connection. 
I tried both methods 'get_offers' and 'get_model(['Offer'])' and they both give the same behaviour.

**Comment by fxcm-dhalpert** [comment]
we'll update you when it's fixed.
