### ISSUE TITLE
There's specification to stream offers table

### ISSUE THREAD

**Issue by jared201** [fxcm/RestAPI#71]
from the command.txt

```
table_subscribe {"tables":["Offer"]}

```
but as per section 5.1 of the Socket Rest API specs

<img width="983" alt="Screen Shot 2020-06-10 at 10 38 42 AM" src="https://user-images.githubusercontent.com/4927433/84220921-95d2e000-ab06-11ea-82c5-f0b5639e580a.png">

that's why that particular example is not working

**Comment by fxcm-dhalpert** [comment]
"Offer" is not one of the options for this function, to subscribe for live prices for EUR/USD:
POST   /subscribe
pairs=EUR%2FUSD

**Comment by FXCMAPI** [comment]
offer table is a static table that no need to subscribe. you can subscribe to account/open position table.
