### ISSUE TITLE
module 'fxcmpy' has no attribute 'fxcmpy_instruments'

### ISSUE THREAD

**Issue by jonatel** [fxcm/RestAPI#72]
Hi,

Importing fxcmpy is generating this error:

`AttributeError: module 'fxcmpy' has no attribute 'fxcmpy_instruments'`

**Comment by fxcm-dhalpert** [comment]
please try to re-install the fxcmpy
pip install -U fxcmpy

**Comment by jonatel** [comment]
Thanks for your guide.

After that, I got other error
`module “importlib._bootstrap” has no attribute “SourceFileLoader”`

but fixed updating the _setuptools_ package.

**Comment by FXCMAPI** [comment]
maybe this help
https://stackoverflow.com/questions/44761958/using-pip3-module-importlib-bootstrap-has-no-attribute-sourcefileloader
