### ISSUE TITLE
Can not connect to FXCM Server.

### ISSUE THREAD

**Issue by RickyMacharm** [fxcm/RestAPI#73]
I have been having this issues since Friday 10pm.

I wanted to do some analysis during the weekend. 

is it because of the market close period?

I have ran some analysis weekends before.

I also tried on colab and I got:  File "/usr/local/lib/python3.6/dist-packages/fxcm py/fxcm py.py", line 1135 return data ^ TabError: inconsistent use of tabs and spaces in indentation  when I tried to import fcmpy

**Comment by FXCMAPI** [comment]
Yes, due to America Holiday, our system stopped on Friday
