### ISSUE TITLE
How to place a trailing stop loss order?

### ISSUE THREAD

**Issue by chalagashvili** [fxcm/RestAPI#8]
Hi, thanks for awesome REST API.

I looked through API and experimented a lot but could not place a trailing stop loss order. 

From API I am using this: 

`open_trade(symbol, is_buy, amount, time_in_force, order_type, rate=0, is_in_pips=True, limit=None, at_market=0, stop=None, trailing_step=None, account_id=None)`

In my code I have written this:

`con.open_trade('USD/NOK', True, amount=1, stop=-5, time_in_force='GTC', order_type="AtMarket", trailing_step=1)`

I guess it must be a combination of "stop" and "trailing_step" parameters? Can you tell if Trailing Stop Loss is available via API or I am doing something wrong?

**Comment by fxcm-dhalpert** [comment]
Hi,

please add to open_trade parameters: 
is_in_pips=True

**Comment by chalagashvili** [comment]
thanks for reply! I added that parameter but it does not change anything, also as I see in docs True is the default value anyway.

I still see in Portal that stop and limit are set, but stopMove is not set: http://prntscr.com/lfg6r0

**Comment by chalagashvili** [comment]
As FXCM helped me, I had to have trailing_step=0.1 , and it works now! Closing the thread.

**Comment by bernarde01** [comment]
@chalagashvili I also trying to set this up. I have the trailing step parameter set to 0.1, and the trade executes, but the trailing stop is not activated:

opentrade = con.open_trade(symbol='EUR/USD', is_buy=True,amount=1, time_in_force='GTC',order_type='AtMarket',is_in_pips=True,limit=None, stop=-20,trailing_step=0.1)

**Comment by fxcm-dhalpert** [comment]
the trailing stop should be:
1 - for dynamic 
10 or above - for fixed trailing stop

**Comment by jeppekejser** [comment]
Should the trailing_stop be negative if short?

**Comment by fxcm-dhalpert** [comment]
No.
