### ISSUE TITLE
Unauthorized while subscribing to market data

### ISSUE THREAD

**Issue by Iltotore** [fxcm/RestAPI#80]
This is a modified repost of #77 because the issue got closed without any op-validated answer. The support team seems to completely ignore this issue.

Hello,

I'm trying to subscribe to FXCM's market data using Scala. I firstly open the socket.io connexion and the server responds positively:
```json
0{"sid":"cJaWmJyJyb5GamO3AXar","upgrades":[],"pingInterval":25000,"pingTimeout":5000}
```

then, I'm sending a subscription request to `api-demo.fxcm.com/subscribe` (note that I use a demo account).

- Request: 
```
HttpRequest(HttpMethod(POST),https://api-demo.fxcm.com:443/subscribe,List(User-Agent: request, Accept: application/json, Content-Type: application/x-www-form-urlencoded, Authorization: Bearer cJaWmJyJyb5GamO3AXarXXXXXXXXX))
```
XXXXXXX representing the token (the length is not significant)

- JSON Data:
```json
{
"pairs": "EUR/USD"
}
```

But I got an "Unauthorized" error:
```json
{
  "response" : {
    "executed" : false,
    "error" : "Unauthorized"
  },
  "pairs" : [
  ]
}
```

**Yes, I only use the newly get SID after sending a WS request:**
- Sending a WebSocket request
- Waiting for the Open packet
- Generating the Bearer ID from the Open's SID and the token: `"Bearer " + sid + token`
- Sending a subscribtion request (see `- Request` ↑)

I tried:
- Re-Checking my headers
- Waiting (in case of a potential REST API problem)
- Resetting my token

But I'm still getting this error. Note that the API send regularly a custom message (id 4) containing "0".

This "Unauthorized" issue seems to be a known issue but there is no viable answer: #51 #52

**Comment by fxcm-dhalpert** [comment]
can you please email the username and token to api@fxcm.com

**Comment by Iltotore** [comment]
The support just gave an answer that says litterally "it works on my machine" and then completely ignored my mails. I'm seriously wondering about switching to a more competent platform.

**Comment by fxcm-dhalpert** [comment]
the issue wasn't ignored, to check our logs we need the username and token.

**Comment by Iltotore** [comment]
> can you please email the username and token to api@fxcm.com
I did it. And:
> The support just gave an answer that says litterally "it works on my machine" and then completely ignored my mails.

**Comment by RickyMacharm** [comment]
> The support just gave an answer that says litterally "it works on my machine" and then completely ignored my mails. I'm seriously wondering about switching to a more competent platform.

Do you know of any. I am  sick and tired of the back and forth with this one too

**Comment by FXCMAPI** [comment]
Can you try your token on our test program next time? restapi101.herokuapp.com/
If you see the same issue, then your token is not valid, you have to re-generate a new token.
if not, it means token is valid and working as expected. issue may be somewhere else.
