### ISSUE TITLE
Stream CFDs data like Forex

### ISSUE THREAD

**Issue by rainb3rry** [fxcm/RestAPI#83]
Hi there, i would like to stream CFDs data for example TSLA.us like when i stream GBP/USD data.

When i try subscribe to them as i doing for parities, i got that error
`subscribe request # 2  not executed:  {
  response: { executed: false, error: 'Cannot subscribe to symbol: TSLA' },
  pairs: []
}`

How can i stream CFD data on socket? Thanks.

**Comment by lucy5435** [comment]
I have same issue, my account is real by the way. Can you share your code to compare ?

**Comment by fxcm-dhalpert** [comment]
we are checking this issue

**Comment by fxcm-dhalpert** [comment]
the market is currently closed, for market hours see:
https://www.fxcm.com/markets/insights/fxcm-open-trading/#:~:text=Trading%20operations%20may%20be%20conducted,Sunday%205%3A00%20pm%20EST

**Comment by rainb3rry** [comment]
So, normally can we get CFD stream data like pairs, for example `price_subscribe {"pairs":"TSLA"}` or `price_subscribe {"pairs":"TSLA.us"}` or something? Thanks

**Comment by FXCMAPI** [comment]
it is TSLA.us, you can check the symbols on our tsweb2.0 GUI
