### ISSUE TITLE
fxcm_rest_api.py request give 'response': {'executed': False, 'error': 'Unauthorized'}

### ISSUE THREAD

**Issue by momodiallosn** [fxcm/RestAPI#85]
Hi,
I a experiencing some issues to get historical data using fxcm_rest_api.py.
It seems that a candle request is denied despite filling the access token and the required parameters.

The complete error message is:
{'response': {'executed': False, 'error': 'Unauthorized'}, 'instrument_id': 0, 'period_id': 0, 'candles': []}

I proceed as follows to debug fxcm_rest_api.py 

import fxcm_rest_api
from collections import namedtuple
import requests
import socketio
import logging
import json
import uuid
import threading
from dateutil.parser import parse
from datetime import datetime
import time
import types

ACCESS_TOKEN="***903be6e55182ac********" # here i hide my access token but input the correct one in my script

environment="demo"
trader = trading_test.Trader(ACCESS_TOKEN,environment)
a = trader.login()
print("logged ===>",a) # i get {'status': True, 'data': 'Connecting'} which seems ok
print("connexion id ===>",trader.socketIO.eio.sid)

params = {"num":num,"from":1498125600,"to":1498150800}
trader.HEADERS['Authorization'] = trader.bearerGen()
trader.logger.info(trader.environment.get("trading") + command + str(params))          
print("header ===>", trader.HEADERS) # my header also seems ok {'User-Agent': 'request', 'Accept': 'application/json', 'Content-Type': 'application/x-www-form-urlencoded', 'Authorization': 'Bearer 4tFG2YFinUb19Z_aAAx-***903be6e55182ac********'}; here I also hide my access token

resp = requests.get("https://api-demo.fxcm.com/candles/1/h1", params=params, headers=trader.HEADERS)
print("error code ===>",resp.status_code) # the error code is 200 which seems ok
json_response = resp.json()
print(json_response) # i get {'response': {'executed': False, 'error': 'Unauthorized'}, 'instrument_id': 0, 'period_id': 0, 'candles': []}
print("Url:",resp.url)# the url is https://api-demo.fxcm.com/candles/1/h1?num=5&from=1498125600&to=1498150800

trader.socketIO.disconnect()

Sincerely yours

**Comment by fxcm-dhalpert** [comment]
when using "datefrom" and "dateto" parameters then don't use the "num" parameter.

**Comment by momodiallosn** [comment]
Hi @fxcm-dhalpert, thanks for you help.
I tried on the one hand using num as the parmaters, on the other the couple datefrom, dateto.
Unfortunately, both failed. Please find below the request for each parameters and the corresponding outputs:

resp = requests.get("https://api-demo.fxcm.com/candles/1/h1", params=params, headers=trader.HEADERS)

1) params = {"from":1498125600,"to":1498150800}
print(trader.HEADERS) #{'User-Agent': 'request', 'Accept': 'application/json', 'Content-Type': 'application/x-www-form-urlencoded', 'Authorization': 'Bearer TuUwvwWt84_4XbwMAFjR****1d60bc6b40113ee788b49bdc3****'} # I updated my token to see if there were something wrong with it

which gave me:

{'response': {'executed': False, 'error': 'Unauthorized'}, 'instrument_id': 0, 'period_id': 0, 'candles': []}
Url: https://api-demo.fxcm.com/candles/1/h1?from=1498125600&to=1498150800

2)params = {"num":num}
print(trader.HEADERS) #{'User-Agent': 'request', 'Accept': 'application/json', 'Content-Type': 'application/x-www-form-urlencoded', 'Authorization': 'Bearer TuUwvwWt84_4XbwMAFjR****1d60bc6b40113ee788b49bdc3****'} # I updated my token to see if there were something wrong with it

which gave me:

{'response': {'executed': False, 'error': 'Unauthorized'}, 'instrument_id': 0, 'period_id': 0, 'candles': []}
Url: https://api-demo.fxcm.com/candles/1/h1?num=10


Sincerly yours

**Comment by fxcm-dhalpert** [comment]
the bearer token should be 67 characters long
"Bearer " + <server socket id = 20 characters> + <user token = 40 characters>

**Comment by fxcm-dhalpert** [comment]
"Bearer" + <server socket id = 20 characters> + <user token = 40 characters>

**Comment by momodiallosn** [comment]
Hi @fxcm-dhalpert ,
I just checked and that the case 
print(len(trader.HEADERS['Authorization'])) gives me 67.
As I mentionned earlier in the script posted in removed some character to hide the access token key.
Sincerely yours

**Comment by momodiallosn** [comment]
Hi @fxcm-dhalpert,
Do you want to me to provide you any further information that may help solving the bug?
Sincerely yours

**Comment by fxcm-dhalpert** [comment]
here is an example how to get historical data with REST API

import time
import requests
import socketio

socketIO = socketio.Client()

TRADING_API_URL = 'https://api-demo.fxcm.com'
WEBSOCKET_PORT = 443
ACCESS_TOKEN = 'e8a43d94deae88f1dd09e321d974e60cfe6fc92b'

def on_connect():
    print ('Websocket connected: ' + socketIO.eio.sid)
        
def on_close():
    print ('Websocket closed.')

def on_error(str1):
    print ('Websocket error.', str1)

if __name__ == '__main__':
        socketIO.connect(TRADING_API_URL +":" +str(WEBSOCKET_PORT) +"/?access_token=" +ACCESS_TOKEN)
                                
        print (socketIO.eio.sid)
        bearer_access_token="Bearer "+ socketIO.eio.sid + ACCESS_TOKEN

        print (bearer_access_token)
        socketIO.on('disconnect', on_close)
        socketIO.on('connect', on_connect)
        socketIO.on('connect_error', on_error) 


        headers = { 'User-Agent': 'request',
            'Accept': 'application/json',
            'Content-Type': 'application/x-www-form-urlencoded',
            'Authorization' : bearer_access_token}

        data = requests.get('https://api-demo.fxcm.com:443/candles/1/H1', headers=headers, params={'num':10}).json()
        print(data)

**Comment by momodiallosn** [comment]
Hi @fxcm-dhalpert ,
thank you for the example above. I am pretty puzzled because I still get the "Not authorized" message.
Please find below the output of the command

`-wiI5wK4DpL8Eo7oAHrR
Bearer -wiI5wK4DpL8Eo7oAHrR107bd0f3572b7764c3c8c997b95aa5b8cc4c0c09
Websocket error. Not authorized
{'response': {'executed': False, 'error': 'Unauthorized'}, 'instrument_id': 0, 'period_id': 0, 'candles': []}`

The script I executed is shown below. There is an indent for each def function that does not appear even with the code tags.

import time
import requests
import socketio

socketIO = socketio.Client()

TRADING_API_URL = 'https://api-demo.fxcm.com'
WEBSOCKET_PORT = 443
ACCESS_TOKEN = '107bd0f3572b7764c3c8c997b95aa5b8cc4c0c09'

def on_connect():
             print ('Websocket connected: ' + socketIO.eio.sid)

def on_close():
            print ('Websocket closed.')

def on_error(str1):
            print ('Websocket error.', str1)


if __name__ == '__main__':

    socketIO.connect(TRADING_API_URL +":" +str(WEBSOCKET_PORT) +"/?access_token=" +ACCESS_TOKEN)

    print (socketIO.eio.sid)
    bearer_access_token="Bearer "+ socketIO.eio.sid + ACCESS_TOKEN

    print (bearer_access_token)
    socketIO.on('disconnect', on_close)
    socketIO.on('connect', on_connect)
    socketIO.on('connect_error', on_error) 


    headers = { 'User-Agent': 'request',
        'Accept': 'application/json',
        'Content-Type': 'application/x-www-form-urlencoded',
        'Authorization' : bearer_access_token}

    data = requests.get('https://api-demo.fxcm.com:443/candles/1/H1', headers=headers, params={'num':10}).json()
    print(data)
    
    socketIO.disconnect()`


Kind regards

**Comment by fxcm-dhalpert** [comment]
can you please email the username and demo token to api@fxcm.com

**Comment by momodiallosn** [comment]
A solution to the problem encountered is given in the github thread above
https://github.com/fxcm/RestAPI/issues/92
