### ISSUE TITLE
close_for_all_symbols(instrument) returns data: "Error: \'for_symbol\' is a required field."

### ISSUE THREAD

**Issue by likamee** [fxcm/RestAPI#86]
Hi, I hope you guys are safe.

I am trying to close a position using the method close_for_all_symbols, but whenever I call the method, passing as parameter the instrument or the entire default values, I receive the following error:
"Error: \'for_symbol\' is a required field."

The weird part is that at the official documentation (https://www.fxcm.com/fxcmpy/05_market_orders.html#Closing-Positions), no such parameter is required.

Best,
Gabriel

**Comment by fxcm-dhalpert** [comment]
unfortunately this function is not workign, for now you can call this API function directly, for example:
POST   /trading/close_all_for_symbol
account_id=680257&forSymbol=true&symbol=GBP%2FUSD&order_type=AtMarket&time_in_force=GTC

**Comment by likamee** [comment]
@fxcm-dhalpert thanks for you reply.
