### ISSUE TITLE
Get previous day close price, volume

### ISSUE THREAD

**Issue by rainb3rry** [fxcm/RestAPI#88]
Hi there, when I get socket stream i have these data for example of BTC/USD

`42["trade_x",{"Updated":1602673591727,"Rates":[11390,11420,11519.8,11352],"Symbol":"BTC/USD"}]`

I know that, the first rate is latest price, third is highest, fourth is lowest but what is the second rate on the array?

and with post request i got like that,

`{"response":{"executed":true,"error":""},"pairs":[{"Updated":1602673688190,"Rates":[11390,11420,11519.8,11352,11390,11420],"Symbol":"BTC/USD"}]}`

first four data seems same with socket output, but what about fifth and sixth?

and finally, how can I get previous day close price and current volume for a BTC/USD ?

Thank you.

**Comment by fxcm-dhalpert** [comment]
the fields are: Bid, Ask, Session High, Session Low
the trading session starts daily at 17:00 EST
the last 2 field can be ignored

**Comment by rainb3rry** [comment]
So, there is no data for calculate last 24 hour change rate and 24 hour trading volume?
like in here, https://www.tradingview.com/symbols/BTCUSD/?exchange=FX

**Comment by FXCMAPI** [comment]
trading view is not our product. please reach their tech support. 
thanks
Lei

**Comment by rainb3rry** [comment]
> trading view is not our product. please reach their tech support.
> thanks
> Lei

I just put this link to show you how tradingview can get **your market** volume data realtime, that's not about tradingview API.
how can i get 24 hour volume data for a symbol through fxcm api?
