### ISSUE TITLE
FXCM Server Down?

### ISSUE THREAD

**Issue by Kofi-Codrington** [fxcm/RestAPI#89]
![image](https://user-images.githubusercontent.com/40256090/96391649-78cead80-1187-11eb-834d-debc8dbf8907.png)

**Comment by FXCMAPI** [comment]
may i know your account number? is that working before?

**Comment by Kofi-Codrington** [comment]
D291127011, will this work with forexconnect?

**Comment by FXCMAPI** [comment]
can you share the password with me?
-Lei

**Comment by Kofi-Codrington** [comment]
Iaaf7

**Comment by Kofi-Codrington** [comment]
Ok so i managed to connect with a new demo server but now i'm having trouble downloading historical data.

`history = fx.get_history("EUR/USD", "m1",
            datetime.strptime("08.06.2020 17:51:21.000", '%m.%d.%Y %H:%M:%S.%f'),
            datetime.strptime("08.06.2020 18:00:21.000", '%m.%d.%Y %H:%M:%S.%f'))`

I am getting one column of dates, no prices

**Comment by FXCMAPI** [comment]
your account has a problem, try to apply a new one.

**Comment by Kofi-Codrington** [comment]
I created a new account to connect, i cannot download history data, can you help?

**Comment by fxcm-dhalpert** [comment]
Please try now, I tested and it seems ok.
