### ISSUE TITLE
Subscribed models and market data issue

### ISSUE THREAD

**Issue by jaimetpearl** [fxcm/RestAPI#9]
I'm running a script that verifies every time a trade is opened/closed and reacts to it.  I use call back functions to react if any of these events happen using the subscription to the data models.  This is the code for the call back functions:

def print_data_model_OP(data):
    global OP_D
    global OP_I
    try:
        if data['action'] != '':
            if data['action'] == 'D':
               print('Open Position Deleted\n')
               OP_D = True 
            if data['action'] == 'I':
               print('Open Position Inserted\n')
               OP_I = True 
    except:
        pass
    
def print_data_model_CL(data):
    global CL_D
    global CL_I
    try:
        if data['action'] != '':
            if data['action'] == 'D':
               print('Closed Trade Deleted\n')
               CL_D = True 
            if data['action'] == 'I':
               print('Closed Trade Inserted\n')
               CL_I = True 
    except:
        pass
    
I realized that the script was getting stuck somewhere whenever one of these functions was called.  I decided to subscribe a call back function to print the market data every 50 changes in price, this way I could monitor if the connection to the API is still alive.  This is my call back function:

def print_data_prices(data, dataframe):
    global connectionCounter
    Bid = float(data['Rates'][0])
    Ask = float(data['Rates'][1])
    Low = float(data['Rates'][2])
    High = float(data['Rates'][3])
    Spread = 10000 * abs( Bid - Ask )
    if connectionCounter > 50:
        print('Time: %s, Bid = %.5f, Ask = %.5f, Low = %.5f, High = %.5f, Spread = %.1f' % ( dt.datetime.now(), Bid, Ask, Low, High, Spread ) )
        connectionCounter = 0    
    connectionCounter = connectionCounter + 1

And this is how I subscribe the data models and price at the beginning of my script:

con.subscribe_data_model('OpenPosition', (print_data_model_OP,))
con.subscribe_data_model('ClosedPosition', (print_data_model_CL,))
con.subscribe_market_data('EUR/USD', (print_data_prices,))

After running the script for a while I couldn't see any pattern, it still gets stuck sometimes after 4hrs, sometimes it could work for as long as 9hrs, but others it just freezes after 1hr.  

Is there a known issue with how the API updates the tables and is there any way/work around on how to fix this?.  Thank you very much!

**Comment by FXCMAPI** [comment]
I assume you use python wrapper fxcmpy on Jupyter Notebook. 
What version do you use? do you see the same on our latest version 1.1.34?
is this issue related to network bandwidth or cache, if you only susbcribe EUR/USD, do you still get stuck?

thanks
Lei

**Comment by jaimetpearl** [comment]
Hi Lei,

Yes, I'm using the latest version 1.1.34 of the python wrapper fxcmpy, and running on Visual Studio Code.  I thought it could be due to bandwidth but already tested it in my local computer and in two different VPS; and in all occasions it got stuck.  I'm only subscribing to EUR/USD.

Thank you!

**Comment by jaimetpearl** [comment]
Hi Lei,
Sure, I'll modify my code and test it.  As soon as I get it done I'll let you know.
Thank you!

**Comment by jaimetpearl** [comment]
Hi Lei,

I tried to run the example you mentioned (before implementing the changes in my own script), but the code seems to haven an issue with the logger.  It gives me the following error:

Exception has occurred: AttributeError
'Trader' object has no attribute 'logger'
  File "D:\Python\Projects\fxcm\fxcm_rest_api_token.py", line 266, in _get_config
    self.logger.error(
  File "D:\Python\Projects\fxcm\fxcm_rest_api_token.py", line 114, in __init__
    self.environment = self._get_config(environment)
  File "D:\Python\Projects\fxcm\fxcmrest_api_test_1.py", line 8, in <module>
    trader = fxcm_rest_api.Trader('****************************************', 'demo') # demo for demo

It seems as if the constructor of the Trader class doesn't initializes the value for the logger, and hence, it gives the error.  However, I'm not sure what value should it be initialize to.

**Comment by FXCMAPI** [comment]
have you try the sample it comes up with? fxcm_rest_client_sample.py
can you share your program fxcmrest_api_test_1.py with me?

**Comment by jaimetpearl** [comment]
Yes, that's the one I was trying (fxcm_rest_client_sample.py).  Then I tried only to connect and get my account details.  Here is the code (for fxcmrest_api_test_1.py):

import  requests
import json
from  importlib import reload
import fxcm_rest_api_token as fxcm_rest_api
import time

trader = fxcm_rest_api.Trader('*******************************', 'demo') # demo for demo 
trader.login()
try:
    print("Logged in, now getting Account details")
    while len(trader.account_list) < 1:
           time.sleep(0.1)
    account_id = trader.account_list[0]
    print(trader.account_id == account_id)
except Exception as e:
    print(str(e))
trader.logout()

**Comment by FXCMAPI** [comment]
this code works on my side. 

import requests
import json
from importlib import reload
import fxcm_rest_api_token as fxcm_rest_api
import time

trader = fxcm_rest_api.Trader('d695e2efe680aeacfdf27bd389a9fe58d9a04ba6', 'demo') # demo for demo
trader.login()
try:
    print("Logged in, now getting Account details")
    while len(trader.account_list) < 1:
           time.sleep(0.1)
    account_id = trader.account_list[0]
    print(trader.account_id == account_id)
except Exception as e:
    print(str(e))

trader.logout()


(base) H:\git\fxcm-api-rest-python3-example>python fxcmrest_api_test_1.py
Logged in, now getting Account details
True

**Comment by jaimetpearl** [comment]
Yes, it works now, sorry about that.  My Visual Studio was trying to fetch the files from a different directory.  I will now modify my script and let you know if it gets stuck again. Thank you!

**Comment by FXCMAPI** [comment]
no problem. I will close this thread for now.
please open a new one 

thanks
Lei
