### ISSUE TITLE
Historical Data

### ISSUE THREAD

**Issue by Kofi-Codrington** [fxcm/RestAPI#90]
I don't understand why its so hard to get historical data on the RestAPI. This is the heart of any trading strategy.  Why is it that when i run:

`con.get_candles('EUR/USD', period='m1')`

I am getting old candles from October 16th? Why is it that the historical data has errors.... Can't the errors be fixed? I have also tried to use ForexConnect which is also not working. It is very frustrating.

![image](https://user-images.githubusercontent.com/40256090/96395111-b9332900-1191-11eb-9a01-639ed35aedc5.png)

**Comment by FXCMAPI** [comment]
we are having issues at the moment, we are working on it. will update you shortly.
