### ISSUE TITLE
Random Authorisation Failed Using Simple Example

### ISSUE THREAD

**Issue by RtypeStudios** [fxcm/RestAPI#92]
Hi There,

I have been testing the below example I've taken from one of the other issues. I'm randomly getting this:

    {'response': {'executed': False, 'error': 'Unauthorized'}, 'instrument_id': 0, 'period_id': 0, 'candles': []}

If I run the below example code a few times, it errors and sometimes randomly works. It seems to work one out of ten times. 

Any ideas what I'm doing wrong? 

    import time
    import requests
    import socketio
    
    socketIO = socketio.Client()

    TRADING_API_URL = 'https://api.fxcm.com'
    WEBSOCKET_PORT = 443
    ACCESS_TOKEN = '<REMOVED>'

    def on_connect():
        print ('Websocket connected: ' + socketIO.eio.sid)

    def on_close():
        print ('Websocket closed.')

    def on_error(str1):
        print ('Websocket error.', str1)
    
    
    if __name__ == '__main__':
    
        try:
            socketIO.connect("{0}:{1}/?access_token={2}".format(TRADING_API_URL, WEBSOCKET_PORT, ACCESS_TOKEN))
    
            print (socketIO.eio.sid)
            bearer_access_token="Bearer "+ socketIO.eio.sid + ACCESS_TOKEN
    
            print (bearer_access_token)
            socketIO.on('disconnect', on_close)
            socketIO.on('connect', on_connect)
            socketIO.on('connect_error', on_error) 
    
            headers = { 'User-Agent': 'request',
                        'Accept': 'application/json',
                        'Content-Type': 'application/x-www-form-urlencoded',
                        'Authorization' : bearer_access_token}

            data = requests.get("{0}:{1}/candles/1/H1".format(TRADING_API_URL, WEBSOCKET_PORT), headers=headers, params={'num':10}).json()
            print(data)

        finally:
            socketIO.disconnect()

Thanks!

**Comment by hamletjunior** [comment]
Hi There!

Is your request (requests.get...) being executed AFTER your on_connect() callback gets executed? You have to wait for the connection to be established before executing any request.

Perhaps you should try to put you request (requests.get...) inside the on_connect() callback. Try this and let me know if it works.

I've been working with this API for a while now and I had to deal with this problem, but I only get disconnected after 40..50 minutes.

If the problem persistis, why don't you try to listen to all other events and see if you're getting errors, disconnect messages and so on?

I know that there are a few events you can listen to beyond disconnect, connect and connect_error:

* message
* connect_timeout
* reconnect
* reconnect_error
* reconnect_failed
* reconnect_attempt

Let me know your progress!

Best Regards,
Hamlet

**Comment by FXCMAPI** [comment]
we use socket and it is stateful connection. 
Our server compare the Bearer token string = Bearer + SessionID + Token with what you sent. 
So please make sure your previous session is closed, otherwise our system will complained and disconnect you if you re-connect too frequently.

**Comment by RtypeStudios** [comment]
@hamletjunior 
Thank you will give that a go. Looks like your right and it might be a race condition where the connect rest call is being made vs the login being completed. Will give it a go this afternoon.

@FXCMAPI 
The example above was from this response from your team: https://github.com/fxcm/RestAPI/issues/85#issuecomment-698733489. 

Additionally, this example doesn't differ much from the one provided in the documentation here: https://fxcm.github.io/rest-api-docs/#tag/Real-Case-Study (the first link titled "Learn how to run BT backtest on FXCM historical data via RestAPI at here. What is bt."

Can you provide a definitive example where the session is closed correctly that follows your best practices?

**Comment by momodiallosn** [comment]
Hi @RtypeStudios ,
did you manadge to find a suitable fix ? Similarly, my script randomly works.
Until  now, I did not had time to get back to it.
Best, Mouhamet.
Ps Happy new year

**Comment by RtypeStudios** [comment]
@momodiallosn its because there is a race condition occurring between logging in and calling other pieces. It seems you can call login and then go on to call other bits before the login has actually completed. 

I haven't looked at this for a while but I found you had to wait for the log to finish and the connection to be established. I'm using this:

        # wait to connect.
        while self.connected == False:
            print("Waiting for connection")
            time.sleep(1)

I'm still hoping for an example from the maintainers of this project that shows the recommended way of handling this. As @hamletjunior mentioned above you should be able to use the self.socketIO.on('connect', self.on_connect) event as well. But that became difficult because I'm calling this in procedural way.

**Comment by hamletjunior** [comment]
Since its a asynchronous call, I call the login and then my thread waits for the on_connect event. Then (and only then) my system goes on with the requests.

**Comment by momodiallosn** [comment]
Thanks @RtypeStudios , @hamletjunior for these solutions.

**Comment by RtypeStudios** [comment]
@hamletjunior could you possibly provide an example of how you are awaiting the on_connect event? I suspect my while loop is a bit hacky and wondered if there is a better way.

**Comment by hamletjunior** [comment]
@RtypeStudios I sure can...but my client is implemented in Java... I decided to implement it in java because I can have more control over the Rest endpoints. 

If I were to make my client using Python, It would be something like this:

`import time
import requests
import socketio

socketIO = socketio.Client()

TRADING_API_URL = 'https://api.fxcm.com'
WEBSOCKET_PORT = 443
ACCESS_TOKEN = '<REMOVED>'
bearer_access_token = ''

def on_connect():
    print ('Websocket connected: ' + socketIO.eio.sid)
    headers = {'User-Agent': 'request',
               'Accept': 'application/json',
               'Content-Type': 'application/x-www-form-urlencoded',
               'Authorization': bearer_access_token}

    data = requests.get("{0}:{1}/candles/1/H1".format(TRADING_API_URL, WEBSOCKET_PORT), headers=headers,
                        params={'num': 10}).json()
    print(data)

def on_close():
    print ('Websocket closed.')

def on_error(str1):
    print ('Websocket error.', str1)


if __name__ == '__main__':

    try:
        socketIO.on('disconnect', on_close)
        socketIO.on('connect', on_connect)
        socketIO.on('connect_error', on_error)

        socketIO.connect("{0}:{1}/?access_token={2}".format(TRADING_API_URL, WEBSOCKET_PORT, ACCESS_TOKEN))
        print (socketIO.eio.sid)
        bearer_access_token="Bearer "+ socketIO.eio.sid + ACCESS_TOKEN
        print (bearer_access_token)

    finally:
        socketIO.disconnect()`

Please note that the request for data is made after the on_connect is called by socketio.

**Comment by hamletjunior** [comment]
@RtypeStudios I sure can...but my client is implemented in Java... I decided to implement it in java because I can have more control over the Rest endpoints.

If I were to make my client using Python, It would be something like this:

import time
import requests
import socketio

socketIO = socketio.Client()

TRADING_API_URL = 'https://api.fxcm.com'
WEBSOCKET_PORT = 443
ACCESS_TOKEN = ''
bearer_access_token = ''

def on_connect():
print ('Websocket connected: ' + socketIO.eio.sid)
headers = {'User-Agent': 'request',
'Accept': 'application/json',
'Content-Type': 'application/x-www-form-urlencoded',
'Authorization': bearer_access_token}

data = requests.get("{0}:{1}/candles/1/H1".format(TRADING_API_URL, WEBSOCKET_PORT), headers=headers,
                    params={'num': 10}).json()
print(data)
def on_close():
print ('Websocket closed.')

def on_error(str1):
print ('Websocket error.', str1)

if name == 'main':

try:
    socketIO.on('disconnect', on_close)
    socketIO.on('connect', on_connect)
    socketIO.on('connect_error', on_error)

    socketIO.connect("{0}:{1}/?access_token={2}".format(TRADING_API_URL, WEBSOCKET_PORT, ACCESS_TOKEN))
    print (socketIO.eio.sid)
    bearer_access_token="Bearer "+ socketIO.eio.sid + ACCESS_TOKEN
    print (bearer_access_token)

finally:
    socketIO.disconnect()
Please note that the request for data is made after the on_connect is called by socketio.

**Comment by hamletjunior** [comment]
@RtypeStudios I sure can...but my client is implemented in Java... I decided to implement it in java because I can have more control over the Rest endpoints.

If I were to make my client using Python, It would be something like this:

**Comment by hamletjunior** [comment]
import time
import requests
import socketio

socketIO = socketio.Client()

TRADING_API_URL = 'https://api.fxcm.com'
WEBSOCKET_PORT = 443
ACCESS_TOKEN = ''
bearer_access_token = ''

def on_connect():
print ('Websocket connected: ' + socketIO.eio.sid)
headers = {'User-Agent': 'request',
'Accept': 'application/json',
'Content-Type': 'application/x-www-form-urlencoded',
'Authorization': bearer_access_token}

data = requests.get("{0}:{1}/candles/1/H1".format(TRADING_API_URL, WEBSOCKET_PORT), headers=headers,
                    params={'num': 10}).json()
print(data)
def on_close():
print ('Websocket closed.')

def on_error(str1):
print ('Websocket error.', str1)

if name == 'main':

try:
    socketIO.on('disconnect', on_close)
    socketIO.on('connect', on_connect)
    socketIO.on('connect_error', on_error)

    socketIO.connect("{0}:{1}/?access_token={2}".format(TRADING_API_URL, WEBSOCKET_PORT, ACCESS_TOKEN))
    print (socketIO.eio.sid)
    bearer_access_token="Bearer "+ socketIO.eio.sid + ACCESS_TOKEN
    print (bearer_access_token)

finally:
    socketIO.disconnect()

**Comment by hamletjunior** [comment]
I'm sorry, I don't know how to quote code like you did... But please note that the code that request the data is only called when the on_connect event is called

**Comment by RtypeStudios** [comment]
Great, thank you!
