### ISSUE TITLE
Problem with historical data

### ISSUE THREAD

**Issue by zj1244** [fxcm/RestAPI#95]
> yes, this has been fixed in the recent release.
> please reopen it if you see any issues
> thanks
> Lei

Originally posted by @FXCMAPI in https://github.com/fxcm/RestAPI/issues/63#issuecomment-595845246

But,The problem is not solved.

Example:
**mt4 and fxcmpy data inconsistency**

![image](https://user-images.githubusercontent.com/29372171/99341346-ad3ba380-28c4-11eb-9680-33e0a3c79f92.png)

![image](https://user-images.githubusercontent.com/29372171/99341852-a2354300-28c5-11eb-8b47-49d60b7c30a3.png)

Hope you can help me

**Comment by hamletjunior** [comment]
Hi! I'm just curious ;-)
The MT4 Data Window shows Bid or Ask values?

**Comment by fxcm-dhalpert** [comment]
All charts in MT4 based on bid prices.

**Comment by zj1244** [comment]
> All charts in MT4 based on bid prices.

can you help me ?thx

**Comment by hamletjunior** [comment]
The closing price matches the 22:00 bid candle. Could it be a TimeZone Configuration problem?

**Comment by zj1244** [comment]
Maybe, But opening price mismatch. So there is still a problem
