### ISSUE TITLE
fxcmpy 1.2.6 subscribe_data_model() comment in source code with wrong information

### ISSUE THREAD

**Issue by luisgarcia2** [fxcm/RestAPI#96]
The function subscribe_data_model() in fxcmpy 1.2.6 has a comment in the source code that says:

>     add_callbacks: list of callables,
>        all methods in that list will be called for every incoming dataset
>        of the model. Such a method has to accept two positional
>        arguments, data and dataframe, say. The first should be a json like
>        object with the new data received by the stream and the second
>        should be a Pandas DataFrame with the collected data.

regarding the parameters of the callable functions in the parameter add_callbacks. But this is wrong, the functions in add_callbacks receive only one argument.

**Comment by FXCMAPI** [comment]
you can try below example
TOKEN = 'your token'
con = fxcmpy.fxcmpy(access_token=TOKEN, log_level='error', server='demo', log_file='log.txt')

def print_data(data):
    print(data)
con.subscribe_data_model('OpenPosition', (print_data,))

**Comment by luisgarcia2** [comment]
Yes, I know how to do it, I just pointed out that the comment should be updated to reflect that. Thanks anyway
