### ISSUE TITLE
Unable to log on to fxcm using Google colab

### ISSUE THREAD

**Issue by zookeeper12** [fxcm/RestAPI#99]
Hi
I have been running my script on colab to test my algorithm successfully until last weekend. 

Error message pops out indicating login error. This happens after trying a script to stop colab from disconnection. The same script runs smoothly on my own jupyter notebook. 

Could any one help to suggest what might have gone wrong?

Thanks

**Comment by lucasdmtn** [comment]
I have the same problem, in google colab and in AWS EC2 instances, i try verify if https is open and with the connection and is ok, i dont know how solve this problem

**Comment by FXCMAPI** [comment]
looks like google colab doesn't work well with our rest API. not sure if any change on colab.
